src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RelatedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relacionado con</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipName>RelatedTos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Descripción</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contexto General</fullName>
                </value>
                <value>
                    <fullName>Métricas y Análisis del Mercado</fullName>
                </value>
                <value>
                    <fullName>Principales Players</fullName>
                </value>
                <value>
                    <fullName>Cadena de Valor y Procesos</fullName>
                </value>
                <value>
                    <fullName>Tendencias</fullName>
                </value>
                <value>
                    <fullName>Principales necesidades</fullName>
                </value>
                <value>
                    <fullName>Oportunidad Sectorial</fullName>
                </value>
                <value>
                    <fullName>Soluciones</fullName>
                </value>
                <value>
                    <fullName>Casos de éxito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/test_adminIndustryTrends.cls
@isTest
private class test_adminIndustryTrends {

    static testMethod void myUnitTest() {
		Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionLocal;

        Account cuentapapa=new Account();
        cuentapapa.Name='test';
        cuentapapa.Region__c=regionLocal.id;
        
        insert cuentapapa;
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.ParentId = cuentapapa.id;
        insert cuenta;
        
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test oppp';
        opp.StageName = 'Open';
        opp.CloseDate = system.today();
        opp.AccountId = cuenta.id;
        insert opp;
        
        Industry_Trend__c it = new Industry_Trend__c();
        it.Industry__c = 'Banking';
        it.Trend__c = 'test';
        it.Region__c = regionGlobal.id;
        insert it;
        
        Strategic_Initiative__c si = new Strategic_Initiative__c();
        si.Account__c = cuenta.id;
        insert si;        

        
        
        adminIndustryTrends p = new adminIndustryTrends();
        
        p.getRegions();
        p.getIndustries();
        p.regionId = regionLocal.id;
        p.industry = 'Banking';
        p.doUpdate();
        p.getHashIndustry();
        p.getTrends();
        p.newTrend.Trend__c = 'test';
        p.newTrend.Industry__c = 'test';
        p.InsertNewTrend();
        
        p.IdtoDel = it.id;
        System.currentPagereference().getParameters().put('IdtoDelete',it.id);

        p.del();
        
    }
    
    static testMethod void validationTypeInNewTrends(){
        
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        adminIndustryTrends controller = new adminIndustryTrends();
        
        controller.tempAccount.Industry = 'Comercio';
        controller.tempAccount.Micro_Industry__c = 'Centros comerciales';
        controller.regionId = regionGlobal.id; 
        
        controller.doUpdate();
        
        controller.InsertNewTrend();
        
        system.assert(controller.erroresDeCarga.size()>0);
    }
    
    static testMethod void validationRelatedTo(){
		
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Industry_Trend__c generalContextTrend = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                      Type__c = 'Contexto General');
        insert generalContextTrend;
        
        adminIndustryTrends controller = new adminIndustryTrends();
        
        controller.tempAccount.Industry = 'Comercio';
        controller.tempAccount.Micro_Industry__c = 'Centros comerciales';
        controller.regionId = regionGlobal.id; 
        
        controller.doUpdate();
        
        controller.newTrend.Type__c = 'Soluciones';
        controller.InsertNewTrend();
        
        system.assertEquals(1, controller.erroresDeCarga.size() );
        
        controller.newTrend.Type__c = 'Soluciones';
        controller.newTrend.RelatedTo__c = generalContextTrend.id;
        controller.InsertNewTrend();
        
        system.assertEquals(1, controller.erroresDeCarga.size() );
        
        controller.newTrend.Type__c = 'Oportunidad Sectorial';
        controller.newTrend.RelatedTo__c = generalContextTrend.id;
        controller.InsertNewTrend();
        
        system.assertEquals(1, controller.erroresDeCarga.size() );
        
        Industry_Trend__c oportunidadTrend = new Industry_Trend__c(type__c = 'Oportunidad Sectorial', Region__c = regionGlobal.id);
        insert oportunidadTrend;
        
        Industry_Trend__c solutionTrend = new Industry_Trend__c(type__c = 'Soluciones', Region__c = regionGlobal.id, RelatedTo__c = oportunidadTrend.id);
        insert solutionTrend;
        
        
        List <Industry_Trend__c> auxList = new List <Industry_Trend__c>();
        auxList.add(solutionTrend);
        auxList.add(oportunidadTrend);
        
        controller.trends = auxList;
        controller.save();
        controller.getSectors();
        controller.getHayErroresDeCarga();
        controller.cleanErrors();
    }
}