src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Outlok_Plan_Comercial__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Outlok_Plan_Comercial</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Previous_Fiscal_Year_Revenue__c</fullName>
        <label>Previous Fiscal Year</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SCP Outlook Plan Comercial</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de SCP Outlook Plan Comercial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Outlook Planes Comerciales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <label>Currency Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_accountHistoricalBusinessWindow.cls
@isTest
private class test_accountHistoricalBusinessWindow {
    
    static testMethod void myUnitTest() {
    //Con industria
        Region__c regionGlobal = new Region__C(name='Global');
        regionGlobal.Currency_Name__c ='asd';
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        regionLocal.Currency_Name__c ='asd';
        insert regionLocal;
        
        Account cuentaPadre =new Account();
        cuentaPadre.Name='testPadre';
        cuentaPadre.Region__c=regionGlobal.id;
        
        insert cuentaPadre;
        
        
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.Region__c=regionLocal.id;
        cuenta.parentId = cuentaPadre.id;
        cuenta.industry = 'Banking';
        
        insert cuenta;
        

        System.currentPagereference().getParameters().put('id',cuenta.id);
        
        accountHistoricalBusinessWindow p_Test = new accountHistoricalBusinessWindow();
        //p_Test.getCurrencies();
        p_Test.SaveChanges();
        p_Test.SaveChanges();
        p_Test.getUserIsoCode();
        p_Test.getCompanyIsoCode();
        
        p_Test.thisyear.a__c = 1;
        p_Test.thisyear.b__c = 1;
        p_Test.thisyear.cc__c = 1;
        
        p_Test.lastyear.a__c = 1;
        p_Test.lastyear.b__c = 1;
        p_Test.lastyear.cc__c = 1;
        
        p_Test.last2year.a__c = 1;
        p_Test.last2year.b__c = 1;
        p_Test.last2year.cc__c = 1;
                
        p_Test.loadData();
        
        /*
        Outlok_Plan_Comercial__c opc = new Outlok_Plan_Comercial__c();
        opc.Previous_Fiscal_Year_Revenue__c = 100000;
        opc.Cuenta__c = cuenta.id;
        insert opc;        
        */
        p_Test.SaveChanges();
        /*
        if (Util.checkMultiCurrencyEnabled()) {
            opc.put('CurrencyIsoCode','EUR');
        }
        update opc;
        p_Test.SaveChanges();                
        */
        
                
    }
}