src/objects/Account_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Data</relationshipLabel>
        <relationshipName>Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunities_With_RDM__c</fullName>
        <label>Opportunities With RDM</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunities_With_VD__c</fullName>
        <label>Opportunities_With_VD</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Data</label>
    <nameField>
        <label>Nombre de Account Data</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Contacts_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts Assessments</relationshipLabel>
        <relationshipName>ContactsAssessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Assessment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OportunityIndustryTrend__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>IndustryTrends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity - Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityIndustryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityPastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>OpportunityPastProvenValueNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Opportunity - PastProvenValueNew</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityPastProvenValueNew Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Opportunity - PastProvenValueNew</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SetOpportunityToAccountDataBatch.cls
global class SetOpportunityToAccountDataBatch implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'select id, opportunities_With_VD__c, opportunities_With_RDM__c, account__c from Account_Data__c';	
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {    
        List<Account_Data__c> accsData = (List<Account_Data__c>)scope;
        
        List<Id> cuentasABuscar = new List<Id>();
        for(Account_Data__c infoCuenta :accsData){
            cuentasABuscar.add(infoCuenta.account__c);
        }
        
        List <Opportunity> oportunidades = [select id, accountId,
                                            (select id from IndustryTrends__r),
                                            (select id from OpportunityPastProvenValueNew__r),
                                            (select id from StrategicInitiatives__r),
                                            (select id from ContactsAssessments__r)
                                            from Opportunity WHERE accountId IN: cuentasABuscar];
        system.debug(oportunidades);
        
        Map <Id, Integer> VDPorCuenta = new Map<Id, Integer>();
        Map <Id, Integer> RDMPorCuenta = new Map<Id, Integer>();
        
        for(Opportunity Opp : oportunidades){
            
            if (!Opp.IndustryTrends__r.isEmpty() || !Opp.OpportunityPastProvenValueNew__r.isEmpty() || !Opp.StrategicInitiatives__r.isEmpty()) {
                Integer valorVD = VDPorCuenta.get(Opp.accountId);
                if(valorVD != null){
                    VDPorCuenta.put(Opp.accountId, valorVD+1);
                }else{
                    VDPorCuenta.put(Opp.accountId, 1);  
                }
            }
            if ( !(Opp.ContactsAssessments__r.isEmpty()) ) {
                Integer valorRDM = RDMPorCuenta.get(Opp.accountId);
                if(valorRDM != null){
                    RDMPorCuenta.put(Opp.accountId, valorRDM+1);
                }else{
                    RDMPorCuenta.put(Opp.accountId, 1);  
                }
            }
        }
        
        for(Account_Data__c cuenta: accsData){
			
            Integer VD = VDPorCuenta.get(cuenta.account__c);
            if(VD != null){
                cuenta.opportunities_With_VD__c = VD;
            }
            
            Integer RDM = RDMPorCuenta.get(cuenta.account__c);
            if(RDM != null){
                cuenta.opportunities_With_RDM__c = RDM;
            }
        }
        
        update accsData;
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}