src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Brand_Opportunities__c</fullName>
        <label>Brand Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Strengths__c</fullName>
        <label>Brand Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Threats__c</fullName>
        <label>Brand Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Weakness__c</fullName>
        <label>Brand Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSAT_Current_Year__c</fullName>
        <label>CSAT Current Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Last_Year__c</fullName>
        <label>CSAT Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Second_To_Last_Year__c</fullName>
        <label>CSAT Second To Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Unit__c</fullName>
        <label>CSAT Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Opportunities__c</fullName>
        <label>Other Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Strengths__c</fullName>
        <label>Other Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Threats__c</fullName>
        <label>Other Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Weakness__c</fullName>
        <label>Other Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Opportunities__c</fullName>
        <label>People Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Strengths__c</fullName>
        <label>People Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Threats__c</fullName>
        <label>People Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Weakness__c</fullName>
        <label>People Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Opportunities__c</fullName>
        <label>Products/Services Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Strengths__c</fullName>
        <label>Products/Services Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Threats__c</fullName>
        <label>Products/Services Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Weakness__c</fullName>
        <label>Products/Services Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Account_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>Account_Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fact__c</fullName>
        <label>Fact</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Account Competitor</label>
    <nameField>
        <label>Nombre de nuestro Competidor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/accountOverallRelationshipWindow.cls
public class accountOverallRelationshipWindow {

    public Account account { get; set; }

    public Account_Competitor__c newCompetitor {get;set;}
    
    public List<Account_Competitor__c> newCompetitors { get; set; }
    
    public Integer year {get;set;}
    
    public String delid {
        get;
        set {
            delid = value;
        }
    }    
    
    public Boolean canEdit {get;set;}

    
    public accountOverallRelationshipWindow(){
        init();
    }
    
    private void init() {
    	this.account = [SELECT name, id, parentId, Industry, Region__c,
            Brand_Strengths__c, Brand_Weakness__c, Brand_Opportunities__c, Brand_Threats__c,
            Products_Services_Strengths__c, Products_Services_Weakness__c, Products_Services_Opportunities__c, Products_Services_Threats__c,
            People_Strengths__c, People_Weakness__c, People_Opportunities__c, People_Threats__c,
            Other_Strengths__c, Other_Weakness__c, Other_Opportunities__c, Other_Threats__c,
            CSAT_Unit__c, CSAT_Current_Year__c, CSAT_Last_Year__c, CSAT_Second_To_Last_Year__c
            FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
    
      	newCompetitors = new List<Account_Competitor__c>([SELECT Id, Name, Fact__c, LastModifiedDate FROM Account_Competitor__c where Account__c = :account.Id order by createdDate]);
		
		//InsertCompetitor();
		newCompetitor = new Account_Competitor__c(Account__c = account.id);
		
        Date today = Date.today();
        
        //this.year = today.year() -1;
        this.year = today.year();
        
        //Funcion que engloba si el el usuario acutal puede o no escribir en esta cuenta
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account);
    }
    
    public PageReference SaveChanges() {
        List<Account_Competitor__c> lista_ac=new List<Account_Competitor__c>();
        List<Account_Competitor__c> lista_ac2=new List<Account_Competitor__c>();
        for(Account_Competitor__c ac:newCompetitors){
          if((((ac.Name!='' && ac.Name!=null) || (ac.Fact__c!='' && ac.Fact__c!=null)) && ac.id==null) || ac.id!=null)
            lista_ac.add(ac);
        }
        upsert lista_ac;
        update account;
        
        newCompetitors = new List<Account_Competitor__c>([SELECT Id, Name, Fact__c, LastModifiedDate FROM Account_Competitor__c where Account__c = :account.Id order by createdDate]);
        //InsertCompetitor();
        
        return null;
    }
    
    public void DeleteCompetitor() {
      List<Account_Competitor__c> lista_ac=new List<Account_Competitor__c>();
      for(Account_Competitor__c ac:newCompetitors){
        if(ac.Id!=null && ac.Id==delid){
          delete ac;
        }else{
          lista_ac.add(ac);
        }
      }
      newCompetitors=lista_ac;
    }
    
  	public PageReference add() {
  		insert newCompetitor;
  		init();
  		return null; 
  	}
  
  
    public void InsertCompetitor() {
        newCompetitors.add(new Account_Competitor__c(Account__c = account.id));
    }
  

}