src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/KPI__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Name__c</fullName>
        <label>Internal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>KPIs</relationshipLabel>
        <relationshipName>KPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Sector__c</fullName>
        <label>Sub_Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Machinery</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Not</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Recreation</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Telecommunications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/adminKPI.cls
public class adminKPI {

    public String title { get; set; }

    public String regionId { get; set;}

    public String industry { get; set; }
    
    public Region__c region { get; set;} 
    
    public List< KPI__c > KPI;
    
    public List< KPI__c > globalKPI {get; set;}
    
    public KPI__c newKPI { get; set; }
    
    public String IdtoDel {get; set;}

    
    public Boolean canEdit {get;set;}
    
    
    public Account tempAccount{get;set;}

    
    public adminKPI(){
    
        KPI = new List<KPI__c>();
        title = 'Choose a Region and Industry to start';
        tempAccount = new Account();
    }

    public List<KPI__c> getKPI(){
        return KPI;
    }
    

    public List<SelectOption> getRegions(){
        List<SelectOption> options = new List<SelectOption>();

    
        List<Region__c> temp =  [SELECT Name,Id From Region__c ORDER BY name ASC];
        
       for( Region__c c : temp)
       {
          options.add(new SelectOption(c.Id,c.Name));
       }  
       return options;
        
    }
    
    public List<SelectOption> getIndustries(){
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult = Account.Industry.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple) {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }
       options.add(new SelectOption('All', 'All'));
       return options;
    }
    
    public PageReference save(){
    	Update globalKPI;
    	Update KPI;    	
    	return null;
    }
    
    public void doUpdate(){
      
      industry=tempAccount.Industry;      
      /*
        region = [SELECT Id, Name FROM Region__c WHERE Id = :regionId];
        KPI = [SELECT Name__c,Unit__c FROM KPI__c WHERE Region__c = :regionId AND Industry__c = :industry];
        
        List<Region__Share> tempedit = [select Id from Region__Share WHERE AccessLevel = 'Edit' AND ParentId =:regionId AND UserOrGroupId =:UserInfo.getUserId()];
        
        if(tempedit.size() > 0)
            canEdit = true;
        else
            canEdit = false;
        
        newKPI = new KPI__c();
        newKPI.Region__c = regionId;
        newKPI.Industry__c = industry;
        title = 'Viewing ' + region.Name + ' region and ' + industry + ' industry';
        */
        
        region = [SELECT Id, Name FROM Region__c WHERE Id = :regionId];
        //system.debug('region');
        
        if (tempAccount.Industry == 'Todos') {
        	tempAccount.Micro_Industry__c = 'Todos';
        } else if ( tempAccount.Industry == 'All') {
        	tempAccount.Micro_Industry__c = 'All';
        }
       	        
        List<Region__Share> tempedit = [select Id from Region__Share WHERE (AccessLevel = 'Edit' OR AccessLevel = 'All') AND ParentId =:regionId AND UserOrGroupId =:UserInfo.getUserId()];
        
        if(tempedit.size() > 0)
            canEdit = true;
        else
            canEdit = false;
        
        //canEdit=true;  
        //system.debug('KPI '+regionId+'-'+tempAccount.Micro_Industry__c+'-'+tempAccount.Sector__c+'-'+tempAccount.Industry); 
        KPI = [SELECT Name,Industry__c,Sub_Sector__c,Sector__c,Name__c,Unit__c FROM KPI__c WHERE Region__c = :regionId AND Industry__c = :tempAccount.Micro_Industry__c AND /*Sector__c = :tempAccount.Sector__c AND*/ Sub_Sector__c = :tempAccount.Industry ORDER BY Name ASC];
        //KPI = [SELECT Name,Industry__c,Sub_Sector__c,Sector__c,Name__c,Unit__c FROM KPI__c WHERE Region__c = :regionId AND Sector__c = :tempAccount.Sector__c AND Sub_Sector__c = :tempAccount.Industry ORDER BY Name ASC];
        //system.debug('KPI : SELECT Name,Industry__c,Sub_Sector__c,Sector__c FROM KPI__c WHERE Region__c = \''+regionId+'\' AND Industry__c = \''+tempAccount.Micro_Industry__c+'\' AND Sector__c = \''+tempAccount.Sector__c+'\' AND Sub_Sector__c = \''+tempAccount.Industry+'\' ORDER BY Name ASC');
        newKPI = new KPI__c();
        newKPI.Region__c = regionId;
        newKPI.Industry__c = tempAccount.Micro_Industry__c;
        newKPI.Sub_Sector__c = tempAccount.Industry;
        newKPI.Sector__c = tempAccount.Sector__c;
        
        title = region.Name + ' > '+tempAccount.Industry+' > '  + tempAccount.Micro_Industry__c;
        //title = 'Viewing ' + region.Name + ' > '+tempAccount.Industry+ ' ('+tempAccount.Sector__c + ' Sector)';
         if(tempAccount.Micro_Industry__c == '' || tempAccount.Industry == '' ||
           tempAccount.Micro_Industry__c == '--None--' || tempAccount.Industry == '--None--' ||
           tempAccount.Micro_Industry__c == null || tempAccount.Industry == null ){
            canEdit = false;
            title = 'Debe seleccionar un Sector y un Subsector';
            industry=null;
        }
    }
    

    public PageReference InsertNewKPI() {
        
        insert newKPI;
        this.doUpdate();
        return null;
    }


    public PageReference del(){
    

        this.IdtoDel = Apexpages.currentPage().getParameters().get('IdtoDelete');  
    
        KPI__c toDel= [ SELECT id FROM KPI__c WHERE Id = :this.IdtoDel];
        
        delete toDel;
        
        doUpdate();
        
        return null;       
    }
    
    
    public void checkStandardKPIs(){
    
        //Busco que en todas las industrias esten los KPIs basicos.
        /*    
        Region__c globalRegion = [SELECT id, name FROM Region__C WHERE name = 'Global'];
        
        List<KPI__c> KPI1 = [SELECT Name__c,Unit__c FROM KPI__c WHERE Internal_Name__c = 'Number of Employees' AND  Region__c = :globalRegion.id AND Industry__c = 'All'];
        if(KPI1.size() == 0){
            KPI__c temp = new KPI__c();
            temp.Internal_Name__c = 'Number of Employees';
            temp.Name__c = System.Label.Employees;
            temp.Unit__c = System.Label.Head_Count;
            temp.Region__c = globalRegion.id;
            temp.Industry__c = 'All';
        
            insert temp;
        }
        
        KPI1 = [SELECT Name__c,Unit__c FROM KPI__c WHERE Internal_Name__c = 'Number of Branches' AND  Region__c = :globalRegion.id AND Industry__c = 'All'];
        if(KPI1.size() == 0){
            KPI__c temp = new KPI__c();
            temp.Internal_Name__c = 'Number of Branches';
            temp.Name__c = System.Label.Number_of_Branches;
            temp.Unit__c = System.Label.Units;
            temp.Region__c = globalRegion.id;
            temp.Industry__c = 'All';
        
            insert temp;
        }
        */
        globalKPI = [SELECT Name__c,Unit__c FROM KPI__c WHERE Industry__c = 'All'];
    }
    
    public String getHashIndustry(){
        if(industry !=null)
            return industry.replaceAll('[^a-zA-Z]', '');
        else
            return '*';
    }
}