src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Criteria__c</fullName>
        <label>Buying Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Analysts_vision__c</fullName>
        <label>External Analysts vision</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Strategic Context</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Capability__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Capabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CapabilityArea__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CapabilityArea</label>
        <referenceTo>CapabilityArea__c</referenceTo>
        <relationshipName>SCP_Capabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>value__c</fullName>
        <label>value</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Capability</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de SCP Capability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Capabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CapabilityArea__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CapabilityArea</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Capability Area</label>
    <nameField>
        <label>Nombre de CapabilityArea</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CapabilityArea</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Value_Chain__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Value Chain</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Value Chain</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Value Chain</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Value_Chain_Capability__c.object
<CustomObject>
    <fields>
        <fullName>Capability__c</fullName>
        <label>GAP Capability</label>
        <referenceTo>Capability__c</referenceTo>
        <relationshipName>Capability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value_Chain__c</fullName>
        <label>GAP Value Chain</label>
        <referenceTo>Value_Chain__c</referenceTo>
        <relationshipName>Value_Chain</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SCP Value Chain - Capability</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de SCP Value Chain - Capability</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Chain - Capability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/accountCapabilityMatrixController.cls
public class accountCapabilityMatrixController {

    public Account account {get;set;}
    public Boolean canEdit {get;set;}
    public CapabilityArea__c newCapabilityArea {get;set;}
    public List<CapabilityWrapper> CapabilityWrapperList {get;set;}
    public List<CapabilityArea__c> capabilityAreaList; 
    private String dblClickToCreate = Label.dblClickToAddCapability;
    public Id capabilityAreaId {get;set;}
    public Id capabilityId {get;set;}    

    public accountCapabilityMatrixController() {        
        account = [SELECT name, id, parentId, Industry,Region__c, External_Analysts_vision__c, Strategic_Context__c, Buying_Criteria__c, Strategic_Context_Last_Update__c FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];    
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account);        
        init();        
    }

    private void init() {
        newCapabilityArea = new CapabilityArea__c(name = '', account__c = account.id);
        
        Map<Id,List<Capability__c>> capabilityMap = new Map<Id,List<Capability__c>>();
        
        capabilityAreaList = [Select id, name, account__c from CapabilityArea__c where account__c = :account.id or account__c = null order by CreatedDate];
        Map<Id,CapabilityArea__c> capabilityAreaMap = new Map<Id,CapabilityArea__c>();
        for (CapabilityArea__c f :capabilityAreaList) {
            capabilityAreaMap.put(f.id,f);
        }        
        
        //Map<Id,CapabilityArea__c> capabilityAreaMap = new Map<Id,CapabilityArea__c>([Select id, name from CapabilityArea__c where account__c = :account.id order by CreatedDate]);
        

        for (CapabilityArea__c f :capabilityAreaList) {
            if (capabilityMap.get(f.id) == null) {
               capabilityMap.put(f.id, new List<Capability__c>());
            }            
        }
        system.debug('>>>>> capabilityAreaMap: ' + capabilityAreaMap);
        system.debug('>>>>> capabilityMap: ' + capabilityMap);
        
        
        List<Capability__c> vcs = [select id, name, value__c, capabilityArea__c, (select value_chain__c, value_chain__r.Name, value_chain__r.value__c from capability__r) from Capability__c where capabilityArea__c in :capabilityAreaMap.keySet() and account__c = :account.id order by CreatedDate];        
        for (Capability__c vc :vcs) {
            if (capabilityMap.get(vc.capabilityArea__c) == null) {
               capabilityMap.put(vc.capabilityArea__c, new List<Capability__c>());
            }
            capabilityMap.get(vc.capabilityArea__c).add(vc);
        }         
                
        CapabilityWrapperList = new List<CapabilityWrapper>();
        
        for (CapabilityArea__c capabilityArea :capabilityAreaList) {
            if (canEdit) {
                capabilityMap.get(capabilityArea.Id).add(new Capability__c(value__c = dblClickToCreate, capabilityArea__c = capabilityArea.Id, account__c = account.id));
            }
            CapabilityWrapper cw = new CapabilityWrapper(capabilityAreaMap.get(capabilityArea.Id),capabilityMap.get(capabilityArea.Id)); 
            CapabilityWrapperList.add(cw);
        }

        system.debug('>>>>> capabilityMap.keySet(): ' + capabilityMap.keySet());
        system.debug('>>>>> CapabilityWrapperList: ' + CapabilityWrapperList);
        
    }

    public PageReference newCapabilityArea() {         
        if (newCapabilityArea.name != null && newCapabilityArea.name != '') {
            insert newCapabilityArea;       
        }
        init();
        return null;
    }
    
    public PageReference saveChanges() {
        List<Capability__c> capabilityToUpdate = new List<Capability__c>();
        //List<Capability__c> capabilityToInsert = new List<Capability__c>();
        List<CapabilityArea__c> capabilityAreaToUpdate = new List<CapabilityArea__c>();
        
        for (CapabilityWrapper cw :CapabilityWrapperList) {
            capabilityAreaToUpdate.add(cw.capabilityArea);
            for (Capability__c vc :cw.capabilityList) {
                if (vc.value__c != dblClickToCreate) {
                    capabilityToUpdate.add(vc);
                }
            }
        }
        
        upsert capabilityToUpdate;
        update capabilityAreaToUpdate;
                
        init();
        return null;
    }
    
    public PageReference deletecapabilityArea() {
        CapabilityArea__c f = new CapabilityArea__c(id = capabilityAreaId);
        delete f;
        init();
        return null;
    }

    public PageReference deleteVC() {
        Capability__c c = new Capability__c(id = capabilityId);
        delete c;
        init();
        return null;
    }
    
    public List<CapabilityWrapper> getCapabilityWrapperList() {
        return CapabilityWrapperList;
    } 

}