src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Success Stories</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Account Competitive Differenciators</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unique_Value__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AdminProvenValueController.cls
public with sharing class AdminProvenValueController {
    
    public List<PastProvenValueNew__c> ProvenValueList {get;set;}
    public String regionId { get; set;}
    public String industry { get; set; }
    public String micro_industry { get; set; }
    public String IdtoDelete {get; set;}
    public PastProvenValueNew__c newPruvenValue {get;set;}
    public Boolean canEdit {get;set;}
    public Account tempAccount{get;set;}
    
    public AdminProvenValueController() {
        init();
    }
    
    private void init() {
        newPruvenValue = new PastProvenValueNew__c();
        ProvenValueList = new List<PastProvenValueNew__c>();
        tempAccount = new Account();
    }
    
    public List<SelectOption> getRegions(){
        List<SelectOption> options = new List<SelectOption>();

    
        List<Region__c> temp =  [SELECT Name,Id From Region__c ORDER BY name ASC];
        
       for( Region__c c : temp) {
          options.add(new SelectOption(c.Id,c.Name));
       }  
       return options;
        
    }
    
    public List<SelectOption> getIndustries(){
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult = Account.Industry.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple) {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }
       options.add(new SelectOption('All', 'All'));       
       return options;
    }
    
    public List<SelectOption> getMicro_Industries(){
      List<SelectOption> options = new List<SelectOption>();
            
       Schema.DescribeFieldResult fieldResult = Account.Micro_Industry__c.getDescribe();
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
       for( Schema.PicklistEntry f : ple) {
          options.add(new SelectOption(f.getLabel(), f.getValue()));
       }
       options.add(new SelectOption('All', 'All'));       
       return options;
    }
    
    public List<SelectOption> getProvenValueTypes() {
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new SelectOption(Label.Industry_Offering,Label.Industry_Offering));
        options.add(new SelectOption(Label.Industry_Success_Stories,Label.Industry_Success_Stories));
        options.add(new SelectOption(Label.Industry_Competitive_Differenciators,Label.Industry_Competitive_Differenciators));
        
        return options;
    }
    
    public PageReference save(){
    	Update ProvenValueList;
    	return null;
    }
    
    public void doUpdate() {
        
        if (tempAccount.Industry == 'Todos') {
        	tempAccount.Micro_Industry__c = 'Todos';
        } else if ( tempAccount.Industry == 'All') {
        	tempAccount.Micro_Industry__c = 'All';
        }
       	        
        newPruvenValue.region__c = regionId;
        //newPruvenValue.Industry__c = industry;
        newPruvenValue.Industry__c = tempAccount.Industry;
        newPruvenValue.Micro_Industry__c = tempAccount.micro_industry__c;
        canEdit = false;
        
        List<Region__Share> tempedit = [select Id from Region__Share WHERE (AccessLevel = 'Edit' OR AccessLevel = 'All') AND ParentId =:regionId AND UserOrGroupId =:UserInfo.getUserId()];
        
        if(tempedit.size() > 0)
            canEdit = true;
        else
            canEdit = false;
        
        if (regionId == null || regionId == '' || tempAccount.Industry == null || tempAccount.Industry == '' || tempAccount.Micro_Industry__c == null || tempAccount.Micro_Industry__c == '') {
            canEdit = false;
        }
        
        ProvenValueList = [select id, Unique_Value__c, Type__c from PastProvenValueNew__c where region__c = :regionId and industry__c = :tempAccount.industry and micro_industry__c = :tempAccount.micro_industry__c];
    }
    
    public PageReference InsertNew() {        
        if (newPruvenValue.Type__c != null && newPruvenValue.Unique_Value__c != null) {
            insert newPruvenValue;
            newPruvenValue = new PastProvenValueNew__c();           
            doUpdate();
        }
        return null;
    }
    
    public PageReference del(){
        
        List<PastProvenValueNew__c> provenValue = [select id from PastProvenValueNew__c where id = :IdtoDelete];
        delete provenValue;
        doUpdate();
        return null;
    }
}