src/objects/Account_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>Account_Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Competitor</label>
    <nameField>
        <label>Nombre de nuestro Competidor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Review</label>
        <referenceTo>Account_Review__c</referenceTo>
        <relationshipLabel>Accounts Data</relationshipLabel>
        <relationshipName>Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Data</relationshipLabel>
        <relationshipName>Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitors_Last_Update__c</fullName>
        <label>Competitors Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Competitors_Number__c</fullName>
        <label>Competitors Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrencyIsoCode__c</fullName>
        <label>CurrencyIsoCode</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunities_With_RDM__c</fullName>
        <label>Opportunities With RDM</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunities_With_VD__c</fullName>
        <label>Opportunities_With_VD</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PNB_Amount__c</fullName>
        <label>PNB Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SCP Past Activity</label>
        <referenceTo>PastActivity__c</referenceTo>
        <relationshipLabel>Accounts Data</relationshipLabel>
        <relationshipName>Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative_Last_Update__c</fullName>
        <label>Strategic Initiative Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative_Number__c</fullName>
        <label>Strategic Initiative Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Data</label>
    <nameField>
        <label>Nombre de Account Data</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Review__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Reviews</relationshipLabel>
        <relationshipName>Accounts_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Review</label>
    <nameField>
        <label>Nombre de Account Review</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PastActivity__c.object
<CustomObject>
    <description>Object that contains past activity with client</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Past_Activitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SCP Past Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Potential_New_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_FCV__c</fullName>
        <label>Estimated FCV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Potential_new_Business__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Potential New Business</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Potential New Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential New Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateAccountDataBatch.cls
global class CreateAccountDataBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
                
        String query = 'select id,'+
                    '(select id, lastModifiedDate from StrategicInitiatives__r order by lastModifiedDate desc),'+
                    '(select id, Estimated_FCV__c from GAP_Potential_New_Business__r),'+
                    '(select id, lastModifiedDate from Account_Competitors__r order by lastModifiedDate desc),'+
                    '(select id from Past_Activitys__r order by year__c desc Limit 1),'+
                    '(select id from Accounts_Reviews__r order by lastModifiedDate desc Limit 1)'+
                    'from account where type != \'Prospect\' AND BI_segment__c = \'Empresas\' ';	

		return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {    
        List<Account> accs = (List<Account>)scope;
        
        List<Account_Data__c> accountDataAInsertar = new List<Account_Data__c>();
        for(Account cuenta: accs){

            Account_Data__c accountData = new Account_Data__c();
			accountData.account__c = cuenta.id;
			accountData.competitors_Number__c = cuenta.account_Competitors__r.size();
			
            if (!cuenta.account_Competitors__r.isEmpty()) {
				accountData.competitors_Last_update__c = cuenta.account_Competitors__r.get(0).lastModifiedDate;
			}
			
            if (!cuenta.Past_Activitys__r.isEmpty()) {
				accountData.past_Activity__c = cuenta.Past_Activitys__r.get(0).id;
			}
			
            accountData.pnb_Amount__c = 0;
            for (Potential_New_Business__c pnb :cuenta.GAP_Potential_New_Business__r) {
				if (pnb.Estimated_FCV__c != null) {
				    accountData.pnb_Amount__c += pnb.Estimated_FCV__c;
				}
			}

			accountData.strategic_Initiative_Number__c = cuenta.StrategicInitiatives__r.size();
			if (!cuenta.StrategicInitiatives__r.isEmpty()) {
				accountData.Strategic_Initiative_Last_Update__c = cuenta.StrategicInitiatives__r.get(0).lastModifiedDate;
			}
			accountData.opportunities_With_RDM__c = 0;
			accountData.opportunities_With_VD__c = 0;
                                    
			if (!cuenta.Accounts_Reviews__r.isEmpty()) {
				accountData.Account_Review__c = cuenta.Accounts_Reviews__r.get(0).id;
			}
			
      		if(util.checkMultiCurrencyEnabled()){
                   accountData.CurrencyIsoCode__c = Util.getCompanyIsoCode();
                
            } else {
              accountData.CurrencyIsoCode__c = '$';  
            }
                                    
			accountDataAInsertar.add(accountData);

        }
        
        insert accountDataAInsertar;
    }
    
    global void finish(Database.BatchableContext BC) {
        Database.executeBatch(new SetOpportunityToAccountDataBatch());
    }
}