src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Brand_Opportunities__c</fullName>
        <label>Brand Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Strengths__c</fullName>
        <label>Brand Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Threats__c</fullName>
        <label>Brand Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Weakness__c</fullName>
        <label>Brand Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Buying_Criteria__c</fullName>
        <label>Buying Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CSAT_Current_Year__c</fullName>
        <label>CSAT Current Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Last_Year__c</fullName>
        <label>CSAT Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Second_To_Last_Year__c</fullName>
        <label>CSAT Second To Last Year</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CSAT_Unit__c</fullName>
        <label>CSAT Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Opportunities__c</fullName>
        <label>Other Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Strengths__c</fullName>
        <label>Other Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Threats__c</fullName>
        <label>Other Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Weakness__c</fullName>
        <label>Other Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Opportunities__c</fullName>
        <label>People Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Strengths__c</fullName>
        <label>People Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Threats__c</fullName>
        <label>People Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>People_Weakness__c</fullName>
        <label>People Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Opportunities__c</fullName>
        <label>Products/Services Opportunities</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Strengths__c</fullName>
        <label>Products/Services Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Threats__c</fullName>
        <label>Products/Services Threats</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Services_Weakness__c</fullName>
        <label>Products/Services Weakness</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Strategic Context</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Account_Competitor__c.object
<CustomObject>
    <label>Account Competitor</label>
    <nameField>
        <label>Nombre de nuestro Competidor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Team_Member__c.object
<CustomObject>
    <label>SCP Account Team Member</label>
    <nameField>
        <label>Account Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Account Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Outlok_Plan_Comercial__c.object
<CustomObject>
    <label>SCP Outlook Plan Comercial</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de SCP Outlook Plan Comercial</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Outlook Planes Comerciales</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PastActivity__c.object
<CustomObject>
    <description>Object that contains past activity with client</description>
    <label>SCP Past Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/accountSCPFullReportNew.cls
public class accountSCPFullReportNew {
    
    public Account account { get; set; }
    
    /* Account Team */
    public List<Account_Team_Member__c> TeamMembers {get;set;}    
    
    /* Industry Trends */
    public List<ExtendedRegion> Regions {get;set;}
    
    /* Strategic Context */
    public List<Account> globalStrategicContext { get; set; }
    public List<Strategic_Initiative__c>  localStrategicInitiatives { get; set; }
    public List<Strategic_Initiative__c>  globalStrategicInitiatives { get; set; }
    public List<String> globalBuyingCriteria {get;set;}

    /* KPI */
    public List <ExtendedKPI> Data {get;set;}    
    public List <ExtendedKPI> globalData {get;set;} 
    public Integer year {get;set;}
    
    /* Overall Relationship */
    public List<Account_Competitor__c> newCompetitors { get; set; }
    
    /* Historical Business Window */
    public PastActivity__c thisyear {get;set;}
    public PastActivity__c lastyear {get;set;}
    public PastActivity__c last2year {get;set;}
    
    /* Review of Current Contracts */
    public List<Contract> contracts {get;set;}
    public List<Contract> competitors_contracts {get;set;}
    
    /* Value Proposition Business Support */
    //public List<accountIndustryTrends.Owrap> oppsList {get;set;}
    
    /* Outlook Revenue and Sales */
    public Outlok_Plan_Comercial__c total_opc { get; set; }
 
    /* SweetSpot */
    public List<ValueChainWrapper> valueChainWrapperList {get;set;}
    public List<CapabilityWrapper> capabilityWrapperList {get;set;}    
    
    public accountSCPFullReportNew() {
        this.account = [Select id, name, Strategic_Context__c, Strategic_Context_Last_Update__c, Buying_Criteria__c, 
                        Brand_Strengths__c, Products_Services_Strengths__c, People_Strengths__c, Other_Strengths__c,
                        Brand_weakness__c, Products_Services_weakness__c, People_weakness__c, Other_weakness__c,
                        Brand_Opportunities__c, Products_Services_Opportunities__c, People_Opportunities__c, Other_Opportunities__c,
                        Brand_threats__c, Products_Services_threats__c, People_threats__c, Other_threats__c,
                        CSAT_Unit__c, CSAT_Second_To_Last_Year__c, CSAT_Last_Year__c, CSAT_Current_Year__c 
                        from account where id = :ApexPages.currentPage().getParameters().get('Id')];
        initIndustryTrends();
        initStrategicContext();
        initKPI();
        initOverallRelationship();
        initHistoricalBusiness();
        initCurrentContracts();
        initValuePropositionBusinessSupport();
        initSweetSpot();        
    }
    
    private void initIndustryTrends() {
        regions = (new accountIndustryTrends()).regions;    
    }
    
    private void initStrategicContext() {
        accountStrategicContextWindow ascw = new accountStrategicContextWindow(); 
        globalStrategicContext = ascw.globalStrategicContext;   
        localStrategicInitiatives = ascw.localStrategicInitiatives;
        globalStrategicInitiatives = ascw.globalStrategicInitiatives;
        globalBuyingCriteria = ascw.globalBuyingCriteria;       
    }
    
    private void initKPI() {
        AccountKPIWindow akw = new AccountKPIWindow();
        Data = akw.Data;
        //globalData = akw.globalData;   
        year = akw.year;        
    }
    
    private void initOverallRelationship() {
        newCompetitors = (new accountOverallRelationshipWindow()).newCompetitors;   
    }
    
    private void initHistoricalBusiness() {
        accountHistoricalBusinessWindow ahbw = new accountHistoricalBusinessWindow();
        thisyear = ahbw.thisyear;       
        lastyear = ahbw.lastyear;       
        last2year = ahbw.last2year;         
    }
    
    private void initCurrentContracts() {
        this.contracts = [select id, ContractNumber, description, StartDate, ContractTerm, EndDate, mrc__c, fcv__c, competitorName__c, isCompetitorContract__c from Contract where accountid = :account.id and isCompetitorContract__c = false];
        this.competitors_contracts = [select id, ContractNumber, description, StartDate, ContractTerm, EndDate, mrc__c, fcv__c, competitorName__c, isCompetitorContract__c from Contract where accountid = :account.id and isCompetitorContract__c = true];
    }
    
    private void initValuePropositionBusinessSupport() {
        //oppsList = (new accountIndustryTrends()).oppsList;
    }    

    private void initSweetSpot() {
         accountValueChainTableController avtc = new accountValueChainTableController();
         valueChainWrapperList = avtc.getValueChainWrapperList(); 
         
         accountCapabilityMatrixController accm = new accountCapabilityMatrixController();
         capabilityWrapperList = accm.getCapabilityWrapperList(); 

    }
}