src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/AccountKPI__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountsKPI</relationshipLabel>
        <relationshipName>AccountsKPI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <label>KPI</label>
        <referenceTo>KPI__c</referenceTo>
        <relationshipLabel>AccountsKPI</relationshipLabel>
        <relationshipName>AccountsKPI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>14</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AccountKPI</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de AccountKPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountsKPI</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/KPI__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>KPIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>KPIs</relationshipLabel>
        <relationshipName>KPIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sub_Sector__c</fullName>
        <label>Sub_Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Machinery</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Not</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Recreation</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Shipping</fullName>
                </value>
                <value>
                    <fullName>Technology</fullName>
                </value>
                <value>
                    <fullName>Telecommunications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>KPI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/accountKPIWindow.cls
public class accountKPIWindow {

    public Account account { get; set; }
    
    public List<KPI__C> KPIs { get; set; }
    
    public List <AccountKPI__c> KPIData {get;set;}
    
    public List <ExtendedKPI> Data {get;set;}
    
    public List <ExtendedKPI> parentData {get;set;}

    public List <ExtendedKPI> localData {get;set;}
        
    public Integer year {get;set;}
    
    public Boolean canEdit {get;set;}
    
    public String delid {get;set;}
    
    private Region__c region {get;set;}
    
    public KPI__c newKPI {get;set;}
    
    public accountKPIWindow(){
        if (Util.globalAccount==null) {
        	this.account = [SELECT name, id, parentId, parent.Name, Industry, Region__c, Micro_Industry__c FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
    	} else {
    		this.account = Util.globalAccount; 
    	}
    	
        //Funcion que engloba si el el usuario acutal puede o no escribir en esta cuenta
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account);

        init();    
    }
    
    private void init() {
    
        this.KPIs = new List<KPI__C>();

        region = Util.getRegionFromAccount(account.Id, account.region__c);
		initNewKpi();
        /*
        List<Region__c> regionsList = [SELECT Id,Name, parent__c FROM Region__c WHERE id = :this.account.region__c];
        region = null;
        if (regionsList.size()>0) {
            region = regionsList.get(0);
        } else {
            region = [SELECT Id,Name, parent__c FROM Region__c WHERE name = 'Global'];
        }
        */
        
        this.loadKPIs(region,this.account.Industry);
        
        this.KPIData = [SELECT KPI__c, Value__c, Year__c, KPI__R.Id FROM AccountKPI__c WHERE Account__c = :this.account.id];
        
        this.Data = new List<ExtendedKPI>();
        
        this.parentData = new List<ExtendedKPI>();
        
        this.localData = new List<ExtendedKPI>();
        
        Date today = Date.today();
        
        this.year = today.year();
        
        for(KPI__C k : KPIs){
            this.Data.add( new ExtendedKPI(k,this.KPIData,year,this.account.id, getRegionKPIName(k)));
        }
        
        for(KPI__C k : [SELECT Name__c,Unit__c FROM KPI__c WHERE account__c = :account.id]) {
            this.localData.add( new ExtendedKPI(k,this.KPIData,year,this.account.id, getLocalKPIName()));
        }       
        
        if (account.ParentId != null) {
            for(KPI__C k : [SELECT Name__c,Unit__c FROM KPI__c WHERE account__c = :account.ParentId]) {
                this.parentData.add( new ExtendedKPI(k,this.KPIData,year,this.account.id, getParentKPIName()));
            }
        }
        
    }
    
    private void initNewKpi() {
    	if (account.region__c == null) {
        	newKPI = new KPI__c(region__c = region.id, account__c = account.id);
        } else {
        	newKPI = new KPI__c(region__c = account.region__c, account__c = account.id);
        }
    }
    
    public void loadKPIs(Region__c region, String industry){
    
        KPIs.addAll([SELECT Name__c,Id,Name,Unit__c, region__r.Name, sub_sector__c, Industry__c FROM KPI__C WHERE Region__C = : region.Id AND sub_sector__c != null and (sub_sector__c = :account.Industry or sub_sector__c = 'All' or sub_sector__c = 'Todos') And (Industry__c = :account.Micro_Industry__c or Industry__c = 'All' or Industry__c = 'Todos')]);
        
        if(region.parent__c != null){
            Region__c parent = [SELECT Id,Name, parent__c FROM Region__c WHERE id = :region.parent__c];
            loadKPIs(parent,industry);
        }
        
    }
    
    public PageReference SaveChanges() {
        update account;

        List<AccountKPI__c> accountKPIToUpsert = new List<AccountKPI__c>();
        List<KPI__c> kpiToUpdate = new List<KPI__c>(); 
        
        for(ExtendedKPI ekpi : Data){
            accountKPIToUpsert.add(ekpi.thisyear);
            accountKPIToUpsert.add(ekpi.lastyear);
            accountKPIToUpsert.add(ekpi.last2year);        
        }
        
        for(ExtendedKPI ekpi : parentData){
            accountKPIToUpsert.add(ekpi.thisyear);
            accountKPIToUpsert.add(ekpi.lastyear);
            accountKPIToUpsert.add(ekpi.last2year);
        }
        
        for(ExtendedKPI ekpi : localData){
            accountKPIToUpsert.add(ekpi.thisyear);
            accountKPIToUpsert.add(ekpi.lastyear);
            accountKPIToUpsert.add(ekpi.last2year);
            kpiToUpdate.add(ekpi.kpi);
        }       
        
        upsert accountKPIToUpsert;
        upsert kpiToUpdate;
        
        return null;
    }
    
    public PageReference addKPI() {
        /*
        KPI__c k;
        if (account.region__c == null) {
        	k = new KPI__c(region__c = region.id, account__c = account.id, Name__c = Label.new_kpi);
        } else {
        	k = new KPI__c(region__c = account.region__c, account__c = account.id, Name__c = Label.new_kpi);
        }
        insert k;
        */
        
        insert newKPI;        
                
        AccountKPI__c a1 = new AccountKPI__c(account__c = account.id);
        AccountKPI__c a2 = new AccountKPI__c(account__c = account.id);
        AccountKPI__c a3 = new AccountKPI__c(account__c = account.id);     
        List<AccountKPI__c> accountKPIs = new List<AccountKPI__c>(); 
        
        localData.add(new ExtendedKPI(newKPI,accountKPIs,year,this.account.id, getLocalKPIName()));
        
        initNewKpi();        
        return null;
    }
    
    public PageReference deleteKPI() {

        KPI__c k = new KPI__c(id=delid);
        delete k;
        
        init();
        
        return null;
    }
    
    public String getIndustry(){
        if(account.industry != null && account.Micro_Industry__c != null)
            return account.Micro_Industry__c.replaceAll('[^a-zA-Z]', '');
        else
            return '';
    }
    
    private String getLocalKPIName() {
        return account.Name + ' (Local)';
    }
    
    private String getParentKPIName() {
        return account.Parent.Name + ' (Parent)';
    }
    
    private String getRegionKPIName(KPI__c k) {
        return 'Sector: ' + k.sub_sector__c + ' - ' + k.industry__c + ' (' + k.region__r.Name + ')';
    }
    
    public PageReference ExportToExcel() {
        return Page.accountKPIWindowExcel;
    }
    
    public String getExcelName() {
        String name = account.Name + '-' + Label.KPI + '.xls';
        return name.replaceAll(' ', '_').replaceAll(',','');
    }   
}