src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Almacenamiento</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Account_Industry_trend__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts &amp; Industry Trends</relationshipLabel>
        <relationshipName>Accounts_Industry_Trends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_state__c</fullName>
        <label>Estado actual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vendido en el pasado</fullName>
                </value>
                <value>
                    <fullName>No aplica</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Accounts &amp; Industry Trends</relationshipLabel>
        <relationshipName>Accounts_Industry_Trends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account - Industry trend</label>
    <nameField>
        <displayFormat>A-IT{0000}</displayFormat>
        <label>Nombre de Account - Industry trend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>RelatedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relacionado con</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipName>RelatedTos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contexto General</fullName>
                </value>
                <value>
                    <fullName>Métricas y Análisis del Mercado</fullName>
                </value>
                <value>
                    <fullName>Principales Players</fullName>
                </value>
                <value>
                    <fullName>Cadena de Valor y Procesos</fullName>
                </value>
                <value>
                    <fullName>Tendencias</fullName>
                </value>
                <value>
                    <fullName>Principales necesidades</fullName>
                </value>
                <value>
                    <fullName>Oportunidad Sectorial</fullName>
                </value>
                <value>
                    <fullName>Soluciones</fullName>
                </value>
                <value>
                    <fullName>Casos de éxito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_InformeSectorizacionController.cls
@isTest
private class Test_InformeSectorizacionController {

    static testMethod void obtengoTodasLasSolucionesYCuentas(){
        
        Account myAccount = new Account(Name = 'Test');
        insert myAccount;

        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Industry_Trend__c solution = new Industry_Trend__c(Region__c = regionGlobal.id, Type__c= 'Soluciones');
        insert solution;
        
        Account_Industry_trend__c myAccountTrend = new Account_Industry_trend__c(Account__c = myAccount.id, 
                                                                                                       Current_state__c = 'No lo poseo y no lo tengo en perspectiva',
                                                                                                       Industry_Trend__c = solution.id);
        insert myAccountTrend;
        
		InformeSectorizacionController controller = new InformeSectorizacionController();
        controller.doFilter();
        
        system.assert(controller.todasLasSoluciones.size() > 0);
        system.assert(controller.accountWrapper.size() > 0);
        system.assert(controller.accountsfiltered.size()>0);
            
    }
    
    static testMethod void forEachAccountIGetAWrapper(){
        
        Account myAccount = new Account(Name = 'Test');
        insert myAccount;

        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Industry_Trend__c solution = new Industry_Trend__c(Region__c = regionGlobal.id, Type__c= 'Soluciones');
        insert solution;
        
        Account_Industry_trend__c myAccountTrend = new Account_Industry_trend__c(Account__c = myAccount.id, 
                                                                                                       Current_state__c = 'Vendido en el pasado',
                                                                                                       Industry_Trend__c = solution.id);
        insert myAccountTrend;
                
        InformeSectorizacionController controller = new InformeSectorizacionController();
        controller.doFilter();
        
        InformeSectorizacionController.AccountStateWrapper wrapper = controller.wrapperAccounts.get(myAccount.id);
        system.assertEquals(myAccount.id, wrapper.account.id);
        
        String state = wrapper.states.get(solution.id);
        system.assertEquals('Vendido en el pasado' , state);
        
    }
    
    static testMethod void theWrapperHaveOneStatePerSolution(){
        
        Account myAccount = new Account(Name = 'Test');
        insert myAccount;

        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Industry_Trend__c solution = new Industry_Trend__c(Region__c = regionGlobal.id, Type__c= 'Soluciones');
        insert solution;
        
        Industry_Trend__c otherSolution = new Industry_Trend__c(Region__c = regionGlobal.id, Type__c= 'Soluciones');
        insert otherSolution;
        
        Account_Industry_trend__c myAccountTrend = new Account_Industry_trend__c(Account__c = myAccount.id, 
                                                                                                       Current_state__c = 'Lo poseo en el funnel',
                                                                                                       Industry_Trend__c = solution.id);
        insert myAccountTrend;
                
        InformeSectorizacionController controller = new InformeSectorizacionController();
        controller.doFilter();
        
        List <Industry_Trend__c> allSolution = [SELECT Id from Industry_Trend__c];
        
        InformeSectorizacionController.AccountStateWrapper wrapper = controller.wrapperAccounts.get(myAccount.id);
        system.assertEquals(allSolution.size(), wrapper.colorList.size());
        
    }
    
    static testMethod void theListOfStatesIsOrderedInRelationToTheListOfSolutions(){
        Account myAccount = new Account(Name = 'Test');
        insert myAccount;

        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Industry_Trend__c solution = new Industry_Trend__c(Region__c = regionGlobal.id, Type__c= 'Soluciones');
        insert solution;
        
        Industry_Trend__c otherSolution = new Industry_Trend__c(Region__c = regionGlobal.id, Type__c= 'Soluciones');
        insert otherSolution;
        
        Account_Industry_trend__c myAccountTrend = new Account_Industry_trend__c(Account__c = myAccount.id, 
                                                                                                       Current_state__c = 'No aplica',
                                                                                                       Industry_Trend__c = solution.id);
        insert myAccountTrend;
                
        InformeSectorizacionController controller = new InformeSectorizacionController();
        controller.doFilter();
        
        InformeSectorizacionController.AccountStateWrapper wrapper = controller.wrapperAccounts.get(myAccount.id);
        system.assertEquals(2, wrapper.colorList.size());
        system.assertEquals('black', wrapper.colorList[1]);
    }
    
    static testMethod void createAllTheWrapperAndThenFilter(){
        Account myAccount = new Account(Name = 'Test');
        insert myAccount;

        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
		
        // need
        Industry_Trend__c need = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                 Type__c= 'Principales necesidades');
        insert need;

        //Opportunities
       	Industry_Trend__c myOpportunity = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                      Type__c = 'Oportunidad Sectorial',
                                                                                      RelatedTo__c = need.id);
        insert myOpportunity;
        
        Industry_Trend__c myOpportunity2 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                       Type__c= 'Oportunidad Sectorial',
                                                                                       RelatedTo__c = need.id);
        insert myOpportunity2;
        
        Industry_Trend__c myOpportunity3 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                       Type__c= 'Oportunidad Sectorial'
                                                                                       );
        insert myOpportunity3;
        
		//solutions for myOpportunity
		Industry_Trend__c solution = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                 Type__c= 'Soluciones',
                                                                                 RelatedTo__c = myOpportunity.id);
        insert solution;
        
        Industry_Trend__c otherSolution = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                      Type__c= 'Soluciones',
                                                                                      RelatedTo__c = myOpportunity.id);
        insert otherSolution;
		
        //solutions for myOpportunity2
		Industry_Trend__c SolutionOpp2 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                     Type__c= 'Soluciones',
                                                                                     RelatedTo__c = myOpportunity2.id);
        insert SolutionOpp2;
        
        Industry_Trend__c otherSolutionOpp2 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                          Type__c= 'Soluciones',
                                                                                          RelatedTo__c = myOpportunity2.id);
        insert otherSolutionOpp2;
        
        //solutions for myOpportunity3
		Industry_Trend__c SolutionOpp3 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                     Type__c= 'Soluciones',
                                                                                     RelatedTo__c = myOpportunity3.id);
        insert SolutionOpp3;

		//================================================================================        
        
		InformeSectorizacionController controller = new InformeSectorizacionController();
        system.assertEquals(1,controller.wrapperNeeds.size() );
        system.assertEquals(5,controller.wrapperSolution.size() );
        controller.wrapperSolution[0].checkBox = true;
        
        controller.doFilter();
        system.assertEquals(1, controller.todasLasSoluciones.size());
        system.assertEquals(1,controller.accountWrapper.size());
        
        controller.wrapperNeeds[0].checkBox = false;
        controller.wrapperSolution[0].checkBox = true;
        controller.doFilter();
        
        system.assertEquals(1, controller.todasLasSoluciones.size());
        system.assertEquals(1, controller.accountWrapper.size() );
        system.assertEquals(1, controller.accountWrapper[0].colorList.size());
		        
    }
    
    static testMethod void iCanFilterByRegionSectorAndSubsector(){
        
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionSeccional = new Region__C(name = 'Venezuela', Parent__c = regionGlobal.id );
        insert regionSeccional;
        
        Account myAccount = new Account(Name = 'Test', Region__c = regionGlobal.id, Industry = 'Transporte', Micro_Industry__c = 'Almacenamiento');
        insert myAccount;
        
        Account accountInOtherRegion = new Account(Name = 'Other region', Region__c = regionSeccional.id, Industry = 'Comercio', Micro_Industry__c = 'Centros Comerciales');
        insert accountInOtherRegion;
        
        // need
        Industry_Trend__c need = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                             Type__c= 'Principales necesidades');
        insert need;
        
        //Opportunities
        Industry_Trend__c myOpportunity = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                      Type__c = 'Oportunidad Sectorial',
                                                                                      RelatedTo__c = need.id);
        insert myOpportunity;
        
        Industry_Trend__c myOpportunity2 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                       Type__c= 'Oportunidad Sectorial',
                                                                                       RelatedTo__c = need.id);
        insert myOpportunity2;
        
        Industry_Trend__c myOpportunity3 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                       Type__c= 'Oportunidad Sectorial'
                                                                                      );
        insert myOpportunity3;
        
        //solutions for myOpportunity
        Industry_Trend__c solution = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                 Type__c= 'Soluciones',
                                                                                 RelatedTo__c = myOpportunity.id);
        insert solution;
        
        Industry_Trend__c otherSolution = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                      Type__c= 'Soluciones',
                                                                                      RelatedTo__c = myOpportunity.id);
        insert otherSolution;
        
        //solutions for myOpportunity2
        Industry_Trend__c SolutionOpp2 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                     Type__c= 'Soluciones',
                                                                                     RelatedTo__c = myOpportunity2.id);
        insert SolutionOpp2;
        
        Industry_Trend__c otherSolutionOpp2 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                          Type__c= 'Soluciones',
                                                                                          RelatedTo__c = myOpportunity2.id);
        insert otherSolutionOpp2;
        
        //solutions for myOpportunity3
        Industry_Trend__c SolutionOpp3 = new Industry_Trend__c(Region__c = regionGlobal.id, 
                                                                                     Type__c= 'Soluciones',
                                                                                     RelatedTo__c = myOpportunity3.id);
        insert SolutionOpp3;
        
        Industry_Trend__c SolutionRegional = new Industry_Trend__c(Region__c = regionSeccional.id, 
                                                                                     Type__c= 'Soluciones',
                                                                                     RelatedTo__c = myOpportunity3.id);
        insert SolutionRegional;
        
       	InformeSectorizacionController controller = new InformeSectorizacionController();
        
        /*
         * 
        controller.regionId = regionGlobal.id;
        controller.criterialAccountFilter.Industry = 'Transporte';
        controller.criterialAccountFilter.Micro_Industry__c = 'Almacenamiento';
        controller.doPanelFilter();
		

        system.assertEquals(1,controller.accountWrapper.size());*/
        
        //system.assertEquals(5, controller.todasLasSoluciones.size());
        
                /*
        controller.regionId = regionSeccional.id; // crear otra region.
        controller.criterialAccountFilter.Industry = 'Transporte';
        controller.criterialAccountFilter.Micro_Industry__c = 'Almacenamiento';
        controller.doPanelFilter();
        
        system.assertEquals(0,controller.accountWrapper.size());
        system.assertEquals(0,controller.todasLasSoluciones.size());
        system.assertEquals(1,controller.errors.size());*/
        
        /*
        controller.regionId = regionSeccional.id;
        controller.criterialAccountFilter.Industry = 'Transporte';
        controller.criterialAccountFilter.Micro_Industry__c = 'Almacenamiento';
        controller.doPanelFilter();
        
        system.assertEquals(0,controller.accountWrapper.size());
        system.assertEquals(0,controller.todasLasSoluciones.size());
        system.assertEquals(1,controller.errors.size());*/
        
        
        //solo sol globales no trae soluciones local(ej: venezuela.)
        controller.regionId = regionGlobal.id;
        controller.criterialAccountFilter.Industry = 'Todos';
        controller.criterialAccountFilter.Micro_Industry__c = 'Todos';
        controller.doPanelFilter();
        
        system.assertEquals(1,controller.accountWrapper.size());
        system.assertEquals(5,controller.todasLasSoluciones.size()); // me trae todas.
        system.assertEquals(0,controller.errors.size());
        
        
        //las soluciones tienen que ser las regionales y globales.
        List <SelectOption> regiones = controller.getRegions();
        controller.regionId = regionSeccional.id;
        controller.criterialAccountFilter.Industry = 'Todos';
        controller.criterialAccountFilter.Micro_Industry__c = 'Todos';
        controller.doPanelFilter();
        
        system.assertEquals(1,controller.accountWrapper.size());
        system.assertEquals(6,controller.todasLasSoluciones.size());
        system.assertEquals(0,controller.errors.size());
    }
    
    
}