src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Evento_BackShop__c.object
<CustomObject>
    <fields>
        <fullName>Cantidad_de_edificios__c</fullName>
        <label>Cantidad de edificios</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cantidad_de_edificios_condicion__c</fullName>
        <label>Cantidad de edificios condicion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FiltroCuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FiltroCuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Eventos BackShop</relationshipLabel>
        <relationshipName>Eventos_BackShop</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Indica_la_cantidad_de_sucursales__c</fullName>
        <label>Indica la cantidad de sucursales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Indica_la_cantidad_de_sucursales_cond__c</fullName>
        <label>Indica la cantidad de sucursales cond</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ingresos_anuales_del_cliente__c</fullName>
        <label>Ingresos anuales del cliente</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ingresos_anuales_del_cliente_condicion__c</fullName>
        <label>Ingresos anuales del cliente condicion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Pais__c</fullName>
        <label>Pais</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>British Indian Ocean Territory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Eventos BackShop</relationshipLabel>
        <relationshipName>Eventos_BackShop</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Comercio</fullName>
                </value>
                <value>
                    <fullName>Comunicaciones y tecnologia</fullName>
                </value>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Industria</fullName>
                </value>
                <value>
                    <fullName>Sector Público</fullName>
                </value>
                <value>
                    <fullName>Servicios</fullName>
                </value>
                <value>
                    <fullName>Servicios Públicos</fullName>
                </value>
                <value>
                    <fullName>Transporte</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_sector__c</fullName>
        <label>Sub sector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sector__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cantidad_de_empleados__c</fullName>
        <label>cantidad de empleados</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cantidad_de_empleados_condicion__c</fullName>
        <label>cantidad de empleados condicion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cuantos_veh_culos_dispone_el_parque__c</fullName>
        <label>cuantos vehículos dispone el parque</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cuantos_veh_culos_dispone_el_parque_cond__c</fullName>
        <label>cuantos vehículos dispone el parque cond</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ispone_de_parque_automotor__c</fullName>
        <label>ispone de parque automotor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Evento BackShop</label>
    <nameField>
        <label>Nombre de BackShop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos BackShop</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/administracionBackShopController.cls
public class administracionBackShopController {

    public List<Evento_BackShop__c> eventosBackShop {get; set;}
    
    public Evento_BackShop__c eventoAInsertar {get; set;}
    
    public String idABorrar {get; set;}
    
    public List<cuentaWrapper> cuentasWpp {get;set;}
    
    public String CuentaABorrarNombre {get;set;}
    
    public administracionBackShopController(){
        
        eventoAInsertar = new Evento_BackShop__c();
        cuentasWpp = new List<cuentaWrapper>();
        
        obtenerEventos();
        
    }
    
    public void obtenerEventos(){
        eventosBackShop = [select id, name, Descripcion__c, Link__c, Pais__c, 
                           Sector__c, Sub_sector__c, Region__c, Cantidad_de_edificios__c, cantidad_de_empleados__c, cuantos_veh_culos_dispone_el_parque__c,
                           Indica_la_cantidad_de_sucursales__c, Ingresos_anuales_del_cliente__c, ispone_de_parque_automotor__c, Cantidad_de_edificios_condicion__c,
                           cantidad_de_empleados_condicion__c, cuantos_veh_culos_dispone_el_parque_cond__c, Indica_la_cantidad_de_sucursales_cond__c, Ingresos_anuales_del_cliente_condicion__c, FiltroCuenta__c
                           from Evento_BackShop__c];
    }
    
    public PageReference InsertarEvento(){
        
        if(eventoAInsertar.name != null && cuentasWpp.size() == 0){
            
            eventoAInsertar.FiltroCuenta__c = null;
            insert eventoAInsertar;
        	eventoAInsertar = new Evento_BackShop__c();
            obtenerEventos();
        }
        
        List<Evento_BackShop__c> lista = new List<Evento_BackShop__c>();
        
        if(eventoAInsertar.name != null && cuentasWpp.size() > 0){
            
            if(eventoAInsertar.sector__c != null || 
            eventoAInsertar.Sub_sector__c != null || 
            eventoAInsertar.Region__c != null || 
            eventoAInsertar.Ingresos_anuales_del_cliente__c != null || 
            eventoAInsertar.cantidad_de_empleados__c != null || 
            eventoAInsertar.Cantidad_de_edificios__c != null || 
            eventoAInsertar.Indica_la_cantidad_de_sucursales__c != null || 
            eventoAInsertar.ispone_de_parque_automotor__c != null || 
            eventoAInsertar.cuantos_veh_culos_dispone_el_parque__c != null
            ){
                Evento_BackShop__c evento = new Evento_BackShop__c();
                evento.name = eventoAInsertar.name;
                evento.sector__c = eventoAInsertar.sector__c;
                evento.Sub_sector__c = eventoAInsertar.Sub_sector__c;
                evento.Region__c = eventoAInsertar.Region__c;
                evento.Ingresos_anuales_del_cliente_condicion__c = eventoAInsertar.Ingresos_anuales_del_cliente_condicion__c;
                evento.Ingresos_anuales_del_cliente__c = eventoAInsertar.Ingresos_anuales_del_cliente__c;
                evento.cantidad_de_empleados_condicion__c = eventoAInsertar.cantidad_de_empleados_condicion__c;
                evento.cantidad_de_empleados__c = eventoAInsertar.cantidad_de_empleados__c;
                evento.Cantidad_de_edificios_condicion__c = eventoAInsertar.Cantidad_de_edificios_condicion__c;
                evento.Cantidad_de_edificios__c = eventoAInsertar.Cantidad_de_edificios__c;
                evento.Indica_la_cantidad_de_sucursales_cond__c = eventoAInsertar.Indica_la_cantidad_de_sucursales_cond__c;
                evento.Indica_la_cantidad_de_sucursales__c = eventoAInsertar.Indica_la_cantidad_de_sucursales__c;
                evento.ispone_de_parque_automotor__c = eventoAInsertar.ispone_de_parque_automotor__c;
                evento.cuantos_veh_culos_dispone_el_parque_cond__c = eventoAInsertar.cuantos_veh_culos_dispone_el_parque_cond__c;
                evento.cuantos_veh_culos_dispone_el_parque__c = eventoAInsertar.cuantos_veh_culos_dispone_el_parque__c;
                evento.Descripcion__c = eventoAInsertar.Descripcion__c;
                evento.Link__c = eventoAInsertar.Link__c;
                lista.add(evento);
                
            }
            
            
            for (cuentaWrapper cuentas : cuentasWpp){
                Evento_BackShop__c evento = new Evento_BackShop__c();
                
                evento.name = eventoAInsertar.name;
                evento.Descripcion__c = eventoAInsertar.Descripcion__c;
                evento.Link__c = eventoAInsertar.Link__c;
                evento.FiltroCuenta__c = cuentas.cuenta;
                
               lista.add(evento);
                
            }
            
            
            
            insert lista;
            eventoAInsertar = new Evento_BackShop__c();
            cuentasWpp = new List<cuentaWrapper>();
            obtenerEventos();
        }
        
        
        return null;
    }
    
    public void renderizarPagina(){
        //lo utilizo para renderizar la pagina al comienzo para que no se genere el #text entre el titulo y el contenido del pageblock section. twisty    
    }
    
    public PageReference borrarEvento(){
        
        Integer i = 0;
        
        for(Evento_BackShop__c evento : eventosBackShop){
            
            if(evento.id == idABorrar){
                break;
            }
            else{
                i++;
            }   
        }
        
        if(eventosBackShop[i].id != null){            
            delete eventosBackShop[i];    
        }
        
        eventosBackShop.remove(i);        
         
        return null;
    }
    
    
    public void agregoCuenta(){
        
        if(eventoAInsertar.FiltroCuenta__c != null){
            Account cuenta = new Account();
            
            cuenta = [SELECT id, name FROM Account WHERE id =: eventoAInsertar.FiltroCuenta__c];
            
            cuentaWrapper cuentaWpp = new cuentaWrapper(cuenta);
            cuentasWpp.add(cuentaWpp);
            
          
            
        }
    }
    
    public void borrarCuentaDeLista(){
        
        system.debug(CuentaABorrarNombre);
        
        Set<cuentaWrapper> cuentasSet = new Set<cuentaWrapper>(cuentasWpp);

        system.debug(cuentasSet);
        
        for(cuentaWrapper cuenta : cuentasSet ){
            if (cuenta.nombre == CuentaABorrarNombre){
                cuentasSet.remove(cuenta);
            }
        }
        
        cuentasWpp = new List<cuentaWrapper>(cuentasSet);
        
        system.debug(cuentasWpp);
        
    }
    
    
    public class cuentaWrapper{
        
        public Id cuenta {get; set;}
        public String nombre {get; set;}
        
        public cuentaWrapper(Account unaCuenta){
            cuenta = unaCuenta.id;
            nombre = unaCuenta.name;
        }
    }
}