src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategic_Context_Last_Update__c</fullName>
        <label>Ultima Actualización</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Context__c</fullName>
        <label>Strategic Context</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

src/objects/Account_Industry_trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Accounts &amp; Industry Trends</relationshipLabel>
        <relationshipName>Accounts_Industry_Trends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Account - Industry trend</label>
    <nameField>
        <displayFormat>A-IT{0000}</displayFormat>
        <label>Nombre de Account - Industry trend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Industry_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>IndustryTrends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Título</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trend__c</fullName>
        <label>Descripción</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OportunityIndustryTrend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Industry Trends</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Industry Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OpportunityIndustryTrend</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Industry Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PastProvenValueNew__c.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Micro Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>GAP_Past_Proven_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Proven Value</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Past Proven Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Proven Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business__c.object
<CustomObject>
    <fields>
        <fullName>Potential_new_Business__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Potential New Business</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Potential New Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential New Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Past_Provent__c.object
<CustomObject>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Past_Provent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Past_Provent</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Past_Provent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Past_Provent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Strategic__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Cnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Cnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Strategic_Cnt</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Strategic_ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Strategic_Cnt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Strategic_Ini__c.object
<CustomObject>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Ini</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipName>Potential_New_Business_Strategic_Ini</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business - Strategic I</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential New Business - Strategic Ini N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business - Strategic I</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business_Trend__c.object
<CustomObject>
    <fields>
        <fullName>Industry_Trend__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Industry Trend</label>
        <referenceTo>Industry_Trend__c</referenceTo>
        <relationshipName>Potential_New_Business_Trend</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Potential_New_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GAP Potential New Business</label>
        <referenceTo>Potential_New_Business__c</referenceTo>
        <relationshipName>Potential_New_Business_Trend</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Potential_New_Business_Trend</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Potential_New_Business_Trend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential_New_Business_Trend</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountGrowthStrategyController.cls
public class AccountGrowthStrategyController {

    public Account account {get;set;}
    public Boolean canEdit {get;set;}
 
    public Id toDel {get;set;}
    
    public List<Strategic_Initiative__c>  localStrategicInitiatives { get; set; }
    public List<Strategic_Initiative__c>  globalStrategicInitiatives { get; set; }
    public List<ExtendedRegion> Regions {get;set;}

    public List<Industry_Trend__c>  solutions { get; set; }

    public List<AccountPastProvenValueNewController.ProvenValueWrapper> provenValueWrapperList {get;set;}
    
    public List<Potential_New_Business__c> PotentialNewBusinessList {get;set;}
    public Potential_New_Business__c potentialNewBusiness {get;set;}

    public Potential_New_Business__c totalPotentialNewBusiness {get;set;}
    
    public List <NecesidadWrapper> necesidadesWpp {get; set;}
    
    Map<Id, OportunidadWrapper> WrappersDeOportunidadPorId {get; set;}
    Map<Id, NecesidadWrapper> WrappersDeNecesidadPorId {get;set;}
 
    public String pnbid {
        get;
        // *** setter is NOT being called ***
        set {
            pnbid = value;
        }
    }
    public String trendid {
        get;
        // *** setter is NOT being called ***
        set {
            trendid = value;
        }
    }

    public String iniciativeid {
        get;
        // *** setter is NOT being called ***
        set {
            iniciativeid = value;
        }
    }
    
    public String pastProventValueid {
        get;
        // *** setter is NOT being called ***
        set {
            pastProventValueid = value;
        }
    }   
  
    public AccountGrowthStrategyController() {        
        if (Util.globalAccount==null) {
        	account = [SELECT name, id, parentId, Industry, Region__c, /*Sector__C,*/ Micro_Industry__c, Strategic_Context__c, Strategic_Context_Last_Update__c, /*(select id from OpportunityStrategicContext__r),*/ (select name, Potential_New_Business__c, Potential_New_Business__r.Name from Potential_New_Business_Strategic_Cnt__r) FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];    
        } else {
    		this.account = Util.globalAccount; 
    	}
        
        userActions temp = new userActions();
        canEdit = temp.checkWrite(this.account);                
        init();        
    }
    
    private void init() {
 
        toDel = null;
                
        localStrategicInitiatives = [SELECT name,Strategic_Initiative__c, LastModifiedDate, title__c, (select id from Opportunities__r where opportunity__r.accountId = :account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.Name, Potential_New_Business__r.Potential_New_Business__c  FROM Potential_New_Business_Strategic_Ini__r) FROM Strategic_Initiative__c WHERE Account__C = :this.account.id];
        globalStrategicInitiatives = new List<Strategic_Initiative__c>();
 
        provenValueWrapperList = new AccountPastProvenValueNewController().provenValueWrapperList;
        
        Region__c region = Util.getRegionFromAccount(account.Id, account.region__c);
        /*
        List<Region__c> regionsList = [SELECT Id,Name, parent__c FROM Region__c WHERE id = :this.account.region__c];
        Region__c region = null;
        if (regionsList.size()>0) {
            region = regionsList.get(0);
        } else {
            region = [SELECT Id,Name, parent__c FROM Region__c WHERE name = 'Global'];
        }
        */
        
        Regions = new List<ExtendedRegion>();
        loadData(region);
                
        if(account.parentId != null) {
            getDataFromParents([SELECT name, id, parentId, Industry,Region__c, Strategic_Context__c, Strategic_Context_Last_Update__c /*, (select name, Opportunity__c from OpportunityStrategicContext__r)*/ FROM Account WHERE Id = :this.account.parentId]);        
        }
        
        PotentialNewBusinessList = [select id, Name, Comments__c, Contact_to_approach__c, Estimated_FCV__c, Potential_new_Business__c, Status__c, (SELECT Industry_Trend__c, Industry_Trend__r.name, Industry_Trend__r.Trend__c FROM Potential_New_Business_Trend__r), (SELECT Strategic_Initiative__c, Strategic_Initiative__r.name, Strategic_Initiative__r.Strategic_Initiative__c FROM Potential_New_Business_Strategic_Ini__r ORDER BY Strategic_Initiative__r.name DESC), (select Past_Proven_Value__c, Past_Proven_Value__r.Name, Past_Proven_Value__r.Unique_Value__c from Potential_New_Business_Past_Provent__r) from Potential_New_Business__c where account__c = :account.id];
        potentialNewBusiness = new  Potential_New_Business__c(Account__c = account.id); 

        List<Id> regionsIds = Util.getParentsRegions(region);
        solutions = [select Region__c, LastModifiedDate,(SELECT Current_state__c FROM Accounts_Industry_Trends__r WHERE Account__c =:account.id), Name, Trend__c, URL_Attachment__c, title__c, relatedTo__c, relatedTo__r.title__c, relatedTo__r.trend__c, relatedTo__r.relatedTo__C, relatedTo__r.relatedTo__r.trend__c, relatedTo__r.relatedTo__r.title__c, (SELECT name, Opportunity__c, Opportunity__r.name FROM Opportunities__R  WHERE Opportunity__r.Account.id = :account.id and Opportunity__r.stagename != 'Closed Won' and Opportunity__r.stagename != 'Closed Lost'), (SELECT id, Potential_New_Business__r.Name, Potential_new_Business__r.Potential_new_Business__c FROM Potential_New_Business_Trend__r) from Industry_Trend__c WHERE Region__c in :regionsIds AND (Sub_Sector__c = :account.Industry or Sub_Sector__c = 'Todos' or Sub_Sector__c = 'All') AND (Industry__c = :account.Micro_Industry__c or Industry__c = 'Todos' or Industry__c = 'All') and type__c = 'Soluciones' ORDER BY Name ASC];


        totalPotentialNewBusiness = new Potential_New_Business__c(Estimated_FCV__c = 0);
        for (Potential_New_Business__c p :PotentialNewBusinessList) {
            if (p.Estimated_FCV__c != null) {
                totalPotentialNewBusiness.Estimated_FCV__c +=  p.Estimated_FCV__c;
            }
        }
        
                //Agregado para nueva tabla.
        
		system.debug(solutions.size());
        necesidadesWpp = new List<NecesidadWrapper>();
        WrappersDeOportunidadPorId = new Map<Id, OportunidadWrapper>();
        WrappersDeNecesidadPorId = new Map<Id, NecesidadWrapper> ();
            for(Industry_trend__c solution: solutions){
                
                SolutionWrapper sw = new SolutionWrapper();
                sw.Trend = solution;
                
                OportunidadWrapper wppOpp = WrappersDeOportunidadPorId.get(solution.RelatedTo__r.id);
                if(wppOpp == null){
                    wppOpp = new OportunidadWrapper(solution.RelatedTo__r.title__c, solution.RelatedTo__r.id);
                    WrappersDeOportunidadPorId.put(solution.RelatedTo__r.id, wppOpp);
                }
                wppOpp.soluciones.add(sw);
                sw.oportunidadIdPadre = wppOpp.oportunidadId;
                
                NecesidadWrapper wppNec = WrappersDeNecesidadPorId.get(solution.RelatedTo__r.RelatedTo__r.id);
                if(wppNec == null){
                    wppNec = new NecesidadWrapper(solution.RelatedTo__r.RelatedTo__r.title__c, solution.RelatedTo__r.RelatedTo__r.id);
                    WrappersDeNecesidadPorId.put(solution.RelatedTo__r.RelatedTo__r.id, wppNec);
                    necesidadesWpp.add(wppNec);
                }
                wppNec.agregarOportunidad(wppOpp);
                wppOpp.necesidadIdPadre = wppNec.necesidadId;
            }

    }
    
    public void loadData(Region__c region){
        /*
        List< Industry_Trend__c > Trends = [select LastModifiedDate, Name, Trend__c, URL_Attachment__c, (select id from Opportunities__r where opportunity__r.accountId = :account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.name, Potential_New_Business__r.Potential_New_Business__c FROM Potential_New_Business_Trend__r) from Industry_Trend__c WHERE Region__c = :region.id AND (Sub_Sector__c = :account.Industry or Sub_Sector__c = 'Todos' or Sub_Sector__c = 'All') And (Industry__c = :account.Micro_Industry__c or Industry__c = 'Todos' or Industry__c = 'All') ORDER BY Name ASC];
 
        Regions.add(new ExtendedRegion(region,Trends));
        if(region.parent__c != null){
            Region__c parent = [SELECT Id,Name, parent__c FROM Region__c WHERE id = :region.parent__c];
            loadData(parent);
        } 
        */
    }
    
    public void del() {
        integer i = 0;
        while(i < PotentialNewBusinessList.size() && PotentialNewBusinessList[i].Id != toDel){
            i++;
        }
        if(i < PotentialNewBusinessList.size()) {
            delete PotentialNewBusinessList[i];
            PotentialNewBusinessList.remove(i);
            provenValueWrapperList = new AccountPastProvenValueNewController().provenValueWrapperList;
        }
    }

    public void getDataFromParents(Account a){
    
        if(a.parentId != null){
            getDataFromParents([SELECT name, id, parentId, Industry,Region__c, Strategic_Context__c/*, (select id from OpportunityStrategicContext__r)*/ FROM Account WHERE Id = :a.parentId]);
        }
            
        List<Strategic_Initiative__c> temp = [SELECT name,Strategic_Initiative__c, LastModifiedDate, title__c, (select id from Opportunities__r where opportunity__r.accountId = :account.id), (SELECT name, Potential_New_Business__c, Potential_New_Business__r.Name, Potential_New_Business__r.Potential_New_Business__c  FROM Potential_New_Business_Strategic_Ini__r) FROM Strategic_Initiative__c WHERE Account__C = :a.id];
        
        if(temp != null)
            globalStrategicInitiatives.addAll(temp);
   
    }

    public PageReference save() {
        //upsert growthStrategyList;
        update PotentialNewBusinessList;
        init();
        return null;        
    }
    
    public PageReference add() {
        upsert potentialNewBusiness;
        init();
        return null;        
    }
    
    public PageReference linkTrend() {        
        insert new Potential_New_Business_Trend__c(Industry_Trend__c = trendid, Potential_New_Business__c = pnbid);
        save();
        return null;
    }

    public PageReference linkIniciative() {
        insert new Potential_New_Business_Strategic_Ini__c(Strategic_Initiative__c = iniciativeid, Potential_New_Business__c = pnbid);
        save();        
        return null;
    }
    
    public PageReference linkPastProventValue() {
        insert new Potential_New_Business_Past_Provent__c(Past_Proven_Value__c = pastProventValueid, Potential_New_Business__c = pnbid);
        save();
        return null;
    }
   
    public PageReference unlinkTrend() {
        delete [SELECT id FROM Potential_New_Business_Trend__c WHERE id = :trendid];
        save();
        return null;
    }
    

    public PageReference unlinkIniciative() {
        delete [SELECT id FROM Potential_New_Business_Strategic_Ini__c WHERE id = :iniciativeid];
        save();
        return null;
    }
    
    public PageReference unlinkPastProventValue() {
        delete [SELECT id FROM Potential_New_Business_Past_Provent__c WHERE id = :pastProventValueid];
        save();
        return null;
    }
   
    public PageReference ExportToExcel() {      
        save();
        return Page.accountGrowthStrategyExcel;
    }
    
    public String getExcelName() {
        String name = account.Name + '-' + Label.GAP_Growth_Strategy + '.xls';
        return name.replaceAll(' ', '_').replaceAll(',','');
    }

    //wrappers 

    public class SolutionWrapper {
        public String oportunidadIdPadre {get; set;}
        public Industry_Trend__c Trend {get; set;}
        public Account_Industry_Trend__c Status {get; set;}
    }
    
    class NecesidadWrapper {
        public String necesidad {get; set;}
        public String necesidadId {get; set;}
        public List<OportunidadWrapper> oportunidades {get; set;}
        
        public NecesidadWrapper (String unaNecesidad, String idPropio){
            necesidad = unaNecesidad;
            necesidadId = idPropio;
            
            oportunidades = new List<OportunidadWrapper>();
        }
        
        public void agregarOportunidad(OportunidadWrapper wppOpp){
            
            boolean contains = false;
            for (Integer i = oportunidades.size() - 1; i >= 0;-- i) {
                if (oportunidades.get(i) == wppOpp) {
                    contains = true;
                }
            }
            
            if(!contains){
                oportunidades.add(wppOpp);    
            }
            
        }
        
    }
    
   public class OportunidadWrapper {
        
        public String Oportunidad {get; set;}
        public String necesidadIdPadre {get; set;}
        public String oportunidadId {get; set;}
        
        public List<SolutionWrapper> soluciones {get; set;}
        
        public OportunidadWrapper (String unaOportunidad, String idPropio){
            Oportunidad = unaOportunidad;
            oportunidadId = idPropio;
            
            soluciones = new List<SolutionWrapper>();
        }
        
        //agregado para victor.
        public Decimal getCantidadDeRenglones(){ 
         
            Decimal renglones = 0;
            system.debug('getCantidadDeRenglones');
            
            for(SolutionWrapper sol: soluciones){
                system.debug('renglones');
            	List <Potential_New_Business_Trend__c> potencialNewBusiness = sol.trend.Potential_New_Business_Trend__r;
                
                system.debug(potencialNewBusiness.size());
                
                Decimal cantidadDePotencialBusiness = potencialNewBusiness.size();
                Decimal divisor = 2;
                Decimal renglonesDeLaSolucion = cantidadDePotencialBusiness / divisor;
                
                system.debug(renglonesDeLaSolucion);
                
                if( (math.mod(potencialNewBusiness.size(), 2) ) == 1 ){
                	renglonesDeLaSolucion = renglonesDeLaSolucion + 0.5;    
                }
                
                system.debug(renglonesDeLaSolucion);
                
                if(renglonesDeLaSolucion == 0){renglonesDeLaSolucion = 1;}
                
                system.debug(renglonesDeLaSolucion);
                    
                renglones = renglones + renglonesDeLaSolucion;
                
                system.debug(renglonesDeLaSolucion);
            }
            
            return renglones;
        }
    }
     
}