src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_Util.cls
@isTest
private class Test_Util {

	static testMethod void checkParentRegions() {
		Region__c r1 = new Region__c(Name = 'r1');
		insert r1;

		Region__c r2 = new Region__c(Name = 'r1', Parent__c = r1.id);
		insert r2;

		Region__c r3 = new Region__c(Name = 'r1', Parent__c = r2.id);
		insert r3;

		system.assertEquals(1, Util.getParentsRegions(r1).size());
		system.assertEquals(2, Util.getParentsRegions(r2).size());
		system.assertEquals(3, Util.getParentsRegions(r3).size());

	}

	
	static testmethod void PuedoEliminarUnObjetoDeUnaLista() {

		List<Region__c> regiones = new List<Region__c> ();

		Region__c r1 = new Region__c(Name = 'r1');
		Account a = new Account(name='asd');
		regiones.add(r1);

		Util.removeObjectFromList(regiones, r1);
		System.assertEquals(0, regiones.size());

		try 
		{	        
		Util.removeObjectFromList(regiones, a);
		}
		catch (UtilException e)
		{
			System.assert(null != e.getMessage());
			System.debug(e.getMessage());
		}
	}

}