src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/FourPlanning__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>conocimiento_de_la_cuenta__c</fullName>
        <label>Coeficiente [d] Desarrollo de Cuenta</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>FourPlanning</label>
    <nameField>
        <label>Nombre de FourPlanning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>4Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Area__c.object
<CustomObject>
    <fields>
        <fullName>FourPlanning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning</label>
        <referenceTo>FourPlanning__c</referenceTo>
        <relationshipLabel>FourPlanning Areas</relationshipLabel>
        <relationshipName>FourPlanning_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FourPlanning Area</label>
    <nameField>
        <label>Nombre de FourPlanning Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_CoeCuenta__c.object
<CustomObject>
    <fields>
        <fullName>Creacion_del_valor__c</fullName>
        <label>Creacion del valor</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FourPlanning CoeCuentas</relationshipLabel>
        <relationshipName>FourPlanning_CoeCuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valor_Coeficiente_De_Cuenta__c</fullName>
        <label>Valor Coeficiente de Cuenta</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FourPlanning CoeCuenta</label>
    <nameField>
        <label>Nombre de FourPlanning CoeCuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning CoeCuentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Reto__c.object
<CustomObject>
    <fields>
        <fullName>FourPlanning_Area__c</fullName>
        <label>FourPlanning Area</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>FourPlanning Retos</relationshipLabel>
        <relationshipName>FourPlanning_Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FourPlanning Reto</label>
    <nameField>
        <label>Nombre de FourPlanning Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FourPlanning_Reto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning Reto</label>
        <referenceTo>FourPlanning_Reto__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nav_Certa__c</fullName>
        <label>Nav Certa</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Probabilidad_de_exito_Certa__c</fullName>
        <label>Probabilidad de exito Certa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>95</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DesarrolloCuentaTest.cls
@isTest
public class DesarrolloCuentaTest {

    static testMethod void poniendoUnIdDeCuentaPuedoVerLaPagina(){
        
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuenta.id;
        insert fourPlanning;
        
        PageReference desarrolloCuenta = Page.DesarrolloCuenta;
        Test.setCurrentPage(desarrolloCuenta);
        desarrolloCuenta.getParameters().put('Id', cuenta.id);
        
        DesarrolloCuentaController controller = new DesarrolloCuentaController();
        
        controller.irACuestionario();
        controller.irAForYou();
        controller.irAPlanDeAccion();
        controller.irAEjesDeTrabajo();
        controller.irAInicio();
        controller.establecerZonaObjetivo();
        system.assert(controller.mostrar);
    }
    
    static testMethod void consigoLosTresPrincipalesRetos(){

        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuenta.id;
        insert fourPlanning;
        
        FourPlanning_Area__c area1 = new FourPlanning_Area__c();
        area1.FourPlanning__c = fourPlanning.id;
        FourPlanning_Area__c area2 = new FourPlanning_Area__c();
        area2.FourPlanning__c = fourPlanning.id;
        
        insert area1;
        insert area2;
        
        FourPlanning_Reto__c reto1area1 = new FourPlanning_Reto__c();
        reto1area1.Nombre_del_Reto__c = 'reto1area1'; 
        reto1area1.FourPlanning_Area__c = area1.id;
        FourPlanning_Reto__c reto2area1 = new FourPlanning_Reto__c();
        reto2area1.Nombre_del_Reto__c='reto2area1';
    	reto2area1.FourPlanning_Area__c = area1.id;
        
        FourPlanning_Reto__c reto1area2 = new FourPlanning_Reto__c();
        reto1area2.Nombre_del_Reto__c = 'reto1area2';
        reto1area2.FourPlanning_Area__c = area2.id;
        
        List<FourPlanning_Reto__c> retos = new List<FourPlanning_Reto__c> {reto1area1, reto1area2, reto2area1};
        insert retos;

        
        PageReference desarrolloCuenta = Page.DesarrolloCuenta;
        Test.setCurrentPage(desarrolloCuenta);
        desarrolloCuenta.getParameters().put('Id', cuenta.id);
        
        DesarrolloCuentaController controller = new DesarrolloCuentaController();

        
		system.assertEquals(3, controller.retosPrincipales.size());        
    }
    
    static testMethod void siSoloTengoDosRetosEnTotalEsosSonLosQueAparecen(){
                
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuenta.id;
        insert fourPlanning;
        
        FourPlanning_Area__c area3 = new FourPlanning_Area__c();
		area3.FourPlanning__c = fourPlanning.id;
        insert area3;
        
        FourPlanning_Reto__c reto1 = new FourPlanning_Reto__c();
        reto1.Nombre_del_Reto__c = 'Reto1';
        reto1.FourPlanning_Area__c = area3.id;
        FourPlanning_Reto__c reto2  = new FourPlanning_Reto__c();
        reto2.Nombre_del_Reto__c = 'Reto2';
    	reto2.FourPlanning_Area__c = area3.id;
        
        List<FourPlanning_Reto__c> retos = new List<FourPlanning_Reto__c> {reto1, reto2};
        insert retos;

        PageReference desarrolloCuenta = Page.DesarrolloCuenta;
        Test.setCurrentPage(desarrolloCuenta);
        desarrolloCuenta.getParameters().put('Id', cuenta.id);
        
        DesarrolloCuentaController controller = new DesarrolloCuentaController();

		system.assertEquals(2, controller.retosPrincipales.size());
		        
    }

    static testMethod void obtengoElPromedioDeConocimientoDeLaCuentaPorPaisCorrectamente(){
        
        
        Region__c regionArgentina = new Region__c();
        insert regionArgentina;
        
        Region__c regionBrasil = new Region__c();
        insert regionBrasil;
        
        Account cuentaArgentina = new Account(name = 'Nombre Cuenta');
        cuentaArgentina.Region__c = regionArgentina.id;
        insert cuentaArgentina;
        
        Account cuentaBrasil = new Account(name = 'Nombre Cuenta');
        cuentaBrasil.Region__c = regionBrasil.id;
        insert cuentaBrasil;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuentaArgentina.id;
        fourPlanning.conocimiento_de_la_cuenta__c = 80;
        insert fourPlanning;
        
        FourPlanning__c fourPlanning2 = new FourPlanning__c();
        fourPlanning2.conocimiento_de_la_cuenta__c = 60;
        fourPlanning2.Cuenta__c = cuentaArgentina.id;
        
        insert fourPlanning2;
        
        FourPlanning__c fourPlanningQueNoSuma = new FourPlanning__c();
        fourPlanningQueNoSuma.conocimiento_de_la_cuenta__c = 80;
        fourPlanningQueNoSuma.Cuenta__c = cuentaBrasil.id;
        insert fourPlanningQueNoSuma;
        
        PageReference desarrolloCuenta = Page.DesarrolloCuenta;
        Test.setCurrentPage(desarrolloCuenta);
        desarrolloCuenta.getParameters().put('Id', cuentaArgentina.id);
        
        DesarrolloCuentaController controller = new DesarrolloCuentaController();
        
        system.assertEquals(70, controller.promedioPais);
    }
    
    static testMethod void consigoLosTresPrincipalesRetosSiEnLasPrimeras2AreasNoTengoRetos(){
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuenta.id;
        insert fourPlanning;
        
        FourPlanning_Area__c area3 = new FourPlanning_Area__c();
        area3.FourPlanning__c = fourPlanning.id;
        FourPlanning_Area__c area4 = new FourPlanning_Area__c();
        area4.FourPlanning__c = fourPlanning.id;
        FourPlanning_Area__c area5 = new FourPlanning_Area__c();
        area5.FourPlanning__c = fourPlanning.id;
        
        insert area3;
        insert area4;
        insert area5;
        
        FourPlanning_Reto__c reto1area3 = new FourPlanning_Reto__c();
        reto1area3.Nombre_del_Reto__c = 'reto1area3'; 
        reto1area3.FourPlanning_Area__c = area3.id;
        
        FourPlanning_Reto__c reto1area4 = new FourPlanning_Reto__c();
        reto1area4.Nombre_del_Reto__c ='reto1area4';
        reto1area4.FourPlanning_Area__c = area4.id;
        
        FourPlanning_Reto__c reto1area5 = new FourPlanning_Reto__c();
        reto1area5.Nombre_del_Reto__c = 'reto1area5';
        reto1area5.FourPlanning_Area__c = area5.id;
        
        List<FourPlanning_Reto__c> retos = new List<FourPlanning_Reto__c> {reto1area3, reto1area4, reto1area5};
            insert retos;
        
        
        PageReference desarrolloCuenta = Page.DesarrolloCuenta;
        Test.setCurrentPage(desarrolloCuenta);
        desarrolloCuenta.getParameters().put('Id', cuenta.id);
        
        DesarrolloCuentaController controller = new DesarrolloCuentaController();
        
        
        system.assertEquals(3, controller.retosPrincipales.size()); 
    }


    static testMethod void seGeneranLos4ObjetosQueDanValorALasEsferasDelGrafico(){
        
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
		
        //Crear los coe de cuenta.
        FourPlanning_CoeCuenta__c coeCuenta = new FourPlanning_CoeCuenta__c();
        coeCuenta.Creacion_del_valor__c = Date.today();
        coeCuenta.Cuenta__c = cuenta.id;
        coeCuenta.Valor_Coeficiente_De_Cuenta__c = 10;
        insert coeCuenta;
        
        FourPlanning_CoeCuenta__c coeCuenta2 = new FourPlanning_CoeCuenta__c();
        coeCuenta2.Creacion_del_valor__c = Date.today().addMonths(-3);
        coeCuenta2.Cuenta__c = cuenta.id;
        coeCuenta2.Valor_Coeficiente_De_Cuenta__c = 20;
        insert coeCuenta2;
        
        FourPlanning_CoeCuenta__c coeCuenta3 = new FourPlanning_CoeCuenta__c();
        coeCuenta3.Creacion_del_valor__c = Date.today().addMonths(-6);
        coeCuenta3.Cuenta__c = cuenta.id;
        coeCuenta3.Valor_Coeficiente_De_Cuenta__c = 30;
        insert coeCuenta3;
        
        FourPlanning_CoeCuenta__c coeCuenta4 = new FourPlanning_CoeCuenta__c();
        coeCuenta4.Creacion_del_valor__c = Date.today().addMonths(-9);
        coeCuenta4.Cuenta__c = cuenta.id;
        coeCuenta4.Valor_Coeficiente_De_Cuenta__c = 40;
        insert coeCuenta4;
        
        
        Opportunity oppTrimestreActual = new Opportunity();
        oppTrimestreActual.AccountId = cuenta.id;
        oppTrimestreActual.Name = 'opp';
        oppTrimestreActual.nav_certa__c = 10;
        oppTrimestreActual.probabilidad_de_exito_certa__c = '25';
        oppTrimestreActual.StageName = 'Value Proposition';
        oppTrimestreActual.CloseDate = Date.today();
        insert oppTrimestreActual;

        Opportunity oppUnTrimestreAnterior = new Opportunity();
        oppUnTrimestreAnterior.AccountId = cuenta.id;
        oppUnTrimestreAnterior.Name = 'opp';
        oppUnTrimestreAnterior.nav_certa__c = 20;
        oppUnTrimestreAnterior.probabilidad_de_exito_certa__c = '25';
        oppUnTrimestreAnterior.StageName = 'F1 - Ganada';
        oppUnTrimestreAnterior.CloseDate = Date.today();
        insert oppUnTrimestreAnterior;
        
        Opportunity oppDosTrimestresAnteriores = new Opportunity();
        oppDosTrimestresAnteriores.AccountId = cuenta.id;
        oppDosTrimestresAnteriores.Name = 'opp';
        oppDosTrimestresAnteriores.nav_certa__c = 30;
        oppDosTrimestresAnteriores.probabilidad_de_exito_certa__c = '25';
        oppDosTrimestresAnteriores.StageName = 'F1 - Ganada';
        oppDosTrimestresAnteriores.CloseDate = Date.today().addMonths(-3);
        insert oppDosTrimestresAnteriores;
        
        Opportunity oppTresTrimestresAnteriores = new Opportunity();
        oppTresTrimestresAnteriores.AccountId = cuenta.id;
        oppTresTrimestresAnteriores.Name = 'opp';
        oppTresTrimestresAnteriores.nav_certa__c = 40;
        oppTresTrimestresAnteriores.probabilidad_de_exito_certa__c = '25';
        oppTresTrimestresAnteriores.StageName = 'F1 - Ganada';
        oppTresTrimestresAnteriores.CloseDate = Date.today().addMonths(-3);
        insert oppTresTrimestresAnteriores;
        
        
        Test.setCreatedDate(oppUnTrimestreAnterior.Id, Date.today().addMonths(-3));
        Test.setCreatedDate(oppDosTrimestresAnteriores.Id, Date.today().addMonths(-6));
        Test.setCreatedDate(oppTresTrimestresAnteriores.Id, Date.today().addMonths(-9));
        Test.startTest();
        
        PageReference desarrolloCuenta = Page.DesarrolloCuenta;
        Test.setCurrentPage(desarrolloCuenta);
        desarrolloCuenta.getParameters().put('Id', cuenta.id);
        
        DesarrolloCuentaController controller = new DesarrolloCuentaController();
        
        Opportunity oppDebug = [select id, createdDate, isClosed from opportunity where id =: oppTresTrimestresAnteriores.id];
        system.debug(oppDebug);
        
        test.stopTest();
    }

}