src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Super_Ball_Arbol__c.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
                <value>
                    <fullName>Gobierno Provincial</fullName>
                </value>
                <value>
                    <fullName>Agricultura y pesca</fullName>
                </value>
                <value>
                    <fullName>Alimentación y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Automoción</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Construcción e inmobiliaria</fullName>
                </value>
                <value>
                    <fullName>Defensa</fullName>
                </value>
                <value>
                    <fullName>Educación</fullName>
                </value>
                <value>
                    <fullName>Farma</fullName>
                </value>
                <value>
                    <fullName>Gobierno Central</fullName>
                </value>
                <value>
                    <fullName>Gobierno Local</fullName>
                </value>
                <value>
                    <fullName>Industria</fullName>
                </value>
                <value>
                    <fullName>Justicia</fullName>
                </value>
                <value>
                    <fullName>Minería y Recursos Naturales</fullName>
                </value>
                <value>
                    <fullName>Ocio y Turismo</fullName>
                </value>
                <value>
                    <fullName>Petróleo y gas</fullName>
                </value>
                <value>
                    <fullName>Químicos</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Salud</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Servicios Profesionales</fullName>
                </value>
                <value>
                    <fullName>Tecnología y Electrónica</fullName>
                </value>
                <value>
                    <fullName>Telecom y Media</fullName>
                </value>
                <value>
                    <fullName>Transporte y Logística</fullName>
                </value>
                <value>
                    <fullName>Utilities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Super Ball - Arbol</label>
    <nameField>
        <label>Nombre de Super Ball - Arbol</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Arboles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Super_Ball_Interlocutor__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Interlocutores</relationshipLabel>
        <relationshipName>Super_Ball_Interlocutores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Interlocutor</label>
    <nameField>
        <label>Nombre de Super Ball - Interlocutor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Interlocutores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Nodo__c.object
<CustomObject>
    <fields>
        <fullName>Nodo_Padre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nodo Padre</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Arbol__c</fullName>
        <label>Super Ball - Arbol</label>
        <referenceTo>Super_Ball_Arbol__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Nodo</label>
    <nameField>
        <label>Nombre de Super Ball - Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Nodos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Pregunta__c.object
<CustomObject>
    <fields>
        <fullName>Dependencia_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependencia No</label>
        <referenceTo>Super_Ball_Pregunta__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas (Dependencia No)</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dependencia_Si__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependencia Si</label>
        <referenceTo>Super_Ball_Pregunta__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pregunta__c</fullName>
        <label>Pregunta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>esHija__c</fullName>
        <defaultValue>false</defaultValue>
        <label>esHija</label>
        <type>Checkbox</type>
    </fields>
    <label>Super Ball - Pregunta</label>
    <nameField>
        <label>Nombre de Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Preguntas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Recurso__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Recursos</relationshipLabel>
        <relationshipName>Super_Ball_Recursos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Recurso</label>
    <nameField>
        <label>Nombre de Super Ball - Nodo Padre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Recursos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Soluciones</relationshipLabel>
        <relationshipName>Super_Ball_Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Solucion</label>
    <nameField>
        <label>Nombre de Super Ball - Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CuestionarioNodosTest.cls
@isTest
public class CuestionarioNodosTest {
    
    static testMethod void creoLosNodos(){
        
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        Super_Ball_Arbol__c arbol = new Super_Ball_Arbol__c(name='arbol');
        arbol.Sector__c = 'Financiero';
        insert arbol;
        
        Super_Ball_Nodo__c nodo = new Super_Ball_Nodo__c(name='nodoPadre');
        nodo.Super_Ball_Arbol__c = arbol.id;
        insert nodo;
        
        Super_Ball_Nodo__c nodoHijo = new Super_Ball_Nodo__c(name='nodoHijo');
        nodoHijo.Super_Ball_Arbol__c = arbol.id;
        nodoHijo.Nodo_Padre__c = nodo.id;
        insert nodoHijo;
        
        Super_Ball_Pregunta__c preguntaSi = new Super_Ball_Pregunta__c(name='a');
        preguntaSi.Super_Ball_Nodo__c = nodoHijo.id;
        preguntaSi.pregunta__c = 'pregunta si';
        preguntaSi.esHija__c = true;
        insert preguntaSi;
        
        Super_Ball_Pregunta__c preguntaNo = new Super_Ball_Pregunta__c(name='a');
        preguntaNo.Super_Ball_Nodo__c = nodoHijo.id;
        preguntaNo.pregunta__c = 'pregunta no';
        preguntaNo.esHija__c = true;        
        insert preguntaNo;
        
        Super_Ball_Pregunta__c pregunta = new Super_Ball_Pregunta__c(name='a');
        pregunta.Super_Ball_Nodo__c = nodoHijo.id;
        pregunta.Dependencia_Si__c = preguntaSi.id;
        pregunta.Dependencia_No__c = preguntaNo.id;
        pregunta.esHija__c = false;
        insert pregunta;
        
        system.debug(preguntaSi.id);
        system.debug(preguntaNo.id);
        
        Super_Ball_Recurso__c recurso = new Super_Ball_Recurso__c(name = 'a');
        recurso.Super_Ball_Nodo__c = nodoHijo.id;
        insert recurso;
        
        Super_Ball_Solucion__c solucion = new Super_Ball_Solucion__c(name='a');
        solucion.Super_Ball_Nodo__c = nodoHijo.id;
        insert solucion;
        
        Super_Ball_Interlocutor__c interlocutor = new Super_Ball_Interlocutor__c(name ='a');
        interlocutor.Super_Ball_Nodo__c = nodoHijo.id;
        insert interlocutor;
        
        Test.setCurrentPageReference(new PageReference('Page.CuestionarioNodos'));
        System.currentPageReference().getParameters().put('IdNodo', nodo.id);
        System.currentPageReference().getParameters().put('Id', cuenta.id);

        CuestionarioNodosController controller = new CuestionarioNodosController();
        controller.traigoRamasDelNodoOLasGenero();
        controller.renderizar();
        controller.guardar();
        controller.irAMapaDeLaCuenta();
        controller.irAMenu();
    }
}