src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/SB_Cuenta_Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>SB - Cuenta - Soluciones</relationshipLabel>
        <relationshipName>SB_Cuenta_Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>estado__c</fullName>
        <label>estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Oportunidades Ganadas</fullName>
                </value>
                <value>
                    <fullName>Oportunidades en Funnel</fullName>
                </value>
                <value>
                    <fullName>Lineas de trabajo Priorizadas</fullName>
                </value>
                <value>
                    <fullName>Lineas a Explorar</fullName>
                </value>
                <value>
                    <fullName>Lineas que no Aplican en el Cliente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SB - Cuenta - Solucion</label>
    <nameField>
        <label>Nombre de SB - Cuenta - Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SB - Cuenta - Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Arbol__c.object
<CustomObject>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripción</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pais__c</fullName>
        <label>Pais</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>España</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Saudi Arabia</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Myanmar</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
                <value>
                    <fullName>Gobierno Provincial</fullName>
                </value>
                <value>
                    <fullName>Agricultura y pesca</fullName>
                </value>
                <value>
                    <fullName>Alimentación y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Automoción</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Construcción e inmobiliaria</fullName>
                </value>
                <value>
                    <fullName>Defensa</fullName>
                </value>
                <value>
                    <fullName>Educación</fullName>
                </value>
                <value>
                    <fullName>Farma</fullName>
                </value>
                <value>
                    <fullName>Gobierno Central</fullName>
                </value>
                <value>
                    <fullName>Gobierno Local</fullName>
                </value>
                <value>
                    <fullName>Industria</fullName>
                </value>
                <value>
                    <fullName>Justicia</fullName>
                </value>
                <value>
                    <fullName>Minería y Recursos Naturales</fullName>
                </value>
                <value>
                    <fullName>Ocio y Turismo</fullName>
                </value>
                <value>
                    <fullName>Petróleo y gas</fullName>
                </value>
                <value>
                    <fullName>Químicos</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Salud</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Servicios Profesionales</fullName>
                </value>
                <value>
                    <fullName>Tecnología y Electrónica</fullName>
                </value>
                <value>
                    <fullName>Telecom y Media</fullName>
                </value>
                <value>
                    <fullName>Transporte y Logística</fullName>
                </value>
                <value>
                    <fullName>Utilities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Super Ball - Arbol</label>
    <nameField>
        <label>Nombre de Super Ball - Arbol</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Arboles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Super_Ball_Nodo__c.object
<CustomObject>
    <fields>
        <fullName>Descripci_n__c</fullName>
        <label>Descripción</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Nodo_Padre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nodo Padre</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Arbol__c</fullName>
        <label>Super Ball - Arbol</label>
        <referenceTo>Super_Ball_Arbol__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Nodo</label>
    <nameField>
        <label>Nombre de Super Ball - Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Nodos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Soluciones</relationshipLabel>
        <relationshipName>Super_Ball_Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Solucion</label>
    <nameField>
        <label>Nombre de Super Ball - Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/graficoSBController.cls
public class graficoSBController {

    Public String idCuenta {get;set;}
    Public String idNodoPadre {get;set;}
    Public Account cuenta {get;set;}
    
    Public Super_Ball_Arbol__c arbol {get;set;}
    Public List<Super_Ball_Nodo__c> nodosHijos {get;set;}
    
    Public List<nodo> todosLosNodos {get;set;}
    Public List<edge> todosLosEdjes {get;set;}
    
    Public String nodosJson {get;set;}
    Public String edgesJson {get;set;}
    
    public graficoSBController(){
        idCuenta = ApexPages.currentPage().getParameters().get('Id');
		idNodoPadre = ApexPages.currentPage().getParameters().get('IdNodo');
        
        nodosHijos = new List<Super_Ball_Nodo__c>();
        todosLosNodos = new List<nodo>();
        todosLosEdjes = new List<edge>();
            
        if(idCuenta!= null){
            cuenta = [select id, name, Industry, Micro_Industry__c, Region__r.name from account where id =: idCuenta];
            traerArbol();
        }
        
    }
    
    public void traerArbol(){
		
        List<Super_Ball_Arbol__c> arboles = new List<Super_Ball_Arbol__c>();
        Set<String> objectFields = Schema.SObjectType.Account.fields.getMap().keySet();        
        if( objectFields.contains('bi_country__c') ) {
            
            list<Account> cuentasTelefonica = database.query('select id, bi_country__c, bi_sector_global__c from account where id=:idCuenta');
            String pais = '';
            String sector = '';
            
            if(cuentasTelefonica.size()>0){
                pais = (String)cuentasTelefonica[0].get('bi_country__c');
                sector = (String)cuentasTelefonica[0].get('bi_sector_global__c');
            }
            
            arboles = [select id, name, descripcion__c, Sector__c, (select id, Descripci_n__c, name from Super_Ball_Nodos__r where nodo_padre__c = null)
                       from Super_Ball_Arbol__c 
                       where Pais__c =: pais and Sector__c =: sector];
        }else{
            
            arboles = [select id, name, descripcion__c, Sector__c, (select id, Descripci_n__c, name from Super_Ball_Nodos__r where nodo_padre__c = null) 
                       from Super_Ball_Arbol__c 
                       where Pais__c =: cuenta.region__r.name and Sector__c =: cuenta.Micro_Industry__c];
        }
        
        if(arboles.size()>0){
            arbol = arboles[0];
        }else{
            arbol = new Super_Ball_Arbol__c();
        }
        
        NodosHijos = [select id, name, nodo_padre__c, (select id, name, Super_Ball_Nodo__c, estado__c, Super_Ball_Solucion__c from SB_Cuenta_Soluciones__r)
                      from Super_Ball_Nodo__c where nodo_padre__c In: arbol.Super_Ball_Nodos__r];
        
        crearNodos();
    }
    
    public void crearNodos(){
        
      crearNodosCentrales();
	  crearSubNodosYEdjes();
      crearEdjesCentrales();
      crearJson();
    }
    
    public void crearNodosCentrales(){
        
        NodoColor colorNodoCentral = new NodoColor();
        colorNodoCentral.background ='#004250';
        colorNodoCentral.border = 'grey';
        
        NodoWidth widthNodoCentral = new NodoWidth();
        widthNodoCentral.maximum = 90;
        widthNodoCentral.minimum = 90;
        
        for(Super_Ball_Nodo__c nodoCentral: arbol.Super_Ball_Nodos__r){
            Nodo nodojs = new Nodo();
            nodojs.id = nodoCentral.id;
            nodojs.label = nodoCentral.name;
            nodojs.color = colorNodoCentral;
            nodojs.shape = 'circle';
            nodojs.widthConstraint = widthNodoCentral;
            nodojs.font = '12px arial white';
            
            todosLosNodos.add(nodojs);
        }
    }
    
    public void crearSubNodosYEdjes(){
        
        system.debug(nodosHijos.size());
        for(Super_Ball_Nodo__c nodoHijo: nodosHijos){
            
            //Creo Edjes
            
            Edge edjeNodo = new Edge();
            edjeNodo.from_x = nodoHijo.nodo_padre__c;
            edjeNodo.to = nodoHijo.id;
            edjeNodo.length = 100;
            
            todosLosEdjes.add(edjeNodo);
            
            //Creo Nodos
            NodoColor color = new NodoColor();
            color.background ='#1696bf';
            color.border = 'grey';
			
            NodoWidth width = new NodoWidth();
            width.maximum = 90;
            width.minimum = 90;
			            
            Nodo nodojs = new Nodo();
            nodojs.id = nodoHijo.id;
            nodojs.label = nodoHijo.name;
            nodojs.color = color;
            nodojs.shape = 'circle';
            nodojs.widthConstraint = width;
            nodojs.font = '10px arial white';
            
            system.debug(nodojs);
            
            todosLosNodos.add(nodojs);
            
            for(SB_Cuenta_Solucion__c solucion: nodoHijo.SB_Cuenta_Soluciones__r){
                NodoColor colorSolucion = new NodoColor();
                colorSolucion.background ='black';
                colorSolucion.border = 'black';
                
                if(solucion.estado__c == 'Oportunidades Ganadas'){colorSolucion.background = '#337ab7';}
                if(solucion.estado__c == 'Oportunidades en Funnel'){colorSolucion.background = 'green';}
                if(solucion.estado__c == 'Lineas de trabajo Priorizadas'){colorSolucion.background = '#ddd301';}
                if(solucion.estado__c == 'Lineas a Explorar'){colorSolucion.background = 'orange';}
                if(solucion.estado__c == 'Lineas que no Aplican en el Cliente'){colorSolucion.background = 'grey';}
                

                Nodo nodoSolucionjs = new Nodo();
                nodoSolucionjs.id = solucion.id;
                nodoSolucionjs.label = solucion.name;
                nodoSolucionjs.color = colorSolucion;
                nodoSolucionjs.shape = 'box';
                nodoSolucionjs.widthConstraint = width;
                nodoSolucionjs.font = '10px arial white';
                
                todosLosNodos.add(nodoSolucionjs);
                
                //creo edjes
                
                Edge edjeSolucion = new Edge();
                edjeSolucion.from_x = solucion.Super_Ball_Nodo__c;
                edjeSolucion.to = solucion.id;
                edjeSolucion.length = 90;
                
                todosLosEdjes.add(edjeSolucion);
                
            }
        }
    }
    
    public void crearEdjesCentrales(){

        
        String nombreRecurso = arbol.Sector__c.replace(' ','');
        
        List<StaticResource> resourceList = [
            SELECT Name, NamespacePrefix, SystemModStamp 
            FROM StaticResource 
            WHERE Name =:nombreRecurso 
        ];
        
        String LinkImagen = '';
        if(resourceList.size()>0){
            LinkImagen = '/resource/'+resourceList[0].SystemModStamp.getTime()+'/certa_scp__'+nombreRecurso;
        }
        
        NodoColor colorNodoOrigen = new NodoColor();
        //colorNodoOrigen.background ='#004250';
        colorNodoOrigen.border = 'grey';
        
        NodoWidth widthNodoOrigen = new NodoWidth();
        widthNodoOrigen.maximum = 500;
        widthNodoOrigen.minimum = 140;
        
        Nodo origen = new Nodo();
        origen.id = 'origen';
        origen.label = arbol.Sector__c;
        origen.color = colorNodoOrigen;
        origen.shape = 'image';
        origen.widthConstraint = widthNodoOrigen;
        origen.font = '14px arial black';
        origen.image = LinkImagen;
        origen.size = 80;
        
        todosLosNodos.add(origen);
        
        for(Integer i = 0; i<arbol.Super_Ball_Nodos__r.size(); i++){
            
            Edge edjeCentral = new Edge();
            edjeCentral.from_x = 'origen';
            edjeCentral.to = arbol.Super_Ball_Nodos__r[i].id;
            edjeCentral.length = 250;
            
            todosLosEdjes.add(edjeCentral);
        }
    }
	
    public void crearJson(){
        nodosJson = JSON.serialize(todosLosNodos);
        edgesJson = JSON.serialize(todosLosEdjes);
        
        edgesJson = edgesJson.replace('from_x', 'from');
        
        system.debug(JSON.serialize(todosLosNodos));
        system.debug(edgesJson);
    }
    
    public PageReference irACuestionario(){
        
        String url = Page.CuestionarioNodos.getURL();
        return new PageReference (url + '?id=' + idCuenta+'&idNodo='+IdNodoPadre);
    }
    
    public PageReference pantallaCompleta(){
        
        String url = Page.graficoFullScreen.getURL();
        return new PageReference (url + '?id=' + idCuenta+'&idNodo='+IdNodoPadre);
    }
    
    public PageReference volverDePantallaCompleta(){
        
        String url = Page.pruebaVis.getURL();
        return new PageReference (url + '?id=' + idCuenta+'&idNodo='+IdNodoPadre);
    }
//=======================================================
    
    public class nodo{
        
        public String id {get;set;}
        public String label {get;set;}
        public NodoColor color {get;set;}
        public String shape {get;set;}
        public NodoWidth widthConstraint {get; set;}
        public String font {get;set;}
        public String image {get;set;}
        public Integer size {get;set;}
        
    }
    
    public class NodoColor{
        
        public String background {get;set;}
        public String border {get;set;}
    }
    
    public class NodoWidth{
        
        public Integer maximum {get;set;}
        public Integer minimum {get;set;}
    }
    
    public class edge{
        //La variable se llama from en el json, pero es una palabra resevada en apex, por lo tanto despues de realizar el json, 
        //aplico un metodo sobre el string para reemplazar "from_x" por "from"
        public String from_x {get;set;}
        public String to {get;set;}
        public Integer length {get;set;}
    }
}