src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Región SCP</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cuentas</relationshipLabel>
        <relationshipName>Cuentas</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_FCV_Calculated__c</fullName>
        <description>Field to calculate the sum of Estimated in Suboportunities</description>
        <inlineHelpText>Adding up the estimated FCV of the sub opportunities win or in progress (not loss or cancelled)
Is the FCV considered for commercial dashboard and reporting
Posible Values: Calculated field in €.
Filled in by: Calculated automatically.</inlineHelpText>
        <label>Campo Inactivo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_FCV__c</fullName>
        <description>Estimated by the account manager in early stages of the opportunity (m€)</description>
        <inlineHelpText>The account manager indicates an estimation of the total value of the project.
Posible Values: Free field in €
Filled in by: The account manager.</inlineHelpText>
        <label>Campo Inactivo</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Year_End_Revenue__c</fullName>
        <label>Ingresos Totales año fiscal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Contract_Value__c</fullName>
        <label>Campo Inactivo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_AccountOpportunities.cls
@isTest
private class test_AccountOpportunities { 
    
    static testMethod void myUnitTest() {
        
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionLocal;
        
        Account cuenta=new Account();
        cuenta.region__c = regionLocal.id;
        cuenta.Name='test';
        
        insert cuenta;
        
        Opportunity opp = new Opportunity(Name = 'Test Opp', accountId = cuenta.id, StageName = 'Prospect', CloseDate = System.Today());
        
        opp.full_contract_value__c = 1000;
        opp.Estimated_Year_End_Revenue__c = 1000;        
        opp.Estimated_FCV__c = 1000;
        opp.Estimated_FCV_Calculated__c = 1000;
        
        insert opp;
        
        Opportunity opp2 = new Opportunity(Name = 'Test Opp2', accountId = cuenta.id, StageName = 'Prospect', CloseDate = System.Today());
        
        opp2.amount = 1000;
                
        insert opp2;
        
        ApexPages.StandardController controller = new ApexPages.StandardController(cuenta);
        
        AccountOpportunities p = new AccountOpportunities(controller);
        p.getFields();
        p.getOperators();
        p.filterLogic = '';
        p.field = 'Name';
		p.operator = '%val%';
		p.value = 'Test';
		
		p.field1 = 'Name';
		p.operator1 = 'val%';
		p.value1 = 'Test';
		
		p.field2 = 'Name';
		p.operator2 = '%val';
		p.value2 = 'Test';
		
		p.field3 = 'Name';
		p.operator3 = '=';
		p.value3 = 'Test';
		

		p.field4 = 'Amount';
		p.operator4 = '!=';
		p.value4 = '2';
        
        p.setFilter();
        
        p.field = 'Name';
		p.operator = '%val%';
		p.value = 'Test';
		
		p.field1 = 'Name';
		p.operator1 = 'val%';
		p.value1 = 'Test';
		
		p.field2 = 'Name';
		p.operator2 = '%val';
		p.value2 = 'Test';
		
		p.field3 = 'Name';
		p.operator3 = '=';
		p.value3 = 'Test';
		
		p.field4 = 'Amount';
		p.operator4 = '!=';
		p.value4 = 'to fail';
		
		p.setFilter();
		
		p.field = 'Name';
		p.operator = '%val%';
		p.value = 'Test';
		
		p.field1 = 'Name';
		p.operator1 = 'val%';
		p.value1 = 'Test';
		
		p.field2 = 'Name';
		p.operator2 = '%val';
		p.value2 = 'Test';
		
		p.field3 = 'Name';
		p.operator3 = '>';
		p.value3 = 'to fail';
		
		p.field4 = 'Amount';
		p.operator4 = '%val';
		p.value4 = 'to fail';
		
		p.filterLogic = 'to fail';
		
		p.setFilter();
    }

}