src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Micro_Industry__c</fullName>
        <label>Subsector</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Industry</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Centros Comerciales</fullName>
                </value>
                <value>
                    <fullName>Automotores y Camiones</fullName>
                </value>
                <value>
                    <fullName>Droguerías</fullName>
                </value>
                <value>
                    <fullName>Tienda Departamental</fullName>
                </value>
                <value>
                    <fullName>Otros Comercios</fullName>
                </value>
                <value>
                    <fullName>Supermercados</fullName>
                </value>
                <value>
                    <fullName>Alimentos y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Combustibles y Lubricantes</fullName>
                </value>
                <value>
                    <fullName>Call Centers</fullName>
                </value>
                <value>
                    <fullName>Grupo Telefonica</fullName>
                </value>
                <value>
                    <fullName>Hardware Tecnológico</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Contenido Multimedia</fullName>
                </value>
                <value>
                    <fullName>Telcos e Internet</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Instituciones financieras no bancarias</fullName>
                </value>
                <value>
                    <fullName>Medios de Pago</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Agro, Pesca y Forestación</fullName>
                </value>
                <value>
                    <fullName>Construccion</fullName>
                </value>
                <value>
                    <fullName>Industria Alimentos</fullName>
                </value>
                <value>
                    <fullName>Industria Automotriz y Autopartes</fullName>
                </value>
                <value>
                    <fullName>Industria Ligera y Manufacturas</fullName>
                </value>
                <value>
                    <fullName>Industria Metalurgica y Pesada</fullName>
                </value>
                <value>
                    <fullName>Industria Química</fullName>
                </value>
                <value>
                    <fullName>Industria Textil y Calzado</fullName>
                </value>
                <value>
                    <fullName>Laboratorios</fullName>
                </value>
                <value>
                    <fullName>Mineria</fullName>
                </value>
                <value>
                    <fullName>Petroleo y Gas</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Ámbito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Privado</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Público</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/SB_Cuenta_Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>SB - Cuenta - Soluciones</relationshipLabel>
        <relationshipName>SB_Cuenta_Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Solucion__c</fullName>
        <label>Super Ball - Solucion</label>
        <referenceTo>Super_Ball_Solucion__c</referenceTo>
        <relationshipLabel>SB - Cuenta - Soluciones</relationshipLabel>
        <relationshipName>SB_Cuenta_Soluciones</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SB - Cuenta - Solucion</label>
    <nameField>
        <label>Nombre de SB - Cuenta - Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SB - Cuenta - Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Arbol__c.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
                <value>
                    <fullName>Gobierno Provincial</fullName>
                </value>
                <value>
                    <fullName>Agricultura y pesca</fullName>
                </value>
                <value>
                    <fullName>Alimentación y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Automoción</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Construcción e inmobiliaria</fullName>
                </value>
                <value>
                    <fullName>Defensa</fullName>
                </value>
                <value>
                    <fullName>Educación</fullName>
                </value>
                <value>
                    <fullName>Farma</fullName>
                </value>
                <value>
                    <fullName>Gobierno Central</fullName>
                </value>
                <value>
                    <fullName>Gobierno Local</fullName>
                </value>
                <value>
                    <fullName>Industria</fullName>
                </value>
                <value>
                    <fullName>Justicia</fullName>
                </value>
                <value>
                    <fullName>Minería y Recursos Naturales</fullName>
                </value>
                <value>
                    <fullName>Ocio y Turismo</fullName>
                </value>
                <value>
                    <fullName>Petróleo y gas</fullName>
                </value>
                <value>
                    <fullName>Químicos</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Salud</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Servicios Profesionales</fullName>
                </value>
                <value>
                    <fullName>Tecnología y Electrónica</fullName>
                </value>
                <value>
                    <fullName>Telecom y Media</fullName>
                </value>
                <value>
                    <fullName>Transporte y Logística</fullName>
                </value>
                <value>
                    <fullName>Utilities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Super Ball - Arbol</label>
    <nameField>
        <label>Nombre de Super Ball - Arbol</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Arboles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Super_Ball_Interlocutor__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Interlocutores</relationshipLabel>
        <relationshipName>Super_Ball_Interlocutores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Interlocutor</label>
    <nameField>
        <label>Nombre de Super Ball - Interlocutor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Interlocutores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Nodo__c.object
<CustomObject>
    <fields>
        <fullName>Nodo_Padre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nodo Padre</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Arbol__c</fullName>
        <label>Super Ball - Arbol</label>
        <referenceTo>Super_Ball_Arbol__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Nodo</label>
    <nameField>
        <label>Nombre de Super Ball - Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Nodos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Pregunta__c.object
<CustomObject>
    <fields>
        <fullName>Dependencia_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependencia No</label>
        <referenceTo>Super_Ball_Pregunta__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas (Dependencia No)</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dependencia_Si__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependencia Si</label>
        <referenceTo>Super_Ball_Pregunta__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>esHija__c</fullName>
        <defaultValue>false</defaultValue>
        <label>esHija</label>
        <type>Checkbox</type>
    </fields>
    <label>Super Ball - Pregunta</label>
    <nameField>
        <label>Nombre de Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Preguntas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Recurso__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Recursos</relationshipLabel>
        <relationshipName>Super_Ball_Recursos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Recurso</label>
    <nameField>
        <label>Nombre de Super Ball - Nodo Padre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Recursos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Soluciones</relationshipLabel>
        <relationshipName>Super_Ball_Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Solucion</label>
    <nameField>
        <label>Nombre de Super Ball - Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/graficoSBControllerTest.cls
@isTest
public class graficoSBControllerTest {

    static testMethod void graficosSBController(){
        
        Account cuenta = new Account(name = 'nombre cuenta');
        cuenta.Micro_Industry__c = 'Financiero';
        insert cuenta;
        
        Super_Ball_Arbol__c arbol = new Super_Ball_Arbol__c(name='arbol');
        arbol.Sector__c = 'Financiero';
        insert arbol;
        
        Super_Ball_Nodo__c nodo = new Super_Ball_Nodo__c(name='nodoPadre');
        nodo.Super_Ball_Arbol__c = arbol.id;
        insert nodo;
        
        Super_Ball_Nodo__c nodoHijo = new Super_Ball_Nodo__c(name='nodoHijo');
        nodoHijo.Super_Ball_Arbol__c = arbol.id;
        nodoHijo.Nodo_Padre__c = nodo.id;
        insert nodoHijo;
        
        Super_Ball_Pregunta__c preguntaSi = new Super_Ball_Pregunta__c(name='a');
        preguntaSi.Super_Ball_Nodo__c = nodoHijo.id;
        preguntaSi.esHija__c = true;
        insert preguntaSi;
        
        Super_Ball_Pregunta__c preguntaNo = new Super_Ball_Pregunta__c(name='a');
        preguntaNo.Super_Ball_Nodo__c = nodoHijo.id;
        preguntaNo.esHija__c = true;        
        insert preguntaNo;
        
        Super_Ball_Pregunta__c pregunta = new Super_Ball_Pregunta__c(name='a');
        pregunta.Super_Ball_Nodo__c = nodoHijo.id;
        pregunta.Dependencia_Si__c = preguntaSi.id;
        pregunta.Dependencia_No__c = preguntaNo.id;
        pregunta.esHija__c = false;
        insert pregunta;
        
        Super_Ball_Recurso__c recurso = new Super_Ball_Recurso__c(name = 'a');
        recurso.Super_Ball_Nodo__c = nodoHijo.id;
        insert recurso;
        
        Super_Ball_Solucion__c solucion = new Super_Ball_Solucion__c(name='a');
        solucion.Super_Ball_Nodo__c = nodoHijo.id;
        insert solucion;
        
        SB_Cuenta_Solucion__c solucionCuenta = new SB_Cuenta_Solucion__c(name='a');
        solucionCuenta.Super_Ball_Nodo__c = nodoHijo.id;
        solucionCuenta.Super_Ball_Solucion__c = solucion.id;
        insert solucionCuenta;
        
        Super_Ball_Interlocutor__c interlocutor = new Super_Ball_Interlocutor__c(name ='a');
        interlocutor.Super_Ball_Nodo__c = nodoHijo.id;
        insert interlocutor;
        
        Test.setCurrentPageReference(new PageReference('Page.PruebaVis'));
        System.currentPageReference().getParameters().put('IdNodo', nodo.id);
        System.currentPageReference().getParameters().put('Id', cuenta.id);
        
        GraficoSBController controller = new graficoSBController();
        controller.volverDePantallaCompleta();
        controller.pantallaCompleta();
        controller.irACuestionario();
    }
}