src/objects/Account_Competitor__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Competitors</relationshipLabel>
        <relationshipName>Account_Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Competitor</label>
    <nameField>
        <label>Nombre de nuestro Competidor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Competitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account_Review__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Review</label>
        <referenceTo>Account_Review__c</referenceTo>
        <relationshipLabel>Accounts Data</relationshipLabel>
        <relationshipName>Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Data</relationshipLabel>
        <relationshipName>Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitors_Last_Update__c</fullName>
        <label>Competitors Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Competitors_Number__c</fullName>
        <label>Competitors Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunities_With_RDM__c</fullName>
        <label>Opportunities With RDM</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunities_With_VD__c</fullName>
        <label>Opportunities_With_VD</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PNB_Amount__c</fullName>
        <label>PNB Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Past_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SCP Past Activity</label>
        <referenceTo>PastActivity__c</referenceTo>
        <relationshipLabel>Accounts Data</relationshipLabel>
        <relationshipName>Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative_Last_Update__c</fullName>
        <label>Strategic Initiative Last Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative_Number__c</fullName>
        <label>Strategic Initiative Number</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Account Data</label>
    <nameField>
        <label>Nombre de Account Data</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Review__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Reviews</relationshipLabel>
        <relationshipName>Accounts_Reviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Review</label>
    <nameField>
        <label>Nombre de Account Review</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Contacts_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts Assessments</relationshipLabel>
        <relationshipName>Contacts_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts Assessments</relationshipLabel>
        <relationshipName>ContactsAssessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Assessment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_FCV__c</fullName>
        <description>Estimated by the account manager in early stages of the opportunity (m€)</description>
        <inlineHelpText>The account manager indicates an estimation of the total value of the project.
Posible Values: Free field in €
Filled in by: The account manager.</inlineHelpText>
        <label>Campo Inactivo</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/OpportunityStrategicInitiative__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <referenceTo>Strategic_Initiative__c</referenceTo>
        <relationshipLabel>Opportunities &amp; Strategic Initiatives</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity - Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Opportunity - Strategic Initiative</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities &amp; Strategic Initiatives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PastActivity__c.object
<CustomObject>
    <description>Object that contains past activity with client</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Past_Activitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SCP Past Activity</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Past Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Potential_New_Business__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GAP_Potential_New_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_FCV__c</fullName>
        <label>Estimated FCV</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Potential_new_Business__c</fullName>
        <label>Descripción</label>
        <type>TextArea</type>
    </fields>
    <label>SCP Potential New Business</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>GAP Potential New Business Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Potential New Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Strategic Initiatives</relationshipLabel>
        <relationshipName>StrategicInitiatives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_InfoSCPForAccountBatch.cls
@isTest
private class Test_InfoSCPForAccountBatch {
	
    /*
	@isTest static void test_accountWithoutData() {
		
		Account acct = new Account(Name = 'Test');
		insert acct;
		system.assertEquals(1, [select id from Account].size());

		system.assertEquals(0, [select id from Account_Data__c].size());

		Test.startTest();
		Database.executeBatch(new InfoSCPForAccountBatch());
		Test.stopTest();

		List<Account_Data__c> resultAccountData = [select id, account__c, competitors_Number__c, past_Activity__c, pnb_Amount__c, strategic_Initiative_Number__c, opportunities_With_RDM__c, opportunities_With_VD__c, account_Review__c
													from Account_Data__c];
		system.assertEquals(1, resultAccountData.size());

		Account_Data__c accountData = resultAccountData.get(0);

		system.assertEquals(acct.id,accountData.account__c);
		system.assertEquals(0,accountData.competitors_Number__c);
		system.assertEquals(null,accountData.past_Activity__c); 
		system.assertEquals(0,accountData.pnb_Amount__c);
		system.assertEquals(0,accountData.strategic_Initiative_Number__c);
		system.assertEquals(0,accountData.opportunities_With_RDM__c);
		system.assertEquals(0,accountData.opportunities_With_VD__c);
		system.assertEquals(null,accountData.Account_Review__c);

	}
	
	@isTest static void test_accountWithAllData() {

		Account acct = new Account(Name = 'Test');
		insert acct;
		system.assertEquals(1, [select id from Account].size());

		Opportunity opp = new Opportunity(Name = 'Test', accountId = acct.id, CloseDate = System.today(), StageName = 'Open');
		insert opp;
		system.assertEquals(1, [select id from Opportunity].size());

		Account_Competitor__c competitor = new Account_Competitor__c(Account__c = acct.id);
		insert competitor;
		system.assertEquals(1, [select id from Account_Competitor__c].size());

		PastActivity__c pastActivity = new PastActivity__c(Account__c = acct.id); 
		insert pastActivity;
		system.assertEquals(1, [select id from PastActivity__c].size());

		Potential_New_Business__c pnb = new Potential_New_Business__c(Account__c = acct.id, Estimated_FCV__c = 100);
		insert pnb;
		system.assertEquals(1, [select id from Potential_New_Business__c].size());

		Strategic_Initiative__c strategic = new Strategic_Initiative__c(Account__c = acct.id);
		insert strategic;
		system.assertEquals(1, [select id from Strategic_Initiative__c].size());

		Contact contact = new Contact(LastName = 'Test', FirstName = 'Contact', AccountId = acct.id);
		insert contact;
		system.assertEquals(1, [select id from Contact].size());
		
		Contact_Assessment__c contactAssessment = new Contact_Assessment__c(Contact__c = contact.id, Opportunity__c = opp.id);
		insert contactAssessment;
		system.assertEquals(1, [select id from Contact_Assessment__c].size());

		OpportunityStrategicInitiative__c oppStrategic = new OpportunityStrategicInitiative__c(Strategic_Initiative__c = strategic.id,Opportunity__c = opp.id);
		insert oppStrategic;
		system.assertEquals(1, [select id from OpportunityStrategicInitiative__c].size());

		Account_Review__c accountReview = new Account_Review__c(Account__c = acct.id);
		insert accountReview;
		system.assertEquals(1, [select id from Account_Review__c].size());		


		system.assertEquals(0, [select id from Account_Data__c].size());

		Test.startTest();
		Database.executeBatch(new InfoSCPForAccountBatch());
		Test.stopTest();

		List<Account_Data__c> resultAccountData = [select id, account__c, competitors_Last_update__c, strategic_Initiative_Last_Update__c, competitors_Number__c, past_Activity__c, pnb_Amount__c, strategic_Initiative_Number__c, opportunities_With_RDM__c, opportunities_With_VD__c, account_Review__c
													from Account_Data__c];
		system.assertEquals(1, resultAccountData.size());

		Account_Data__c accountData = resultAccountData.get(0);

		system.assertEquals(acct.id,accountData.account__c);
		system.assertEquals(1,accountData.competitors_Number__c);
		system.assertEquals(pastActivity.id,accountData.past_Activity__c); 
		system.assertEquals(100,accountData.pnb_Amount__c);
		system.assertEquals(1,accountData.strategic_Initiative_Number__c);
		//system.assertEquals(1,accountData.opportunities_With_RDM__c);
		system.assertEquals(1,accountData.opportunities_With_VD__c);
		DateTime silu = accountData.strategic_Initiative_Last_Update__c;		
		system.assertEquals(system.today(),date.newinstance(silu.year(),silu.month(),silu.day()));
		DateTime clu = accountData.competitors_Last_update__c;		
		system.assertEquals(system.today(),date.newinstance(clu.year(),clu.month(),clu.day()));
		system.assertEquals(accountReview.id,accountData.account_Review__c);		
	}


	@isTest static void test_manyData() {

		Integer maxData = 199;

		List<Account> accounts = new List<Account>();
		for (Integer i=0;i<maxData;i++) {
			accounts.add(new Account(Name = 'Test' + i));
		}
		insert accounts;

		List<Opportunity> opps = new List<Opportunity>();
		for (Integer i=0;i<maxData;i++) {
			opps.add(new Opportunity(Name = 'Test' + i, accountId = accounts[i].id, CloseDate = System.today(), StageName = 'Open'));
		}

		Test.startTest();
		Database.executeBatch(new InfoSCPForAccountBatch());
		Test.stopTest();

		system.assertEquals(maxData, [select id from Account_Data__c].size());
	}	

    	@isTest static void test_manyDataBatchAccountBatch() {

		Integer maxData = 199;

		List<Account> accounts = new List<Account>();
		for (Integer i=0;i<maxData;i++) {
			accounts.add(new Account(Name = 'Test' + i));
		}
		insert accounts;

		List<Opportunity> opps = new List<Opportunity>();
		for (Integer i=0;i<maxData;i++) {
			opps.add(new Opportunity(Name = 'Test' + i, accountId = accounts[i].id, CloseDate = System.today(), StageName = 'Open'));
		}

		Test.startTest();
		Database.executeBatch(new InfoSCPForAccountBatch());
		Test.stopTest();

		system.assertEquals(maxData, [select id from Account_Data__c].size());
	}	*/
}