src/objects/Area_cadena_de_valor__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conocimiento__c</fullName>
        <label>Conocimiento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alto</fullName>
                </value>
                <value>
                    <fullName>Medio</fullName>
                </value>
                <value>
                    <fullName>Bajo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contacto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contacto</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Areas cadena de valor</relationshipLabel>
        <relationshipName>Areas_cadena_de_valor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interes__c</fullName>
        <label>Interes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reto__c</fullName>
        <label>Reto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solucion__c</fullName>
        <label>Solucion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cuenta__c</fullName>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Areas cadena de valor</relationshipLabel>
        <relationshipName>Areas_cadena_de_valor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Area cadena de valor</label>
    <nameField>
        <label>Nombre de cadenaDeValor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Areas cadena de valor</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Reto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning Reto</label>
        <referenceTo>FourPlanning_Reto__c</referenceTo>
        <relationshipLabel>Soluciones</relationshipLabel>
        <relationshipName>Soluciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solucion</label>
    <nameField>
        <label>Nombre de Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CadenaDeValorController.cls
public class CadenaDeValorController {
	
    public String idCuenta {get; set;}
    public List<Area_cadena_de_valor__c>  areasDeCadenaDeValor {get;set;}
    
    public Area_cadena_de_valor__c nuevaArea {get;set;}
    public String areaABorarId {get; set;}
    
    public CadenaDeValorController(ApexPages.StandardController controller){
        
        nuevaArea = new Area_cadena_de_valor__c();
        
        idCuenta = ApexPages.currentPage().getParameters().get('Id');
        
        conseguirAreas();

        if(areasDeCadenaDeValor.size() == 0){
            areasDeCadenaDeValor = new List<Area_cadena_de_valor__c>();
        }
        
    }
    
    public void conseguirAreas(){
        areasDeCadenaDeValor = [select id, Area__c, Contacto__c, Reto__c, Solucion__c, Interes__c, Conocimiento__c 
                                from Area_cadena_de_valor__c 
                                where cuenta__c =: idCuenta ];
    }
    
    public pageReference saveChanges(){
        
        update areasDeCadenaDeValor;
        return null;
    }
    
    public void setear4ValoresPorDefaultSiNoExisteNinguno(){
        
        List<Area_cadena_de_valor__c> areasAInsertar = new List<Area_cadena_de_valor__c>();
        
        if(areasDeCadenaDeValor.size() == 0){
            Area_cadena_de_valor__c unArea = new Area_cadena_de_valor__c();
            unArea.Area__c = 'Finance';
            unArea.cuenta__c = idCuenta;
            areasAInsertar.add(unArea);
            
            unArea = new Area_cadena_de_valor__c();
            unArea.Area__c = 'Sales';
            unArea.cuenta__c = idCuenta;
            areasAInsertar.add(unArea);
            
            unArea = new Area_cadena_de_valor__c();
            unArea.Area__c = 'Marketing';
            unArea.cuenta__c = idCuenta;
            areasAInsertar.add(unArea);
            
            
            unArea = new Area_cadena_de_valor__c();
            unArea.Area__c = 'Operations';
            unArea.cuenta__c = idCuenta;
            areasAInsertar.add(unArea);
        }
        
        insert areasAInsertar;
        conseguirAreas();
    }
    
    public PageReference nuevaArea(){
        
        nuevaArea.cuenta__c = idCuenta;
		
        if(nuevaArea.Area__c != null){
            insert nuevaArea;
            nuevaArea = new Area_cadena_de_valor__c();
            conseguirAreas();
        }
            
        return null;
    }
    
    public PageReference borrarArea(){
        
        Integer i = 0;
        
        for(Area_cadena_de_valor__c area : areasDeCadenaDeValor){
            
            if(area.id == areaABorarId){
                break;
            }
            else{
                i++;
            }   
        }
        
        if(areasDeCadenaDeValor[i].id != null){
            
            delete areasDeCadenaDeValor[i];    
        }
        
        
        areasDeCadenaDeValor.remove(i);

        return null;
    }
}