src/objects/businesslandscape__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>business Landscapes</relationshipLabel>
        <relationshipName>business_Landscapes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AnnualSpend__c</fullName>
        <label>Gastos Anuales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category_Service__c</fullName>
        <label>Categoria de los servicios</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IoT</fullName>
                </value>
                <value>
                    <fullName>Seguridad</fullName>
                </value>
                <value>
                    <fullName>Comunicaciones unificadas y servicios de colaboración</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Otros servicios</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compra_a_nivel__c</fullName>
        <label>Compra a nivel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContractEndDate__c</fullName>
        <label>Fecha de fin de contrato</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Pais</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CurrentProvider__c</fullName>
        <label>Proveedor Actual</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decision_maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Decision maker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>business Landscapes</relationshipLabel>
        <relationshipName>business_Landscapes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Nivel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NumberOfChannels__c</fullName>
        <label>Numero de Canales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OtherInformation__c</fullName>
        <label>Otra Información</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Servicios</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Service__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Gestión de Servicios Móviles</fullName>
                </value>
                <value>
                    <fullName>Unificación de Comunicaciones y Servicios de Colaboración</fullName>
                </value>
                <value>
                    <fullName>Almacenamiento</fullName>
                </value>
                <value>
                    <fullName>laaS &amp; PaaS</fullName>
                </value>
                <value>
                    <fullName>Gestión de Servicios Cloud</fullName>
                </value>
                <value>
                    <fullName>SaaS</fullName>
                </value>
                <value>
                    <fullName>Enterprise Mobile IT</fullName>
                </value>
                <value>
                    <fullName>Seguridad cibernética</fullName>
                </value>
                <value>
                    <fullName>Seguridad Mgmt</fullName>
                </value>
                <value>
                    <fullName>Seguridad en Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Seguridad Cloud</fullName>
                </value>
                <value>
                    <fullName>Identidad &amp; Privacidad</fullName>
                </value>
                <value>
                    <fullName>Conectividad IoT</fullName>
                </value>
                <value>
                    <fullName>Smart Mobility</fullName>
                </value>
                <value>
                    <fullName>Smart Cities</fullName>
                </value>
                <value>
                    <fullName>Smart Retail</fullName>
                </value>
                <value>
                    <fullName>Nuevo Negocio IoT</fullName>
                </value>
                <value>
                    <fullName>Smart Steps</fullName>
                </value>
                <value>
                    <fullName>Smart Digits</fullName>
                </value>
                <value>
                    <fullName>Servicios de Red</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_Service__c</fullName>
        <label>No se utiliza</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>M2M</fullName>
                </value>
                <value>
                    <fullName>Soluciones de conectividad</fullName>
                </value>
                <value>
                    <fullName>Gestión de servicios</fullName>
                </value>
                <value>
                    <fullName>Servicios WAN</fullName>
                </value>
                <value>
                    <fullName>Servicio de Internet</fullName>
                </value>
                <value>
                    <fullName>Soluciones de Productividad</fullName>
                </value>
                <value>
                    <fullName>Consultas y soluciones de integración</fullName>
                </value>
                <value>
                    <fullName>Servicios unificados de comunicación</fullName>
                </value>
                <value>
                    <fullName>Servicios de conferencias</fullName>
                </value>
                <value>
                    <fullName>Seguridad</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>business Landscape</label>
    <nameField>
        <label>Nombre de business Landscape</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>business Landscapes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountBusinessLandscapeController.cls
public with sharing class AccountBusinessLandscapeController {

    public Account account {get;set;}
    public Boolean canEdit {get;set;}
    public List<BusinessLandscape__c> businessLandscapeList {get;set;}
    public Id toDel {get;set;}
    public List<BusinessLandscapeWrapper> businessLandscapeWrapperList {get;set;}
    public BusinessLandscape__c newBusinesLandscape {get;set;}
    
    public AccountBusinessLandscapeController() {        
        account = [SELECT id, Name FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];    
        canEdit = true;        
        init();        
    }
    
    private void init() {
         businessLandscapeList = [select id, level__c, CurrentProvider__c, Sub_Category_Service__c, AnnualSpend__c, Country__c, ContractEndDate__c, NumberOfChannels__c, 
                                 OtherInformation__c, service__c, Category_Service__c, Decision_maker__c, Compra_a_nivel__c 
                                 from BusinessLandscape__c 
                                 where account__c = :account.id 
                                 order by createdDate];
         
        
                
        
        newBusinesLandscape = new BusinessLandscape__c(Account__c = account.id);

        Map<String, BusinessLandscapeWrapper> CategoryMap = new Map<String, BusinessLandscapeWrapper>();
        businessLandscapeWrapperList = new List<BusinessLandscapeWrapper>(); 
        
        for (BusinessLandscape__c bl :businessLandscapeList) {
            
            if (CategoryMap.get(bl.Category_Service__c) == null) {
                BusinessLandscapeWrapper nuevoCategoriaDeServicio = new BusinessLandscapeWrapper(bl);
                
                //Creo el wrapper para el servicio.
                ServiciosWrapper servicioWpp = new ServiciosWrapper(bl);
                nuevoCategoriaDeServicio.servicios.add(servicioWpp);
                
                //Pongo el wrapper de categoria de servicio en el mapa.
                CategoryMap.put(bl.Category_Service__c, nuevoCategoriaDeServicio);
                
                //Pongo el wpp contenedor de la categoria en la lista para mostrarlo.
                businessLandscapeWrapperList.add(nuevoCategoriaDeServicio);
                
            } else { 
                
                //Obtengo el wpp de la categoria.
                BusinessLandscapeWrapper CategoriaDeServicioConocida = 	CategoryMap.get(bl.Category_Service__c);
                
                //Creo el wrapper para el servicio.
                ServiciosWrapper servicioWpp = new ServiciosWrapper(bl);
                
                //Se lo agrego a la categoria que corresponda.
                CategoriaDeServicioConocida.servicios.add(servicioWpp);
            }
        }
        
    }
    
    public PageReference save() {
        upsert businessLandscapeList;
        init();
        return null;
    }
    
    public PageReference add() {
        insert newBusinesLandscape;
        init();
        return null;
    }
    
    public PageReference del() {        
        if (toDel != null) {
            delete [select id from BusinessLandscape__c where id = :toDel];
            init();
        }       
        return null;
    }
    
    public PageReference ExportToExcel() { 
        save();
        return Page.accountBusinessLandscapeExcel;
    }
    
    public PageReference siNoHayCreadoUnRegistroEnParqueDeServiciosGeneroUnoDeCadaUno(){
        
        if(businessLandscapeList.size() == 0){
            system.debug('siNoHayCreadoUnRegistroEnParqueDeServiciosGeneroUnoDeCadaUno');
        	crearUnRegistroPorCategoria();
            init();
        }
        return null;
    }
    
    public void crearUnRegistroPorCategoria(){
        
        system.debug('crearUnRegistroPorCategoria');
        
        List<String> categorias = new List<String>();
        categorias.add('IoT');
        categorias.add('Seguridad');
        categorias.add('Comunicaciones unificadas y servicios de colaboración');
        categorias.add('Cloud');
        categorias.add('Big Data');
        
        //cargo el mapa de subCategorias por cada categoria.
        Map<String, List<String>> subCategoriaDeCadaCategoria = new Map<String, List<String>>();
        
        //cargo de cada categoria su lista de subcategorias.
        List<String> categoriaIoT = new List<String>{'Conectividad IoT','Smart Mobility','Smart Cities','Smart Retail','Nuevo Negocio IoT'};
        List<String> categoriaSeguridad = new List<String>{'Almacenamiento','Seguridad Mgmt','Seguridad en Comunicaciones','Seguridad Cloud','Identidad & Privacidad'};
        List<String> categoriaComunicacion = new List<String>{'Gestión de Servicios Móviles','Unificación de Comunicaciones y Servicios de Colaboración','Servicios de Red'};
        List<String> categoriaCloud = new List<String>{'Almacenamiento','laaS & PaaS','Gestión de Servicios Cloud','SaaS','Enterprise Mobile IT'};
        List<String> categoriaBigData = new List<String>{'Smart Steps','Smart Digits'};
        
        subCategoriaDeCadaCategoria.put('IoT',categoriaIoT);
        subCategoriaDeCadaCategoria.put('Seguridad',categoriaSeguridad);
        subCategoriaDeCadaCategoria.put('Comunicaciones unificadas y servicios de colaboración',categoriaComunicacion);
        subCategoriaDeCadaCategoria.put('Cloud',categoriaCloud);
        subCategoriaDeCadaCategoria.put('Big Data',categoriaBigData);
            
        List<BusinessLandscape__c> servicios = new List<BusinessLandscape__c>();
        
        BusinessLandscape__c servicio = new BusinessLandscape__c();
        for(String categoria: categorias){
            for(String subCategoria: subCategoriaDeCadaCategoria.get(categoria)){
                servicio = new BusinessLandscape__c();
                servicio.Category_Service__c = categoria;
                servicio.Service__c = subCategoria;
                servicio.Account__c = account.id;
                servicios.add(servicio);
            }
        }
		
        system.debug(servicios);
        insert servicios;
        
    }
    
    public String getExcelName() {
        String name = account.Name + '-' + Label.Account_Business_Landscape +'.xls';
        return name.replaceAll(' ', '_');
    }    

    class BusinessLandscapeWrapper {
        
        public BusinessLandscape__c bl {get;set;}
        public List<serviciosWrapper> servicios {get;set;}        
        
        public BusinessLandscapeWrapper(BusinessLandscape__c n) {
            bl = n;
            servicios = new List<serviciosWrapper>();
        }
    }
    
    class serviciosWrapper {
        
        public BusinessLandscape__c servicio {get; set;}
        
        public serviciosWrapper(BusinessLandscape__c unServicio){
            servicio = unServicio;
        }
    }
}