src/objects/Catalogo__c.object
<CustomObject>
    <label>Catalogo</label>
    <nameField>
        <label>Nombre de Catalogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Linea_de_Servicio__c.object
<CustomObject>
    <fields>
        <fullName>Catalogo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Catalogo</label>
        <referenceTo>Catalogo__c</referenceTo>
        <relationshipLabel>Lineas de Servicio</relationshipLabel>
        <relationshipName>Lineas_de_Servicio</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Linea de Servicio</label>
    <nameField>
        <label>Nombre de Linea de Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lineas de Servicio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Linea_de_Servicio__c</fullName>
        <label>Linea de Servicio</label>
        <referenceTo>Linea_de_Servicio__c</referenceTo>
        <relationshipLabel>Soluciones</relationshipLabel>
        <relationshipName>Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Solucion</label>
    <nameField>
        <label>Nombre de Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SolucionEnCuenta__c.object
<CustomObject>
    <fields>
        <fullName>TipoSolucion__c</fullName>
        <label>TipoSolucion</label>
        <referenceTo>Solucion__c</referenceTo>
        <relationshipLabel>SolucionesEnCuenta</relationshipLabel>
        <relationshipName>SolucionesEnCuenta</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SolucionEnCuenta</label>
    <nameField>
        <label>Nombre de SolucionEnCuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SolucionesEnCuenta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdministrarSolucionesController.cls
public class AdministrarSolucionesController {
    
    
    public List<Linea_de_Servicio__c> lineasDeServicios {get; set;}
    
    public List<SolucionEnCuenta__c> soluciones {get; set;}
    
    public Linea_de_Servicio__c lineaDeServicioAInsertar {get; set;}
    
    public Id lineaABorrarId {get; set;}
    
    public Id solucionABorrarId {get; set;}
    
    public Id lineaPadreDeLaSolucionAInsertar {get; set;}
    
    public Solucion__c solucionAInsertar {get;set;}
    public String idCatalogo {get;set;}
    
    
    public AdministrarSolucionesController(){
        
        idCatalogo = ApexPages.currentPage().getParameters().get('Id');
        
        lineasDeServicios = new List<Linea_de_Servicio__c>();
        
        obtenerLineasDeServicio();
        
    }
    
    public void guardar(){
        system.debug('guardar');
        
        if(lineasDeServicios.size()>0){
            update lineasDeServicios;
        }
    }
    
    public void obtenerLineasDeServicio (){
        
        lineaDeServicioAInsertar = new Linea_de_Servicio__c();
        
        solucionAInsertar = new Solucion__c();
        
        
        lineasDeServicios = [select id, name,
                             (select id, name from Soluciones__r)
                             from Linea_de_Servicio__c
                             where catalogo__c =: idCatalogo
                             ORDER BY createdDate DESC LIMIT 900];
        
        
        
    }
    
    
    public void InsertarLineaDeServicio(){
        
        lineaDeServicioAInsertar.catalogo__c = idCatalogo;
        insert lineaDeServicioAInsertar;
        
        
        obtenerLineasDeServicio();
    }
    
    
    public void InsertarSolucion(){
        
        
        solucionAInsertar.Linea_de_Servicio__c = lineaPadreDeLaSolucionAInsertar;
        
        
        insert solucionAInsertar;
        
        
        obtenerLineasDeServicio();
    }
    
    
    public PageReference borrarLineaDeServicio(){
        
        Integer i = 0;
        
        for(Linea_de_Servicio__c lineaDeServicio : lineasDeServicios){
            
            if(lineaDeServicio.id == lineaABorrarId){
                break;
            }
            else{
                i++;
            }   
        }
        
        if(lineasDeServicios[i].id != null){
            
            delete lineasDeServicios[i];
            
        }
        
        
        lineasDeServicios.remove(i);        
        obtenerLineasDeServicio();
        return null;
    }
    
    
    public PageReference borrarSolucion(){
        
        Solucion__c aBorrar = new Solucion__c();
        //soluciones = [select id, tipoSolucion__c from SolucionEnCuenta__c where tipoSolucion__c=:solucionABorrarId];
        aBorrar = [select id, name from Solucion__c
                   where id =: solucionABorrarId];
        
       // delete soluciones;
        
        delete aBorrar;
        
        
        obtenerLineasDeServicio();
        return null;
        
    }
    
    
}