src/objects/Contact_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Attitudes__c</fullName>
        <label>Attitudes</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Developer</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Burning Platform</fullName>
                </value>
                <value>
                    <fullName>Statu Quo</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Authority__c</fullName>
        <label>Authority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Cycle__c</fullName>
        <label>Buying Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Reconocimiento de Necesidades</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Evaluación de Alternativas</fullName>
                </value>
                <value>
                    <fullName>Reducción de Riesgos</fullName>
                </value>
                <value>
                    <fullName>Obtención de Resultados</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competing_Company_Relationship__c</fullName>
        <label>Competing Company Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Negative</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Positive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts Assessments</relationshipLabel>
        <relationshipName>Contacts_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Focus__c</fullName>
        <label>Focus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Controller</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>End User</fullName>
                </value>
                <value>
                    <fullName>Sponsor</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Influence__c</fullName>
        <label>Influence</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts Assessments</relationshipLabel>
        <relationshipName>ContactsAssessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Our_Relationship__c</fullName>
        <label>Our Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Contact Assessment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Influence__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Influenced__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Influenced</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Influences</relationshipLabel>
        <relationshipName>Contact_Influences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Influences__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Influences</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Influences (Contact Influence)</relationshipLabel>
        <relationshipName>Contact_Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Influence</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Contact Influence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Influences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Buying_Cycle__c</fullName>
        <label>Buying Cycle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awareness of Needs</fullName>
                </value>
                <value>
                    <fullName>Assessments of Alternatives</fullName>
                </value>
                <value>
                    <fullName>Alleviation of Risks</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
                <value>
                    <fullName>Achievements of Results</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/test_OpportunityEvaluations.cls
@isTest
private class test_OpportunityEvaluations {

    static testMethod void myUnitTest() {

    Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.industry = 'Banking';
        
        insert cuenta;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Open';
        opp.CloseDate = System.Today();
        opp.accountId = cuenta.id;
        insert opp;
        

        Contact contacto = new Contact();
        contacto.LastName = 'test';
        contacto.AccountId = cuenta.id;
        insert contacto;
        
        Contact contacto2 = new Contact();
        contacto2.LastName = 'test';
        contacto2.AccountId = cuenta.id;
        contacto2.ReportsToId = contacto.id;
        insert contacto2;
        
        Contact_Influence__c ci = new Contact_Influence__c();
        ci.Contact_Influenced__c = contacto.id;
        ci.Contact_Influences__c = contacto2.id;
        insert ci;
        
        
        Contact_Assessment__c ca = new Contact_Assessment__c();
        ca.Contact__c = contacto.id;
        ca.Opportunity__c = opp.id;
        insert ca;
        
        ca = new Contact_Assessment__c();
        ca.Contact__c = contacto2.id;
        ca.Opportunity__c = opp.id;
        ca.Focus__c = 'End User';
        ca.Influence__c = 'Negative';
        ca.Attitudes__c = 'Negative';
        ca.Authority__c = 'Positive';
        ca.Buying_Cycle__c = 'Assessments of Alternatives';
        ca.Our_Relationship__c = 'Positive';
        ca.Competing_Company_Relationship__c = 'Positive';
        insert ca;
        
        System.currentPagereference().getParameters().put('id',opp.id);

        
        OpportunityEvaluations p = new OpportunityEvaluations();
        
        p.getFooterStyle();
        p.getNotEvaluated();
        //p.getParentNotEvaluated();
        
        p.contactIdToEvaluate = contacto.id;
        p.popContactEvaluation();
        p.newEval.Contact__c = contacto.id;
        p.popContactEvaluationFromX();
        
        p.InsertEvaluation();
        p.SaveChanges();
        p.copyRDM();
        
        p.delid = ca.Id;
        p.DeleteEvaluation();
        
        //Test to UserAction Class
        userActions ua = new userActions();
        ua.checkWrite(cuenta);
        ua.checkWrite(cuenta.id);
        
        //Test to Util Class        
        Util.transforma_miles(-10.10);
        Util.getCurrencyConverted(10.2,'EUR','USD');
        Util.getUserIsoCode();
        Util.getCompanyIsoCode();
        Util.getUserHierarchy(UserInfo.getUserId());
        
    }
}