src/objects/Evento_BackShop__c.object
<CustomObject>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Evento BackShop</label>
    <nameField>
        <label>Nombre de BackShop</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eventos BackShop</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Area__c.object
<CustomObject>
    <fields>
        <fullName>Conocimiento_del_Area__c</fullName>
        <label>Conocimiento del Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alto</fullName>
                </value>
                <value>
                    <fullName>Medio</fullName>
                </value>
                <value>
                    <fullName>Bajo</fullName>
                </value>
                <value>
                    <fullName>Aún no tengo contacto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Titulo_Area__c</fullName>
        <label>Titulo Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FourPlanning Area</label>
    <nameField>
        <label>Nombre de FourPlanning Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_CoeCuenta__c.object
<CustomObject>
    <fields>
        <fullName>Creacion_del_valor__c</fullName>
        <label>Creacion del valor</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>FourPlanning CoeCuentas</relationshipLabel>
        <relationshipName>FourPlanning_CoeCuentas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valor_Coeficiente_De_Cuenta__c</fullName>
        <label>Valor Coeficiente de Cuenta</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FourPlanning CoeCuenta</label>
    <nameField>
        <label>Nombre de FourPlanning CoeCuenta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning CoeCuentas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Contacto__c.object
<CustomObject>
    <fields>
        <fullName>Nivel_de_Relaci_n__c</fullName>
        <label>Nivel de Relación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fluida y Constante</fullName>
                </value>
                <value>
                    <fullName>Ocasional pero Cordial</fullName>
                </value>
                <value>
                    <fullName>Intensa y Difícil</fullName>
                </value>
                <value>
                    <fullName>No lo conozco</fullName>
                </value>
                <value>
                    <fullName>Es “Anti-Telefonica”</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_Contacto__c</fullName>
        <label>Tipo de Contacto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Director de RRHH</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director de Compras</fullName>
                </value>
                <value>
                    <fullName>Director de Negocio</fullName>
                </value>
                <value>
                    <fullName>CISO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>CTO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FourPlanning Contacto</label>
    <nameField>
        <label>Nombre de FourPlanning Contacto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Contactos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FourPlanning_Hito__c.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vencimiento Contrato Activo con Telefónica</fullName>
                </value>
                <value>
                    <fullName>Vencimiento Contrato Activo con la Competencia</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP Comunicaciones</fullName>
                </value>
                <value>
                    <fullName>Publicación RFP TI</fullName>
                </value>
                <value>
                    <fullName>Evento para clientes de Telefonica</fullName>
                </value>
                <value>
                    <fullName>Evento Relevante de la industria</fullName>
                </value>
                <value>
                    <fullName>Previsión Cierre TOP 3 deals</fullName>
                </value>
                <value>
                    <fullName>Otro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripción</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <label>FourPlanning Hito</label>
    <nameField>
        <label>Nombre de FourPlanning Hitos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Hitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FourPlanning_Reto__c.object
<CustomObject>
    <fields>
        <fullName>Etapa_del_Reto__c</fullName>
        <label>Etapa del Reto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospección</fullName>
                </value>
                <value>
                    <fullName>Diseño</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Compras</fullName>
                </value>
                <value>
                    <fullName>Implementación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FourPlanning_Area__c</fullName>
        <label>FourPlanning Area</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>FourPlanning Retos</relationshipLabel>
        <relationshipName>FourPlanning_Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FourPlanning Reto</label>
    <nameField>
        <label>Nombre de FourPlanning Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FourPlanning_Reto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning Reto</label>
        <referenceTo>FourPlanning_Reto__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Strategic_Initiative__c.object
<CustomObject>
    <fields>
        <fullName>Strategic_Initiative__c</fullName>
        <label>Strategic Initiative</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Título</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Strategic Initiative</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Strategic Initiatives</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategic Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InformacionDeLaCuentaComponentTest.cls
@isTest
public class InformacionDeLaCuentaComponentTest {

    static testMethod void seGeneraElObjetoFourPlanningParaUnaCuentaCorrectamente(){

        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning; 
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.getRespuestas();
        
        Evento_BackShop__c evento = new Evento_BackShop__c();
        evento.name='evento1';
        insert evento;
        
        controller.idDelEvento = evento.id;
        
        controller.setearOportunidadesAContacto();
        
        controller.crearEventoInutil();
        controller.actualizarEventoInutil();
        controller.crearEventoUtil();
        controller.actualizarEventoUtil();
        
        controller.IdentificaNegocio();
        controller.NoIdentificaNegocio();
        
       // controller.pruebaCheckbox();
        controller.insertVencimiento();
        controller.getRamas();
        controller.getFamilias();
        controller.borrarSolucionEnCuenta();
       // controller.BorrarPresupuesto();
        controller.cambioTodosADonuts();
        controller.cambioTodosABarras();
        controller.cambioTotalesADonuts();
        controller.cambioTotalesABarras();
        //controller.insertarPresupuesto();
        //controller.vincularRetoASolucion();
        controller.insertarSolucion();
        controller.insertarReto();
        controller.insertarRetoCustom();
        controller.renderizarPagina();
        controller.pruebita();
        controller.irAPlanDeAccion();
        controller.irADesarrolloCuenta();
        controller.irAEjesDeTrabajo();
        controller.irAForYou();
        controller.irACuestionario();
        controller.irAInicio();
        controller.borrarContacto();
        controller.borrarSolucion();
        //controller.desvincularReto();
        //controller.desvincularOportunidad();
        controller.pedirApoyoAVentas();
        controller.cancelarApoyoAVentaEspecialista();
        //controller.crearPlanDeAccion();
        controller.goToOrg();
        controller.sumar(1,2);
        controller.sumar(null,2);
        controller.sumar(1,null);
        controller.sumar(null,null);
        
        
        FourPlanning_Area__c area1 = new FourPlanning_Area__c();
        area1.name = 'area1';
        insert area1;
        FourPlanningController.WrapperArea areawpp = new FourPlanningController.WrapperArea(area1);
        FourPlanningController.WrapperOportunidadGrafico asd = new FourPlanningController.WrapperOportunidadGrafico('a', null);
        FourPlanningController.WrapperOportunidadesVencimientos vencimien = new FourPlanningController.WrapperOportunidadesVencimientos();
        vencimien.claveOrdenar = 'ad';
        vencimien.mes = 'enero';
        vencimien.fcv = 2;
        
		FourPlanningController.wrapperPresupuesto wppPresupuesto = new FourPlanningController.wrapperPresupuesto('enero',1,2,3);				
        FourPlanningController.WrapperReto wppReto = new FourPlanningController.WrapperReto();       
        
        FourPlanning_Reto__c reto1  = new  FourPlanning_Reto__c();
        reto1.name = 'reto1';
        reto1.Nombre_del_Reto__c= 'dasdasd';
        reto1.Etapa_del_Reto__c = 'RFI';
        reto1.FourPlanning_Area__c = area1.id;
        insert reto1;
        
        FourPlanningController.WrapperReto wppReto2 = new FourPlanningController.WrapperReto(reto1);
        
        Opportunity opp = new Opportunity();
        opp.name = 'asd';
        opp.StageName = 'cerrada';
        opp.CloseDate = Date.today();

        FourPlanningController.WrapperOportunidadesAVincular wppasd = new FourPlanningController.WrapperOportunidadesAVincular(opp);
        
        system.assertEquals(cuenta.id, controller.fourPlanning.cuenta__c);
    }

    static testMethod void generarAreas(){
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.fourPlanning.Titulo_Area_1__c = 'titulo1';
        controller.fourPlanning.Titulo_Area_2__c = 'titulo2';
        controller.fourPlanning.Titulo_Area_3__c = 'titulo3';
        
        controller.insertar4Planning();
        controller.generarAreas();
        
        List<FourPlanning_Area__c> areas = [SELECT ID, Titulo_Area__c FROM FourPlanning_Area__c];
        system.assertEquals(3, areas.size());
        system.assertEquals('titulo1', areas[0].Titulo_Area__c);
        system.assertEquals('titulo2', areas[1].Titulo_Area__c);
        system.assertEquals('titulo3', areas[2].Titulo_Area__c);
        
        controller.guardoPro();
        controller.getRenderBanca();
        controller.getRenderMineria();
        
        FourPlanning_Area__c area1 = new FourPlanning_Area__c();
        area1.name = 'area1';
        insert area1;
        
        FourPlanning_Reto__c reto1  = new  FourPlanning_Reto__c();
        reto1.name = 'reto1';
        reto1.Nombre_del_Reto__c= 'dasdasd';
        reto1.Etapa_del_Reto__c = 'RFI';
        reto1.FourPlanning_Area__c = area1.id;
        insert reto1;
        
        FourPlanning_Reto__c reto2  = new  FourPlanning_Reto__c();
        reto2.Nombre_del_Reto__c = 'dasdas';
        reto2.name = 'reto2';
        reto2.Etapa_del_Reto__c ='RFI';
        reto2.FourPlanning_Area__c = area1.id;
        insert reto2;
         
        controller.retoABorrarId = reto1.id;
        
        List<FourPlanning_Reto__c> retossss = new  List<FourPlanning_Reto__c>();
        retossss.add(reto1);
        retossss.add(reto2);
        controller.retosTotales = retossss;
        
        controller.BorrarReto();

        
        List<FourPlanning_Reto__c> retos = [SELECT ID FROM FourPlanning_Reto__c];
        system.assertEquals(1, retos.size());
        
        retos = [SELECT ID FROM FourPlanning_Reto__c WHERE FourPlanning_Area__c =: areas[0].id];
        system.assertEquals(0, retos.size());
        
		system.assertEquals(0, controller.retosArea1.size());
        system.assertEquals(0, controller.retosArea2.size());
        system.assertEquals(0, controller.retosArea3.size());
        controller.guardarFourPlanning();
        
        controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        controller.generarAreas();
        
        system.assertEquals(0, controller.retosArea1.size());
    }

    static testMethod void puedoInsertarYBorrarUnHitoQueALaVezSeInsertaYBorraUnaTarea(){
        
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.hitoAInsertar.Fecha__c = Date.today();
        controller.hitoAInsertar.Categoria__c = 'Publicación RFP TI';
        controller.hitoAInsertar.Descripcion__c = 'unaDescripcion'; 
        
        controller.insertar4Planning();
        controller.insertHito();
        
        List<FourPlanning_Hito__c> hitosCreados = [SELECT ID FROM FourPlanning_Hito__c];
        List<Task> tareasCreadas = [SELECT ID, ActivityDate, Description, hitoAsociado__c FROM Task];
        
        system.assertEquals(1, hitosCreados.size());
        system.assertEquals(1, tareasCreadas.size());
        system.assertEquals(Date.today(), tareasCreadas[0].ActivityDate);
        system.assertEquals('unaDescripcion', tareasCreadas[0].Description);
        system.assertEquals(hitosCreados[0].id, tareasCreadas[0].hitoAsociado__c);
        
        controller.hitoABorrarId = hitosCreados[0].id;
        controller.BorrarHito();
        
        hitosCreados = [SELECT ID FROM FourPlanning_Hito__c];
        tareasCreadas = [SELECT ID, ActivityDate, Description, hitoAsociado__c FROM Task];
        
        system.assertEquals(0, hitosCreados.size());
        system.assertEquals(0, tareasCreadas.size());
        
    }
     
    static testMethod void puedoInsertarYBorrarUnaIniciativa(){
        
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.newInitiative.Strategic_Initiative__c = 'una descripcion';
        controller.newInitiative.Title__c = 'titulo';
        
        controller.InsertIniciative();
        
        List<Strategic_Initiative__c> iniciativasInsertadas = [SELECT ID FROM Strategic_Initiative__c];
        
        System.assertEquals(1, iniciativasInsertadas.size());
        
        controller.delid = iniciativasInsertadas[0].id;
        controller.DeleteStrategicInitiatives();
        
        iniciativasInsertadas = [SELECT ID FROM Strategic_Initiative__c];
        
        System.assertEquals(0, iniciativasInsertadas.size());        

    }
    
    static testMethod void ahoraPuedoGenerarHasta5Areas(){
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.fourPlanning.Titulo_Area_1__c = 'titulo1';
        controller.fourPlanning.Titulo_Area_2__c = 'titulo2';
        controller.fourPlanning.Titulo_Area_3__c = 'titulo3';
        controller.fourPlanning.Titulo_Area_4__c = 'titulo4';
        controller.fourPlanning.Titulo_Area_5__c = 'titulo5';
        
        controller.insertar4Planning();
        controller.generarAreas();
        controller.guardarFourPlanningCompleto();
        
        List<FourPlanning_Area__c> areas = [SELECT ID, Titulo_Area__c FROM FourPlanning_Area__c];
        system.assertEquals(5, areas.size());
        system.assertEquals('titulo1', areas[0].Titulo_Area__c);
        system.assertEquals('titulo2', areas[1].Titulo_Area__c);
        system.assertEquals('titulo3', areas[2].Titulo_Area__c);
        system.assertEquals('titulo4', areas[3].Titulo_Area__c);
        system.assertEquals('titulo5', areas[4].Titulo_Area__c);
        
        
        List<FourPlanning_Reto__c> retos = [SELECT ID FROM FourPlanning_Reto__c];
        system.assertEquals(0, retos.size());
        
        retos = [SELECT ID FROM FourPlanning_Reto__c WHERE FourPlanning_Area__c =: areas[0].id];
        system.assertEquals(0, retos.size());
        
        system.assertEquals(0, controller.retosArea1.size());
        system.assertEquals(0, controller.retosArea2.size());
        system.assertEquals(0, controller.retosArea3.size());
        system.assertEquals(0, controller.retosArea4.size());
        system.assertEquals(0, controller.retosArea5.size());
        controller.guardarFourPlanning();
        
        controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        controller.generarAreas();
        
        system.assertEquals(0, controller.retosArea1.size());
    }
    
    static testMethod void cuandoGuardoElCuestionarioSeGuardaUnObjetoCoeCuenta(){
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
		controller.idCuenta = cuenta.id;
        
        controller.fourPlanning.Canal_Comercializacion_cliente__c = 'On-Line';
        controller.fourPlanning.Canal_Comercializacion_que_mas_crece__c = 'On-Line';
        controller.fourPlanning.Area_que_fracasamos_en_el_pasado__c = 'Cualquier valor';
        controller.fourPlanning.Mejoraria_Relacion_Con_El_Cliente__c = 'Si';
        controller.fourPlanning.realcion_empresa_otros_clientes__c = 'Si';
        
        controller.guardarFourPlanningCompleto();
        
        List<FourPlanning_CoeCuenta__c> coeCuenta = [SELECT ID, Creacion_del_valor__c, Cuenta__c FROM FourPlanning_CoeCuenta__c];
        system.assertEquals(1, coeCuenta.size());
        system.assertEquals(Date.today(), coeCuenta[0].Creacion_del_valor__c);
        system.assertEquals(cuenta.id, coeCuenta[0].Cuenta__c);
        
        //si lo guardo con el mismo valor no se genera un nuevo coeCuenta.
        controller.guardarFourPlanningCompleto();
        coeCuenta = [SELECT ID, Creacion_del_valor__c, Cuenta__c FROM FourPlanning_CoeCuenta__c];
        system.assertEquals(1, coeCuenta.size());
    }
    
    static testMethod void siYaHayUnCoeCreadoParaEseTrimestreLoActualiza(){
        
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
		controller.idCuenta = cuenta.id;
        
        controller.fourPlanning.Canal_Comercializacion_cliente__c = 'On-Line';
        controller.fourPlanning.Canal_Comercializacion_que_mas_crece__c = 'On-Line';
        
        
        controller.guardarFourPlanningCompleto();
        
        List<FourPlanning_CoeCuenta__c> coeCuenta = [SELECT ID, Creacion_del_valor__c, Cuenta__c, lastModifiedDate, Valor_Coeficiente_De_Cuenta__c FROM FourPlanning_CoeCuenta__c];
        system.assertEquals(1, coeCuenta.size());
        system.assertEquals(Date.today(), coeCuenta[0].Creacion_del_valor__c);
        system.assertEquals(cuenta.id, coeCuenta[0].Cuenta__c);
        
        system.debug(coeCuenta[0].lastModifiedDate);
        Double primerValorCoeCuenta = coeCuenta[0].Valor_Coeficiente_De_Cuenta__c;
        
        //agrego mas respuestas para que el valor cambie.
        controller.fourPlanning.Area_que_fracasamos_en_el_pasado__c = 'Cualquier valor';
        controller.fourPlanning.Mejoraria_Relacion_Con_El_Cliente__c = 'Si';
        controller.fourPlanning.realcion_empresa_otros_clientes__c = 'Si';
        
        controller.guardarFourPlanningCompleto();
        
        coeCuenta = [SELECT ID, Creacion_del_valor__c, Cuenta__c, Valor_Coeficiente_De_Cuenta__c, lastModifiedDate FROM FourPlanning_CoeCuenta__c];
        system.debug(coeCuenta[0].lastModifiedDate);
        
        system.assertEquals(1, coeCuenta.size());
        system.assert((coeCuenta[0].Valor_Coeficiente_De_Cuenta__c != primerValorCoeCuenta));
    }
    
    static testMethod void cuandoGeneraElObjetoCoeCuentaYYaHay4CreadosSeBorraElMasViejo(){
        
        //se tienen que crear 1 por trimestre y si hay 4 que esos 4 sean de los 4 ultimos trimestres
      
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        FourPlanning_CoeCuenta__c coeCuenta = new FourPlanning_CoeCuenta__c();
        coeCuenta.Creacion_del_valor__c = Date.newInstance(2015, 6, 1);
        coeCuenta.Cuenta__c = cuenta.id;
        insert coeCuenta;
        
        FourPlanning_CoeCuenta__c coeCuenta2 = new FourPlanning_CoeCuenta__c();
        coeCuenta2.Creacion_del_valor__c = Date.newInstance(2016, 6, 1);
        coeCuenta2.Cuenta__c = cuenta.id;
        insert coeCuenta2;
        
        FourPlanning_CoeCuenta__c coeCuenta3 = new FourPlanning_CoeCuenta__c();
        coeCuenta3.Creacion_del_valor__c = Date.newInstance(2016, 3, 1);
        coeCuenta3.Cuenta__c = cuenta.id;
        insert coeCuenta3;
        
        FourPlanning_CoeCuenta__c coeCuenta4 = new FourPlanning_CoeCuenta__c();
        coeCuenta4.Creacion_del_valor__c = Date.newInstance(2015, 1, 1);
        coeCuenta4.Cuenta__c = cuenta.id;
        insert coeCuenta4;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
		controller.idCuenta = cuenta.id;
        
        controller.fourPlanning.Canal_Comercializacion_cliente__c = 'On-Line';
        controller.fourPlanning.Canal_Comercializacion_que_mas_crece__c = 'On-Line';
        controller.fourPlanning.Area_que_fracasamos_en_el_pasado__c = 'Cualquier valor';
        
        //esto ya crea un coeCuenta;
        controller.guardarFourPlanningCompleto();
        
        List<FourPlanning_CoeCuenta__c> coeCuentas = [SELECT ID, Creacion_del_valor__c, Cuenta__c, Valor_Coeficiente_De_Cuenta__c, lastModifiedDate FROM FourPlanning_CoeCuenta__c];
		system.debug(coeCuentas);
        system.assertEquals(4, coeCuentas.size());
        
        //me fijo que se haya borrado el que tiene la fecha mas antigua
        
        for(FourPlanning_CoeCuenta__c coe:coeCuentas){
            system.assert(!Date.newInstance(2015, 1, 1).isSameDay(coe.Creacion_del_valor__c));
        }
    }
    
    static testMethod void puedoInsertarAreas(){
        
        
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.areaAInsertar.Titulo_Area__c = 'un titulo';
        controller.areaAInsertar.Conocimiento_del_Area__c = 'Bajo';
        
        controller.insertar4Planning();
        
		controller.insertarArea();
        
        List<FourPlanning_Area__c> areas = [select id from FourPlanning_Area__c];
        system.assertEquals(1, areas.size());
		
        
    }
    
    static testMethod void puedoInsertarUnContacto(){
        
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.areaAInsertar.Titulo_Area__c = 'un titulo';
        controller.areaAInsertar.Conocimiento_del_Area__c = 'Bajo';
        
        controller.insertar4Planning();
        
        controller.insertarArea();
        
        //controller.idDelRetoDelContacto = controller.wrappersDeArea[0].wppRetos[0].reto.id;
        
        controller.contactoAInsertar.Nivel_de_Relaci_n__c = 'No lo conozco';
        controller.contactoAInsertar.Tipo_de_Contacto__c = 'CEO';
        
        controller.insertarContacto();
        
        List<FourPlanning_Contacto__c> contactos = [select id, Nivel_de_Relaci_n__c, Tipo_de_Contacto__c from fourPlanning_Contacto__c];
        
        system.assertEquals(0, contactos.size());
       // system.assertEquals('No lo conozco', contactos[0].Nivel_de_Relaci_n__c);
        //system.assertEquals('CEO', contactos[0].Tipo_de_Contacto__c);
    }
    
    static testMethod void sePuedeBorrarUnArea(){
        
        Account cuenta = new Account(name = 'nombre cuenta');
        insert cuenta;
        
        PageReference cuestionario = Page.CuestionarioFourPlanning;
        Test.setCurrentPage(cuestionario);
        cuestionario.getParameters().put('id', cuenta.id);
        
        InformacionDeLaCuentaComponentController controller = new InformacionDeLaCuentaComponentController();
        controller.idCuenta = cuenta.id;
        
        controller.areaAInsertar.Titulo_Area__c = 'un titulo';
        controller.areaAInsertar.Conocimiento_del_Area__c = 'Bajo';
        
        controller.insertar4Planning();
        
        controller.insertarArea();
        
        controller.areaABorrarId = controller.wrappersDeArea[0].area.id;
        
        controller.borrarArea();
        
        List<FourPlanning_Area__c> areas = [select id from FourPlanning_Area__c];
        
        system.assertEquals(0, areas.size());
    }
    
}