src/objects/Filtros_principales_4Planning__c.object
<CustomObject>
    <fields>
        <fullName>conectorLogico1__c</fullName>
        <label>conectorLogico1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>conectorLogico2__c</fullName>
        <label>conectorLogico2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>conectorLogico3__c</fullName>
        <label>conectorLogico3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro1Valor__c</fullName>
        <label>filtro1Valor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro2Operacion__c</fullName>
        <label>filtro2Operacion</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro2Parametro__c</fullName>
        <label>filtro2Parametro</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro2Valor__c</fullName>
        <label>filtro2Valor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>filtro3Operacion__c</fullName>
        <label>filtro3Operacion</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro3Parametro__c</fullName>
        <label>filtro3Parametro</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro3Valor__c</fullName>
        <label>filtro3Valor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>filtro4Operacion__c</fullName>
        <label>filtro4Operacion</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro4Parametro__c</fullName>
        <label>filtro4Parametro</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filtro4Valor__c</fullName>
        <label>filtro4Valor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Filtros principales 4Planning</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Nombre de Filtros principales 4Planning</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Filtros principales 4Plannings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Porcentaje_de_completitud_de_la_cuenta__c</fullName>
        <label>Cuestionario completo al</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vencimiento_Datos_Fijos__c</fullName>
        <inlineHelpText>Fecha de Vencimiento de contratos de datos fijos</inlineHelpText>
        <label>Vencimiento Datos Fijos</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>conocimiento_de_la_cuenta__c</fullName>
        <label>Coeficiente [d] Desarrollo de Cuenta</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>FourPlanning</label>
    <nameField>
        <label>Nombre de FourPlanning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>4Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Hito__c.object
<CustomObject>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripción</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fecha__c</fullName>
        <label>Fecha</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FourPlanning__c</fullName>
        <label>FourPlanning</label>
        <referenceTo>FourPlanning__c</referenceTo>
        <relationshipLabel>FourPlanning Hitos</relationshipLabel>
        <relationshipName>FourPlanning_Hitos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>FourPlanning Hito</label>
    <nameField>
        <label>Nombre de FourPlanning Hitos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Hitos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Tab4PlanningTest.cls
@isTest
public class Tab4PlanningTest {
    
    static testMethod void puedoFiltrarLasCuentasPorlasQueTienen4Planning(){
        
        Account cuenta = new Account();
        cuenta.name = 'nombre';
        insert cuenta;
        
        Account cuenta2 = new Account();
        cuenta2.name = 'nombre';
        insert cuenta2;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        fplanning.cuenta__c = cuenta.id;
        fplanning.Porcentaje_de_completitud_de_la_cuenta__c = 13;
        insert fplanning;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        controller.filtro1Valor = 'true';
        
        controller.filtrar();
        
        system.assertEquals(1, controller.cuentas.size());
    }
    
    static testMethod void puedoFiltrarLasCuentasPorlasQueNOTienen4Planning(){
        
        Account cuenta = new Account();
        cuenta.name = 'nombre';
        insert cuenta;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        //fplanning.cuenta__c = cuenta.id;
        insert fplanning;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        controller.filtro1Valor = 'false';
        
        controller.filtrar();
        
        system.assertEquals(1, controller.cuentas.size());
    }
    
    static testMethod void puedoFiltrarLasCuentasParaQueTraigaTodas(){
        
        Account cuenta = new Account();
        cuenta.name = 'nombre';
        insert cuenta;
        
        Account cuenta2 = new Account();
        cuenta2.name = 'nombre';
        insert cuenta2;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        fplanning.cuenta__c = cuenta.id;
        insert fplanning;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        controller.filtro1Valor = 'ninguno';
        
        controller.filtrar();
        
        system.assertEquals(2, controller.cuentas.size());
    }
    
    static testMethod void filtroPorLasCuentasCuyoFourPlanningTengaMasDeUnFiltro(){
        
        Account cuenta = new Account();
        cuenta.name = 'correcto';
        insert cuenta;
        
        Account cuenta2 = new Account();
        cuenta2.name = 'nombre';
        insert cuenta2;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        fplanning.cuenta__c = cuenta.id;
        fplanning.conocimiento_de_la_cuenta__c = 85;
        fplanning.Porcentaje_de_completitud_de_la_cuenta__c = 13; 
        insert fplanning;
        
        FourPlanning__c fplanning2 = new FourPlanning__c();
        fplanning2.cuenta__c = cuenta2.id;
        fplanning2.conocimiento_de_la_cuenta__c = 70;
        fplanning2.Porcentaje_de_completitud_de_la_cuenta__c = 13; 
        insert fplanning2;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        controller.filtro1Valor = 'true';
        
        controller.filtro2Parametro = 'conocimiento_de_la_cuenta__c';
        controller.filtro2Operacion = '>';
        controller.filtro2Valor = 80;
        //El conector logico es obligatorio.
        controller.conectorLogico2 = 'AND';
        
        controller.filtrar();
        
        system.assertEquals(1, controller.cuentas.size());
        system.assertEquals('correcto', controller.cuentas[0].name);
    }
    
    static testMethod void filtroPorLasCuentasCuyoFourPlanningTengaMasDeUnFiltroUtilizandoORComoConectorLogico(){
        
        Account cuenta = new Account();
        cuenta.name = 'correcto';
        insert cuenta;
        
        Account cuenta2 = new Account();
        cuenta2.name = 'nombre';
        insert cuenta2;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        fplanning.cuenta__c = cuenta.id;
        fplanning.conocimiento_de_la_cuenta__c = 85;
        fplanning.Porcentaje_de_completitud_de_la_cuenta__c = 13; 
        insert fplanning;
        
        FourPlanning__c fplanning2 = new FourPlanning__c();
        fplanning2.cuenta__c = cuenta2.id;
        fplanning2.conocimiento_de_la_cuenta__c = 70;
        fplanning2.Porcentaje_de_completitud_de_la_cuenta__c = 13; 
        insert fplanning2;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        controller.filtro1Valor = 'true';
        
        controller.filtro2Parametro = 'conocimiento_de_la_cuenta__c';
        controller.filtro2Operacion = '>';
        controller.filtro2Valor = 80;
        //El conector logico es obligatorio.
        controller.conectorLogico2 = 'OR';
        
        controller.filtro3Parametro = 'conocimiento_de_la_cuenta__c';
        controller.filtro3Operacion = '<';
        controller.filtro3Valor = 80;
        //El conector logico es obligatorio.
        controller.conectorLogico3 = 'AND';
        
        controller.filtrar();
        
        system.assertEquals(2, controller.cuentas.size());
    }
    
    static testMethod void puedoObtenerLos3Promedios(){
        
        Account cuenta = new Account();
        cuenta.name = 'correcto';
        insert cuenta;
        
        Account cuenta2 = new Account();
        cuenta2.name = 'nombre';
        insert cuenta2;
        
        Account cuenta3 = new Account();
        cuenta3.name = 'nombre';
        insert cuenta3;
        
        Account cuenta4 = new Account();
        cuenta4.name = 'nombre';
        insert cuenta4;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        fplanning.cuenta__c = cuenta.id;
        fplanning.conocimiento_de_la_cuenta__c = 80;
        fplanning.Porcentaje_de_completitud_de_la_cuenta__c = 80;
        insert fplanning;
        
        FourPlanning__c fplanning2 = new FourPlanning__c();
        fplanning2.cuenta__c = cuenta2.id;
        fplanning2.conocimiento_de_la_cuenta__c = 80;
        insert fplanning2;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        system.assertEquals(40, controller.promedioCoeDesarrollo);
        system.assertEquals(20, controller.promedioCompletitud);
        system.assertEquals(50, controller.promedioCuentasConFourPlanning);
    }
    
    
    static testMethod void seGeneraCorrectamenteElJsonParaElLineTime(){
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Vencimiento_Datos_Fijos__c = Date.today();
        fourPlanning.Cuenta__c = cuenta.id;
        insert fourPlanning;
        
        FourPlanning_Hito__c hito1 = new FourPlanning_Hito__c();
        hito1.Fecha__c = Date.today();
        hito1.Descripcion__c = 'Hito 1';
        hito1.FourPlanning__c = fourPlanning.id;
        insert hito1;
        
        
        Tab4PlanningController controller = new Tab4PlanningController();
        controller.filtrar();
        
        Date hoy = Date.today();
        Integer mes = hoy.month();
        Integer dia = hoy.day();
        Integer anio = hoy.year();
        
        String tituloDatosFijos = 'Vencimiento';
        String descripcionDatosFijos = '<b>'+cuenta.name+'<b/>'+'<p>Fecha de Vencimiento de contratos de datos fijos</p>';
        
        String vencimientoDatosFijos = '{"media":{"url":"","caption":".","credit":""},"start_date":{"month":"'+mes+'","day":"'+dia+'","year":"'+anio+'"},"text":{"headline":"'+tituloDatosFijos+'","text":"'+descripcionDatosFijos+'","tag":"Categoria 1"}}';
        
        String cabecera = '{"title":{"media":{"url":"","caption":"","credit":""},"text":{"headline":"","text":""}},"events":[';
        
        
        String hitos = '{"media":{"url":"","caption":".","credit":""},"start_date":{"month":"'+mes+'","day":"'+dia+'","year":"'+anio+'"},"text":{"headline":"Otro","text":"<b>'+cuenta.name+'<b/>'+'<p>'+hito1.descripcion__c+'</p>'+'","tag":"Categoria 1"}}';
        
        
        String JsonEsperado = cabecera + vencimientoDatosFijos +','+ hitos + ']}';
        
    }
    
    static testMethod void luegoDeGenerarElJsonPuedoFiltrarPorUnaCategoria(){
        
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Vencimiento_Datos_Fijos__c = Date.today();
        fourPlanning.Cuenta__c = cuenta.id;
        insert fourPlanning;
        
        FourPlanning_Hito__c hito1 = new FourPlanning_Hito__c();
        hito1.Fecha__c = Date.today();
        hito1.Descripcion__c = 'Hito 1';
        hito1.FourPlanning__c = fourPlanning.id;
        insert hito1;
        
        
        Tab4PlanningController controller = new Tab4PlanningController();
        controller.filtrar();
        
        Date hoy = Date.today();
        Integer mes = hoy.month();
        Integer dia = hoy.day();
        Integer anio = hoy.year();
        
        String tituloDatosFijos = 'Vencimiento';
        String descripcionDatosFijos = '<b>'+cuenta.name+'<b/>'+'<p>Fecha de Vencimiento de contratos de datos fijos</p>';
        
        String vencimientoDatosFijos = '{"media":{"url":"","caption":".","credit":""},"start_date":{"month":"'+mes+'","day":"'+dia+'","year":"'+anio+'"},"text":{"headline":"'+tituloDatosFijos+'","text":"'+descripcionDatosFijos+'","tag":"Categoria 1"}}';
        
        String cabecera = '{"title":{"media":{"url":"","caption":"","credit":""},"text":{"headline":"","text":""}},"events":[';
        
        
        String hitos = '{"media":{"url":"","caption":".","credit":""},"start_date":{"month":"'+mes+'","day":"'+dia+'","year":"'+anio+'"},"text":{"headline":"Otro","text":"<b>'+cuenta.name+'<b/>'+'<p>'+hito1.descripcion__c+'</p>'+'","tag":"Categoria 1"}}';
        
        //filtro por vencimiento.
        controller.filtroEventoTelefonica = false;
        controller.filtroEventosDeTipoReto = false;
        controller.filtroVencimientoCompetencia = false;
        controller.filtroPublicacionRFPComunicacion = false;
        controller.filtroPublicacionRFPTI = false;
        controller.filtroEventoIndustria = false;
        controller.filtroOtroTipoDeEvento = false;
        
        controller.filtrarTimeLine();
        
        String JsonEsperado = cabecera + vencimientoDatosFijos + ']}';
        
        system.assertEquals(JsonEsperado, controller.miJson);
        
        controller.filtroEventoTelefonica = true;
        controller.filtroEventosDeTipoReto = true;
        controller.filtroVencimientoCompetencia = true;
        controller.filtroPublicacionRFPComunicacion = true;
        controller.filtroPublicacionRFPTI = true;
        controller.filtroEventoIndustria = true;
        controller.filtroOtroTipoDeEvento = true;
        
        controller.filtrarTimeLine();
        
        JsonEsperado = cabecera + vencimientoDatosFijos +','+ hitos + ']}';
        
        
    }
    
    static testMethod void sePuedeAsignarValoresALosFiltros(){
        
        Filtros_principales_4Planning__c filtro = new Filtros_principales_4Planning__c();
        filtro.filtro1Valor__c = 'true';
        
        filtro.filtro2Parametro__c = 'conocimiento_de_la_cuenta__c';
        filtro.filtro2Operacion__c = '>';
        filtro.filtro2Valor__c = 80;
        
        filtro.conectorLogico2__c = 'OR';
        
        filtro.filtro3Parametro__c = 'conocimiento_de_la_cuenta__c';
        filtro.filtro3Operacion__c = '<';
        filtro.filtro3Valor__c = 80;
        
        filtro.conectorLogico3__c = 'AND';
        filtro.OwnerId = UserInfo.getUserId();
        
        insert filtro;
        
        Account cuenta = new Account();
        cuenta.name = 'correcto';
        insert cuenta;
        
        Account cuenta2 = new Account();
        cuenta2.name = 'nombre';
        insert cuenta2;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        fplanning.cuenta__c = cuenta.id;
        fplanning.conocimiento_de_la_cuenta__c = 85;
        fplanning.Porcentaje_de_completitud_de_la_cuenta__c = 13; 
        insert fplanning;
        
        FourPlanning__c fplanning2 = new FourPlanning__c();
        fplanning2.cuenta__c = cuenta2.id;
        fplanning2.conocimiento_de_la_cuenta__c = 70;
        fplanning2.Porcentaje_de_completitud_de_la_cuenta__c = 13; 
        insert fplanning2;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        system.assertEquals('OR', controller.filtro.conectorLogico2__c);
        
        controller.asignarValoresALosFiltros();
        controller.filtrarSinGuardar();
        
        system.assertEquals(2, controller.cuentas.size());
    }
    
    static testMethod void seGeneraUnObjetoFiltroCuandoFiltras(){
        
        Account cuenta = new Account();
        cuenta.name = 'correcto';
        insert cuenta;
        
        Account cuenta2 = new Account();
        cuenta2.name = 'nombre';
        insert cuenta2;
        
        FourPlanning__c fplanning = new FourPlanning__c();
        fplanning.cuenta__c = cuenta.id;
        fplanning.conocimiento_de_la_cuenta__c = 85;
        insert fplanning;
        
        FourPlanning__c fplanning2 = new FourPlanning__c();
        fplanning2.cuenta__c = cuenta2.id;
        fplanning2.conocimiento_de_la_cuenta__c = 70;
        insert fplanning2;
        
        Tab4PlanningController controller = new Tab4PlanningController();
        
        controller.filtro1Valor = 'true';
        
        controller.filtro2Parametro = 'conocimiento_de_la_cuenta__c';
        controller.filtro2Operacion = '>';
        controller.filtro2Valor = 80;
        //El conector logico es obligatorio.
        controller.conectorLogico2 = 'OR';
        
        controller.filtro3Parametro = 'conocimiento_de_la_cuenta__c';
        controller.filtro3Operacion = '<';
        controller.filtro3Valor = 80;
        //El conector logico es obligatorio.
        controller.conectorLogico3 = 'AND';
        
        controller.filtrarSinGuardar();
        controller.guardarFiltros();
        
        
        List<Filtros_principales_4Planning__c> filtros = [select id, ownerId, filtro2Parametro__c, filtro3Parametro__c, filtro4Parametro__c, filtro2Operacion__c,
                                                          filtro3Operacion__c, filtro4Operacion__c, filtro1Valor__c, filtro2Valor__c, filtro3Valor__c,
                                                          filtro4Valor__c, conectorLogico1__c, conectorLogico2__c, conectorLogico3__c
                                                          from Filtros_principales_4Planning__c ];
        
        system.assertEquals(1, filtros.size());
        system.assertEquals('conocimiento_de_la_cuenta__c', filtros[0].filtro2Parametro__c);
        system.assertEquals('conocimiento_de_la_cuenta__c', filtros[0].filtro3Parametro__c);
        
    }
}