src/objects/FourPlanning__c.object
<CustomObject>
    <fields>
        <fullName>Agenda_Periodica_Ejecutiva__c</fullName>
        <inlineHelpText>¿Tenemos agenda periódica ejecutiva con participación de nivel directivo de ambas organizaciones?</inlineHelpText>
        <label>Agenda Periodica Ejecutiva</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agenda_Periodica_Operacional__c</fullName>
        <inlineHelpText>¿Tenemos agenda periódica operacional sobre la calidad de los servicios prestados?</inlineHelpText>
        <label>Agenda Periodica Operacional</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Area_que_fracasamos_en_el_pasado__c</fullName>
        <inlineHelpText>¿Existen áreas en el cliente con las que, teniendo productos y soluciones, no estamos teniendo relación?</inlineHelpText>
        <label>Area que fracasamos en el pasado</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Canal_Comercializacion_cliente__c</fullName>
        <description>Principal Canal de Comercialización del Cliente</description>
        <label>Canal Comercializacion cliente</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On-Line</fullName>
                </value>
                <value>
                    <fullName>Off-Line</fullName>
                </value>
                <value>
                    <fullName>Ambos</fullName>
                </value>
                <value>
                    <fullName>No disponible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Canal_Comercializacion_que_mas_crece__c</fullName>
        <inlineHelpText>¿Cuál es el canal de comercialización que más esta creciendo?</inlineHelpText>
        <label>Canal Comercializacion que mas crece</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On-Line</fullName>
                </value>
                <value>
                    <fullName>Off-Line</fullName>
                </value>
                <value>
                    <fullName>Ambos</fullName>
                </value>
                <value>
                    <fullName>Nula</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 1)</relationshipLabel>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 2)</relationshipLabel>
        <relationshipName>FourPlannings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 3)</relationshipLabel>
        <relationshipName>FourPlannings2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frecuencia_Funcionarios_del_Cliente__c</fullName>
        <inlineHelpText>¿Con que Frecuencia te reúnes con tu Cliente?</inlineHelpText>
        <label>Frecuencia Funcionarios del Cliente</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Semanal</fullName>
                </value>
                <value>
                    <fullName>Quincenal</fullName>
                </value>
                <value>
                    <fullName>Mensual</fullName>
                </value>
                <value>
                    <fullName>Trimestral</fullName>
                </value>
                <value>
                    <fullName>No me reúno</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frecuencia_de_Contacto_con_el_Cliente__c</fullName>
        <label>Frecuencia de Contacto con el Cliente</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diaria</fullName>
                </value>
                <value>
                    <fullName>Semanal</fullName>
                </value>
                <value>
                    <fullName>Quincenal</fullName>
                </value>
                <value>
                    <fullName>Mensual</fullName>
                </value>
                <value>
                    <fullName>Ocasional</fullName>
                </value>
                <value>
                    <fullName>No me reúno</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mayor_Nivel_de_Contacto_con_el_Cliente__c</fullName>
        <label>Mayor Nivel de Contacto con el Cliente</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C level</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Gerente</fullName>
                </value>
                <value>
                    <fullName>Jefe</fullName>
                </value>
                <value>
                    <fullName>Analista</fullName>
                </value>
                <value>
                    <fullName>Usuarios</fullName>
                </value>
                <value>
                    <fullName>Sin Contacto</fullName>
                </value>
                <value>
                    <fullName>Otros</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mejoraria_Relacion_Con_El_Cliente__c</fullName>
        <inlineHelpText>En las áreas con las que tenemos relación, ¿Crees que esta mejoraría si tuviésemos más reuniones?</inlineHelpText>
        <label>Mejoraria Relacion Con El Cliente</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>realcion_empresa_otros_clientes__c</fullName>
        <inlineHelpText>¿Conoces lo que Telefónica hace en otros países con clientes semejantes al tuyo?</inlineHelpText>
        <label>realcion empresa/otros clientes</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Si</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FourPlanning</label>
    <nameField>
        <label>Nombre de FourPlanning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>4Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Area__c.object
<CustomObject>
    <fields>
        <fullName>FourPlanning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning</label>
        <referenceTo>FourPlanning__c</referenceTo>
        <relationshipLabel>FourPlanning Areas</relationshipLabel>
        <relationshipName>FourPlanning_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FourPlanning Area</label>
    <nameField>
        <label>Nombre de FourPlanning Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Reto__c.object
<CustomObject>
    <fields>
        <fullName>Etapa_del_Reto__c</fullName>
        <label>Etapa del Reto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospección</fullName>
                </value>
                <value>
                    <fullName>Diseño</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Compras</fullName>
                </value>
                <value>
                    <fullName>Implementación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FourPlanning_Area__c</fullName>
        <label>FourPlanning Area</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>FourPlanning Retos</relationshipLabel>
        <relationshipName>FourPlanning_Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nota__c</fullName>
        <label>Comentarios</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>FourPlanning Reto</label>
    <nameField>
        <label>Nombre de FourPlanning Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CalculadorDelConocimientoDeLaCuentaTest.cls
@isTest
public class CalculadorDelConocimientoDeLaCuentaTest {

    static testMethod void obtengoElCoeficienteDeConocimientoDeLaCuentaEnCienPorciento(){
        
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
        
        FourPlanning_Area__c area3 = new FourPlanning_Area__c();
        FourPlanning_Area__c area1 = new FourPlanning_Area__c();
        FourPlanning_Area__c area2 = new FourPlanning_Area__c();
        
        List<FourPlanning_Area__c> areas = new List<FourPlanning_Area__c> {area1, area2, area3};
        insert areas;
        
        FourPlanning_Reto__c reto1 = new FourPlanning_Reto__c();
        reto1.FourPlanning_Area__c = area3.id;
        reto1.Nombre_del_Reto__c = 'a';
        reto1.Nota__c = 'a';
        reto1.Etapa_del_Reto__c = 'Diseño';
        
        FourPlanning_Reto__c reto2  = new FourPlanning_Reto__c();
        reto2.FourPlanning_Area__c = area2.id;
        reto2.Nombre_del_Reto__c = 'a';
        reto2.Nota__c = 'a';
        reto2.Etapa_del_Reto__c = 'Diseño';
        
        FourPlanning_Reto__c reto3  = new FourPlanning_Reto__c();
        reto3.FourPlanning_Area__c = area1.id;
        reto3.Nombre_del_Reto__c = 'a';
        reto3.Nota__c = 'a';
        reto3.Etapa_del_Reto__c = 'Diseño';
        
        List<FourPlanning_Reto__c> retos = new List<FourPlanning_Reto__c> {reto1, reto2, reto3};
            insert retos;
        
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuenta.id;
        fourPlanning.FourPlanning_Area_3__c = area3.id;
        fourPlanning.FourPlanning_Area_2__c = area2.id;
        fourPlanning.FourPlanning_Area_1__c = area1.id;
        fourPlanning.Mayor_Nivel_de_Contacto_con_el_Cliente__c = 'C level';
        fourPlanning.Frecuencia_de_Contacto_con_el_Cliente__c = 'Periodica';
        fourPlanning.Agenda_Periodica_Ejecutiva__c = 'Si';
        fourPlanning.Agenda_Periodica_Operacional__c = 'Si';
        fourPlanning.Frecuencia_Funcionarios_del_Cliente__c = 'Semanal';
        fourPlanning.Canal_Comercializacion_cliente__c = 'On-Line';
        fourPlanning.Canal_Comercializacion_que_mas_crece__c = 'On-Line';
        fourPlanning.Area_que_fracasamos_en_el_pasado__c = 'Cualquier valor';
        fourPlanning.Mejoraria_Relacion_Con_El_Cliente__c = 'Si';
        fourPlanning.realcion_empresa_otros_clientes__c = 'Si';
        insert fourPlanning;
        
		CalculadorDelConocimientoDeLaCuenta calculador = new CalculadorDelConocimientoDeLaCuenta(fourPlanning);
		calculador.obtenerCalculoDeCoeficienteDelDesarrolloDelCliente();
        
        
    }
}