src/objects/FourPlanning__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 1)</relationshipLabel>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 2)</relationshipLabel>
        <relationshipName>FourPlannings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 3)</relationshipLabel>
        <relationshipName>FourPlannings2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel_de_conocimiento_area1__c</fullName>
        <label>Obsoleto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alto</fullName>
                </value>
                <value>
                    <fullName>Medio</fullName>
                </value>
                <value>
                    <fullName>Bajo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nivel_de_conocimiento_area2__c</fullName>
        <label>Obsoleto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alto</fullName>
                </value>
                <value>
                    <fullName>Medio</fullName>
                </value>
                <value>
                    <fullName>Bajo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nivel_de_conocimiento_area3__c</fullName>
        <label>Obsoleto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alto</fullName>
                </value>
                <value>
                    <fullName>Medio</fullName>
                </value>
                <value>
                    <fullName>Bajo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Titulo_Area_1__c</fullName>
        <label>Obsoleto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Titulo_Area_2__c</fullName>
        <label>Obsoleto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Titulo_Area_3__c</fullName>
        <label>Obsoleto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>conocimiento_de_la_cuenta__c</fullName>
        <label>Coeficiente [d] Desarrollo de Cuenta</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>FourPlanning</label>
    <nameField>
        <label>Nombre de FourPlanning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>4Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Area__c.object
<CustomObject>
    <fields>
        <fullName>FourPlanning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning</label>
        <referenceTo>FourPlanning__c</referenceTo>
        <relationshipLabel>FourPlanning Areas</relationshipLabel>
        <relationshipName>FourPlanning_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FourPlanning Area</label>
    <nameField>
        <label>Nombre de FourPlanning Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Reto__c.object
<CustomObject>
    <fields>
        <fullName>Contactos_del_Cliente__c</fullName>
        <label>Contactos del Cliente</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Director de RRHH</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director de Compras</fullName>
                </value>
                <value>
                    <fullName>Director de Negocio</fullName>
                </value>
                <value>
                    <fullName>CISO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>CTO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estado_de_la_solucion__c</fullName>
        <label>No se usa</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Disponible</fullName>
                </value>
                <value>
                    <fullName>En Desarrollo</fullName>
                </value>
                <value>
                    <fullName>No Disponible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Etapa_del_Reto__c</fullName>
        <label>Etapa del Reto</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospección</fullName>
                </value>
                <value>
                    <fullName>Diseño</fullName>
                </value>
                <value>
                    <fullName>RFI</fullName>
                </value>
                <value>
                    <fullName>RFP</fullName>
                </value>
                <value>
                    <fullName>Compras</fullName>
                </value>
                <value>
                    <fullName>Implementación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fecha_Compromiso__c</fullName>
        <label>Fecha Compromiso</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area__c</fullName>
        <label>FourPlanning Area</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>FourPlanning Retos</relationshipLabel>
        <relationshipName>FourPlanning_Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nivel_de_relaci_n_contacto__c</fullName>
        <label>Nivel de relación contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Buena</fullName>
                </value>
                <value>
                    <fullName>Regular</fullName>
                </value>
                <value>
                    <fullName>Mala</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Productos_a_Desarrollar_Vender__c</fullName>
        <label>No se usa</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Conectividad</fullName>
                </value>
                <value>
                    <fullName>Movilidad</fullName>
                </value>
                <value>
                    <fullName>Virtualización y Computación en modo Opex</fullName>
                </value>
                <value>
                    <fullName>Internet de las Cosas/Control de Objetos</fullName>
                </value>
                <value>
                    <fullName>Omnicanalidad</fullName>
                </value>
                <value>
                    <fullName>Digital WorkPlace (Puesto de Trabajo Digital)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FourPlanning Reto</label>
    <nameField>
        <label>Nombre de FourPlanning Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FourPlanningResumenController.cls
public class FourPlanningResumenController {

    public String idCuenta {get; set;}
    public FourPlanning__C fourPlanning {get; set;}
    
    public List<FourPlanning_Reto__c> retosArea1 {get; set;}
    public List<FourPlanning_Reto__c> retosArea2 {get; set;}
    public List<FourPlanning_Reto__c> retosArea3 {get; set;}
    
    public Boolean hayDatos {get; set;}
    public String activo {get; set;}
    
    public FourPlanningResumenController(){
    	fourPlanning = new FourPlanning__c();
        
        idCuenta = ApexPages.currentPage().getParameters().get('Id');
        
        Activo = 'No';
		List<FourPlanning__c> fourPlannings = new List<FourPlanning__c>();        
        if(idCuenta != null){
            
            fourPlannings = [SELECT Id, FourPlanning_Area_1__c, FourPlanning_Area_2__c, FourPlanning_Area_3__c,
                             Titulo_Area_1__c, Titulo_Area_2__c, Titulo_Area_3__c, Nivel_de_conocimiento_area1__c, Nivel_de_conocimiento_area2__c, Nivel_de_conocimiento_area3__c,
                             conocimiento_de_la_cuenta__c, LastModifiedDate
                             FROM FourPlanning__c 
                             WHERE Cuenta__c =: idCuenta
                             LIMIT 1];
            
            if(fourPlannings.size() > 0){
                fourPlanning = fourPlannings[0];
                Activo = 'Si';
                system.debug(fourPlanning);
            }
        }
        
        retosArea1 = new List<FourPlanning_Reto__c>();
        retosArea2 = new List<FourPlanning_Reto__c>();
        retosArea3 = new List<FourPlanning_Reto__c>();
        
        if(FourPlanning.FourPlanning_Area_1__c != null){
            retosArea1 = [SELECT ID, Nombre_del_Reto__c, Contactos_del_Cliente__c, Productos_a_Desarrollar_Vender__c, Estado_de_la_solucion__c, Nivel_de_relaci_n_contacto__c, Etapa_del_Reto__c,
                          Fecha_Compromiso__c
                          FROM FourPlanning_Reto__c 
                          WHERE FourPlanning_Area__c =: FourPlanning.FourPlanning_Area_1__c];
        }
        
        system.debug(retosArea1);
        
        if(FourPlanning.FourPlanning_Area_2__c != null){
            retosArea2 = [SELECT ID, Nombre_del_Reto__c, Contactos_del_Cliente__c, Productos_a_Desarrollar_Vender__c, Estado_de_la_solucion__c, Nivel_de_relaci_n_contacto__c, Etapa_del_Reto__c,
                          Fecha_Compromiso__c
                          FROM FourPlanning_Reto__c 
                          WHERE FourPlanning_Area__c =: FourPlanning.FourPlanning_Area_2__c];
        }
        
        if(FourPlanning.FourPlanning_Area_3__c != null){    
            retosArea3 = [SELECT ID, Nombre_del_Reto__c, Contactos_del_Cliente__c, Productos_a_Desarrollar_Vender__c, Estado_de_la_solucion__c, Nivel_de_relaci_n_contacto__c, Etapa_del_Reto__c,
                          Fecha_Compromiso__c
                          FROM FourPlanning_Reto__c 
                          WHERE FourPlanning_Area__c =: FourPlanning.FourPlanning_Area_3__c];
        }
        
        hayDatos = false; 
        if(fourPlanning != null){
        	hayDatos = true;	    
        }
        
    }
}