src/objects/FourPlanning_Hito_global__c.object
<CustomObject>
    <fields>
        <fullName>Descripcion__c</fullName>
        <label>Descripcion</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Comercio</fullName>
                </value>
                <value>
                    <fullName>Comunicaciones y tecnologia</fullName>
                </value>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Industria</fullName>
                </value>
                <value>
                    <fullName>Sector Público</fullName>
                </value>
                <value>
                    <fullName>Servicios</fullName>
                </value>
                <value>
                    <fullName>Servicios Públicos</fullName>
                </value>
                <value>
                    <fullName>Transporte</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FourPlanning Hito global</label>
    <nameField>
        <label>Nombre de FourPlanning Hito global</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Hitos globales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/administracionHitosGlobalesTest.cls
@isTest
public class administracionHitosGlobalesTest {

    static testMethod void puedoInsertarUnHitoGlobal(){
        
        administracionHitosGlobalesController controller = new administracionHitosGlobalesController();
        
        controller.hitoGlobalAInsertar.descripcion__c = 'una descripcion';
        controller.hitoGlobalAInsertar.Sector__c = 'Todos';
        
        controller.InsertarHitoGlobal();
        
        List<FourPlanning_Hito_global__c> hitoGlobales = [select id from FourPlanning_Hito_global__c];
        
        system.assertEquals(1, hitoGlobales.size());
    }
    
    static testMethod void borrarEvento(){
        
        administracionHitosGlobalesController controller = new administracionHitosGlobalesController();
        
        controller.hitoGlobalAInsertar.descripcion__c = 'una descripcion';
        controller.hitoGlobalAInsertar.Sector__c = 'Todos';
        
        controller.InsertarHitoGlobal();
        
        controller.idABorrar = [select id from FourPlanning_Hito_global__c][0].id;
        
        controller.renderizarPagina();
        controller.borrarEvento();
        
        List<FourPlanning_Hito_global__c> hitoGlobales = [select id from FourPlanning_Hito_global__c];
        
        system.assertEquals(0, hitoGlobales.size());

    }
}