src/objects/FourPlanning__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 1)</relationshipLabel>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 2)</relationshipLabel>
        <relationshipName>FourPlannings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FourPlanning_Area_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Obsoleto</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>4Planning (FourPlanning Area 3)</relationshipLabel>
        <relationshipName>FourPlannings2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Titulo_Area_1__c</fullName>
        <label>Obsoleto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Titulo_Area_2__c</fullName>
        <label>Obsoleto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Titulo_Area_3__c</fullName>
        <label>Obsoleto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FourPlanning</label>
    <nameField>
        <label>Nombre de FourPlanning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>4Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Area__c.object
<CustomObject>
    <fields>
        <fullName>FourPlanning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning</label>
        <referenceTo>FourPlanning__c</referenceTo>
        <relationshipLabel>FourPlanning Areas</relationshipLabel>
        <relationshipName>FourPlanning_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FourPlanning Area</label>
    <nameField>
        <label>Nombre de FourPlanning Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Reto__c.object
<CustomObject>
    <fields>
        <fullName>Contactos_del_Cliente__c</fullName>
        <label>Contactos del Cliente</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Director de RRHH</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director de Compras</fullName>
                </value>
                <value>
                    <fullName>Director de Negocio</fullName>
                </value>
                <value>
                    <fullName>CISO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>CTO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FourPlanning_Area__c</fullName>
        <label>FourPlanning Area</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>FourPlanning Retos</relationshipLabel>
        <relationshipName>FourPlanning_Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Productos_a_Desarrollar_Vender__c</fullName>
        <label>No se usa</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Conectividad</fullName>
                </value>
                <value>
                    <fullName>Movilidad</fullName>
                </value>
                <value>
                    <fullName>Virtualización y Computación en modo Opex</fullName>
                </value>
                <value>
                    <fullName>Internet de las Cosas/Control de Objetos</fullName>
                </value>
                <value>
                    <fullName>Omnicanalidad</fullName>
                </value>
                <value>
                    <fullName>Digital WorkPlace (Puesto de Trabajo Digital)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FourPlanning Reto</label>
    <nameField>
        <label>Nombre de FourPlanning Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FourPlanningResumenTest.cls
@isTest
public class FourPlanningResumenTest {

    static testMethod void traigoElFourPlanningDeLaCuentaJuntoConSusRetos(){
        
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
		
        FourPlanning_Area__c area3 = new FourPlanning_Area__c();
        FourPlanning_Area__c area1 = new FourPlanning_Area__c();
        FourPlanning_Area__c area2 = new FourPlanning_Area__c();
        
        List<FourPlanning_Area__c> areas = new List<FourPlanning_Area__c> {area1, area2, area3};
        insert areas;
        
        FourPlanning_Reto__c reto1 = new FourPlanning_Reto__c();
        reto1.FourPlanning_Area__c = area3.id;
        reto1.Nombre_del_Reto__c = 'a';
        reto1.Contactos_del_Cliente__c = 'a';
        reto1.Productos_a_Desarrollar_Vender__c = 'Diseño';
        
        FourPlanning_Reto__c reto2  = new FourPlanning_Reto__c();
        reto2.FourPlanning_Area__c = area2.id;
        reto2.Nombre_del_Reto__c = 'a';
        reto2.Contactos_del_Cliente__c = 'a';
        reto2.Productos_a_Desarrollar_Vender__c = 'Diseño';
        
        FourPlanning_Reto__c reto3  = new FourPlanning_Reto__c();
        reto3.FourPlanning_Area__c = area1.id;
        reto3.Nombre_del_Reto__c = 'a';
        reto3.Contactos_del_Cliente__c = 'a;b';
        reto3.Productos_a_Desarrollar_Vender__c = 'Diseño';
        
        List<FourPlanning_Reto__c> retos = new List<FourPlanning_Reto__c> {reto1, reto2, reto3};
        insert retos;
        
		FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuenta.id;
        fourPlanning.FourPlanning_Area_3__c = area3.id;
        fourPlanning.FourPlanning_Area_2__c = area2.id;
        fourPlanning.FourPlanning_Area_1__c = area1.id;
        fourPlanning.Titulo_Area_1__c = 'TituloA1';
        fourPlanning.Titulo_Area_2__c = 'TituloA2';
        fourPlanning.Titulo_Area_3__c = 'TituloA3';

        insert fourPlanning;
		
        PageReference fourPlanningResumen = Page.accountCustomReport;
        Test.setCurrentPage(fourPlanningResumen);
        fourPlanningResumen.getParameters().put('Id', cuenta.id);
        
        FourPlanningResumenController controller = new FourPlanningResumenController();
        
        system.assertEquals(1, controller.retosArea1.size());
        system.assertEquals(reto3.id, controller.retosArea1[0].id);

    }
}