src/objects/FourPlanning__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>FourPlannings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FourPlanning</label>
    <nameField>
        <label>Nombre de FourPlanning</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>4Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Area__c.object
<CustomObject>
    <fields>
        <fullName>FourPlanning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FourPlanning</label>
        <referenceTo>FourPlanning__c</referenceTo>
        <relationshipLabel>FourPlanning Areas</relationshipLabel>
        <relationshipName>FourPlanning_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Titulo_Area__c</fullName>
        <label>Titulo Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FourPlanning Area</label>
    <nameField>
        <label>Nombre de FourPlanning Area</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FourPlanning_Contacto__c.object
<CustomObject>
    <fields>
        <fullName>Nivel_de_Relaci_n__c</fullName>
        <label>Nivel de Relación</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fluida y Constante</fullName>
                </value>
                <value>
                    <fullName>Ocasional pero Cordial</fullName>
                </value>
                <value>
                    <fullName>Intensa y Difícil</fullName>
                </value>
                <value>
                    <fullName>No lo conozco</fullName>
                </value>
                <value>
                    <fullName>Es “Anti-Telefonica”</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reto__c</fullName>
        <label>FourPlanning Reto</label>
        <referenceTo>FourPlanning_Reto__c</referenceTo>
        <relationshipLabel>FourPlanning Contactos</relationshipLabel>
        <relationshipName>FourPlanning_Contactos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>FourPlanning Contacto</label>
    <nameField>
        <label>Nombre de FourPlanning Contacto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Contactos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FourPlanning_Reto__c.object
<CustomObject>
    <fields>
        <fullName>Contactos_del_Cliente__c</fullName>
        <label>Contactos del Cliente</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Director de RRHH</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Director de Compras</fullName>
                </value>
                <value>
                    <fullName>Director de Negocio</fullName>
                </value>
                <value>
                    <fullName>CISO</fullName>
                </value>
                <value>
                    <fullName>CIO</fullName>
                </value>
                <value>
                    <fullName>CTO</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FourPlanning_Area__c</fullName>
        <label>FourPlanning Area</label>
        <referenceTo>FourPlanning_Area__c</referenceTo>
        <relationshipLabel>FourPlanning Retos</relationshipLabel>
        <relationshipName>FourPlanning_Retos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Nombre_del_Reto__c</fullName>
        <label>Nombre del Reto</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Productos_a_Desarrollar_Vender__c</fullName>
        <label>No se usa</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Conectividad</fullName>
                </value>
                <value>
                    <fullName>Movilidad</fullName>
                </value>
                <value>
                    <fullName>Virtualización y Computación en modo Opex</fullName>
                </value>
                <value>
                    <fullName>Internet de las Cosas/Control de Objetos</fullName>
                </value>
                <value>
                    <fullName>Omnicanalidad</fullName>
                </value>
                <value>
                    <fullName>Digital WorkPlace (Puesto de Trabajo Digital)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FourPlanning Reto</label>
    <nameField>
        <label>Nombre de FourPlanning Reto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Retos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FourPlanning_Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Nivel_de_Desarrollo__c</fullName>
        <label>Nivel de Desarrollo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Disponible</fullName>
                </value>
                <value>
                    <fullName>En Desarrollo</fullName>
                </value>
                <value>
                    <fullName>No Disponible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reto__c</fullName>
        <label>FourPlanning Reto</label>
        <referenceTo>FourPlanning_Reto__c</referenceTo>
        <relationshipLabel>FourPlanning Soluciones</relationshipLabel>
        <relationshipName>FourPlanning_Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>FourPlanning Solucion</label>
    <nameField>
        <label>Nombre de FourPlanning Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FourPlanning Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EjesDeTrabajoTest.cls
@isTest
public class EjesDeTrabajoTest {

    static testMethod void seCarganLosRetos(){
        

        
        Account cuenta = new Account(name = 'Nombre Cuenta');
        insert cuenta;
		
        FourPlanning__c fourPlanning = new FourPlanning__c();
        fourPlanning.Cuenta__c = cuenta.id;
        
        insert fourPlanning; 
        
        FourPlanning_Area__c area3 = new FourPlanning_Area__c();
        area3.FourPlanning__c = fourPlanning.id;
        area3.Titulo_Area__c = 'TituloA3';
        FourPlanning_Area__c area1 = new FourPlanning_Area__c();
        area1.FourPlanning__c = fourPlanning.id;
        area1.Titulo_Area__c = 'TituloA1';
        FourPlanning_Area__c area2 = new FourPlanning_Area__c();
        area2.FourPlanning__c = fourPlanning.id;
        area2.Titulo_Area__c = 'TituloA2';
        FourPlanning_Area__c area4 = new FourPlanning_Area__c();
        area4.FourPlanning__c = fourPlanning.id;
        area4.Titulo_Area__c = 'TituloA4';
        FourPlanning_Area__c area5 = new FourPlanning_Area__c();
        area5.FourPlanning__c = fourPlanning.id;
		area5.Titulo_Area__c = 'TituloA5';
        
        List<FourPlanning_Area__c> areas = new List<FourPlanning_Area__c> {area1, area2, area3, area4, area5};
        insert areas;
        
        FourPlanning_Reto__c reto1 = new FourPlanning_Reto__c();
        reto1.FourPlanning_Area__c = area3.id;
        reto1.Nombre_del_Reto__c = 'a';
        reto1.Contactos_del_Cliente__c = 'a';
        reto1.Productos_a_Desarrollar_Vender__c = 'Diseño';
        
        FourPlanning_Reto__c reto2  = new FourPlanning_Reto__c();
        reto2.FourPlanning_Area__c = area2.id;
        reto2.Nombre_del_Reto__c = 'a';
        reto2.Contactos_del_Cliente__c = 'a';
        reto2.Productos_a_Desarrollar_Vender__c = 'Diseño';
        
        FourPlanning_Reto__c reto3  = new FourPlanning_Reto__c();
        reto3.FourPlanning_Area__c = area1.id;
        reto3.Nombre_del_Reto__c = 'a';
        reto3.Contactos_del_Cliente__c = 'a;b';
        reto3.Productos_a_Desarrollar_Vender__c = 'Diseño';
        
        List<FourPlanning_Reto__c> retos = new List<FourPlanning_Reto__c> {reto1, reto2, reto3};
        insert retos;
        
        FourPlanning_Contacto__c contacto = new FourPlanning_Contacto__c();
        contacto.name = 'asd';
        contacto.reto__c = reto1.id;
        contacto.Nivel_de_Relaci_n__c = 'Fluida y Constante';
        insert contacto;
        
        FourPlanning_Contacto__c contacto2 = new FourPlanning_Contacto__c();
        contacto2.name = 's';
        contacto2.reto__c = reto1.id;
        contacto2.Nivel_de_Relaci_n__c = 'Intensa y Difícil' ;
        insert contacto2;
        
        FourPlanning_Contacto__c contacto3 = new FourPlanning_Contacto__c();
        contacto3.name = 'd';
        contacto3.reto__c = reto1.id;
        contacto3.Nivel_de_Relaci_n__c = 'No lo conozco';
        insert contacto3;
	
		FourPlanning_Solucion__c solucion1 = new FourPlanning_Solucion__c();
        solucion1.name = 'asd';
        solucion1.Nivel_de_Desarrollo__c = 'Disponible';
        solucion1.reto__c = reto1.id;
        insert solucion1;
		
        FourPlanning_Solucion__c solucion2 = new FourPlanning_Solucion__c();
        solucion2.name = 'as';
        solucion2.Nivel_de_Desarrollo__c = 'En Desarrollo';
        solucion2.reto__c = reto1.id;
        insert solucion2;
        
        FourPlanning_Solucion__c solucion3 = new FourPlanning_Solucion__c();
        solucion3.name = 'd';
        solucion3.Nivel_de_Desarrollo__c = 'No Disponible';
        solucion3.reto__c = reto1.id;
        insert solucion3;
        
        PageReference ejesDeTrabajo = Page.EjesDeTrabajo;
        Test.setCurrentPage(ejesDeTrabajo);
        ejesDeTrabajo.getParameters().put('Id', cuenta.id);
        
        EjesDeTrabajoController controller = new EjesDeTrabajoController();
        controller.irAPlanDeAccion();
        controller.irADesarrolloCuenta();
        controller.irACuestionario();
        controller.irAInicio();
        controller.irAForYou();
        
		system.assertEquals(5, controller.areas.size());
        system.assertEquals(1, controller.areas[0].retos.size());
        
    }
}