src/objects/Linea_de_Servicio__c.object
<CustomObject>
    <label>Linea de Servicio</label>
    <nameField>
        <label>Nombre de Linea de Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lineas de Servicio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Linea_de_Servicio__c</fullName>
        <label>Linea de Servicio</label>
        <referenceTo>Linea_de_Servicio__c</referenceTo>
        <relationshipLabel>Soluciones</relationshipLabel>
        <relationshipName>Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Solucion</label>
    <nameField>
        <label>Nombre de Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdministrarSolucionesTest.cls
@isTest
public class AdministrarSolucionesTest {

    static testMethod void test1(){
        
        
        AdministrarSolucionesController controller = new AdministrarSolucionesController();
        
        system.assertEquals(0, controller.lineasDeServicios.size());
        
        
        Linea_de_Servicio__c lineaServicio2 = new Linea_de_Servicio__c();
        lineaServicio2.name = 'test2';
        controller.lineaDeServicioAInsertar = lineaServicio2;
        
        controller.insertarLineaDeServicio();
        
        Linea_de_Servicio__c lineaServicio1 = new Linea_de_Servicio__c();
        lineaServicio1.name = 'test1';
        controller.lineaDeServicioAInsertar = lineaServicio1;
        
        controller.insertarLineaDeServicio();
        
        system.assertEquals(2, controller.lineasDeServicios.size());
        
        Solucion__c solucion1 = new Solucion__c();
        controller.lineaPadreDeLaSolucionAInsertar = lineaServicio1.id;
        controller.solucionAInsertar = solucion1;
       
        controller.insertarSolucion();
        
        controller.solucionABorrarId = solucion1.id;
        controller.borrarSolucion();
        
        controller.lineaABorrarId = lineaServicio1.id;
        controller.borrarLineaDeServicio();
        
         system.assertEquals(1, controller.lineasDeServicios.size());
        
        
    }

}