src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_FCV_Calculated__c</fullName>
        <description>Field to calculate the sum of Estimated in Suboportunities</description>
        <inlineHelpText>Adding up the estimated FCV of the sub opportunities win or in progress (not loss or cancelled)
Is the FCV considered for commercial dashboard and reporting
Posible Values: Calculated field in €.
Filled in by: Calculated automatically.</inlineHelpText>
        <label>Campo Inactivo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_FCV__c</fullName>
        <description>Estimated by the account manager in early stages of the opportunity (m€)</description>
        <inlineHelpText>The account manager indicates an estimation of the total value of the project.
Posible Values: Free field in €
Filled in by: The account manager.</inlineHelpText>
        <label>Campo Inactivo</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Year_End_Revenue__c</fullName>
        <label>Ingresos Totales año fiscal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Full_Contract_Value__c</fullName>
        <label>Campo Inactivo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Charges__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Ingreso recurrente mensual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unique_Charges__c</fullName>
        <label>Ingreso por única vez</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/test_owrap.cls
@isTest
private class test_owrap {

    static testMethod void myUnitTest() {
        Account cuenta=new Account();
        cuenta.Name='test';
        cuenta.industry = 'Banking';        
        insert cuenta;
        
        Opportunity opp = new Opportunity(Name='test opportunity');
        opp.StageName = 'Open';
        opp.CloseDate = System.Today();
        opp.accountId = cuenta.Id;
        Owrap o = new Owrap(opp);       
        o.getFull_Contract_Value(); 
        o.getUnique_Charges();
        o.getMonthly_Charges();
        o.getEstimated_Year_End_Revenue();
        o.getUnsold_Pipeline();
        o.getWeighted_Estimated_Year_End_Revenue();
        o.getEstimated_FCV();
        o.getEstimated_FCV_Calculated();        
        o.getTotal_Forecasted_FCV();
        
        opp.Estimated_Year_End_Revenue__c = 10;
        opp.Full_Contract_Value__c = 10;
        opp.Unique_Charges__c = 10;
        opp.Monthly_Charges__c = 10;
        opp.Estimated_Year_End_Revenue__c = 10; 
        opp.Estimated_FCV__c = 10;
        opp.Estimated_FCV_Calculated__c = 10;
               
        if(Util.checkMultiCurrencyEnabled()){
            opp.put('CurrencyIsoCode','EUR');
        }
        
    opp.Probability = 10;
    insert opp;    
    
    Owrap o2 = new Owrap(opp);                
        o2.getFull_Contract_Value(); 
        o2.getUnique_Charges();
        o2.getMonthly_Charges();
        o2.getEstimated_Year_End_Revenue();
        o2.getUnsold_Pipeline();
        o2.getWeighted_Estimated_Year_End_Revenue();
        o2.getEstimated_FCV();
        o2.getEstimated_FCV_Calculated();        
        o2.getTotal_Forecasted_FCV();
                
    }
}