src/objects/Power_BI_link__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Power BI links</relationshipLabel>
        <relationshipName>Power_BI_links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pais__c</fullName>
        <label>Pais</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Power BI link</label>
    <nameField>
        <label>Nombre de Power BI</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Power BI links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ImprimirAccountPlanBIController.cls
public class ImprimirAccountPlanBIController {
	
    public String idCuenta {get;set;}
    public String url {get;set;}
    
    public ImprimirAccountPlanBIController(){
        
        idCuenta = ApexPages.currentPage().getParameters().get('Id');
        
        String pais = 'Argentina';
        Set<String> objectFields = Schema.SObjectType.Account.fields.getMap().keySet();
        
        if( objectFields.contains('bi_country__c') ) {
            list<Account> cuentasTelefonica = database.query('select id, bi_country__c from account where id=:idCuenta');
            pais = '';
            
            if(cuentasTelefonica.size()>0){
                pais = (String)cuentasTelefonica[0].get('bi_country__c');
            }

        }
        
        List<Power_BI_link__c> links = [select id, link__c from Power_BI_link__c where cuenta__c =: idCuenta limit 1];
        if(links.size()>0){
            url = links[0].link__c;
        }else{
            links = [select id, link__c from Power_BI_link__c where pais__c =: pais limit 1];
            if(links.size()>0){
                url = links[0].link__c;
            }
        }
        
    }
}