src/objects/Power_BI_link__c.object
<CustomObject>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Power BI links</relationshipLabel>
        <relationshipName>Power_BI_links</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pais__c</fullName>
        <label>Pais</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Power BI link</label>
    <nameField>
        <label>Nombre de Power BI</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Power BI links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdminPowerBiController.cls
public class AdminPowerBiController {


    Public List<Power_BI_link__c> links {get;set;}
    Public Power_BI_link__c powerBiAInsertar {get;set;}
    public String idLinkABorrar {get; set;}
    
    public List<String> mensajesDeError {get; set;}
    
    public AdminPowerBiController(){
        mensajesDeError = new List<String>();
        powerBiAInsertar = new Power_BI_link__c();
        obtenerLinks();
    }
    
    public void obtenerLinks(){
        links = [select id, name, Cuenta__c, Link__c, Pais__c from Power_BI_link__c];
    }
    
    public void insertarLinks(){
		
        if(powerBiAInsertar.pais__c != null && powerBiAInsertar.cuenta__c != null ){
            mensajesDeError = new List<String>();
            mensajesDeError.add('Los links deben tener o pais o cuenta unicamente, no pueden tener definidos los dos parametros.');
        }
        
        if([select id from Power_BI_link__c where pais__c =: powerBiAInsertar.pais__c].size()>0){
            mensajesDeError = new List<String>();
            mensajesDeError.add('Ya existe un Link para este pais. Edite el existente o borrelo para poder crear uno nuevo.');
        }else{
            Insert powerBiAInsertar;
            obtenerLinks();
            powerBiAInsertar = new Power_BI_link__c();
            cleanErrors();
        }
        
    }
    
    public void borrarLink(){
        if(idLinkABorrar != null || idLinkABorrar != ''){
            List<Power_BI_link__c> linkABorrar = [select id from Power_BI_link__c where id =: idLinkABorrar];
            if(linkABorrar.size()>0){
                delete linkABorrar;
                obtenerLinks();
            }
        }
    }
    
    public void cleanErrors(){
        mensajesDeError = new List<String>();
    }
    
    public void guardar(){
        update links;
    }

}