src/objects/Region__c.object
<CustomObject>
    <description>Region where to work.</description>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipName>Child</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Geographical Region</label>
    <nameField>
        <label>Nombre de GAP Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Geographical Regions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_AdminProvenValueController.cls
@isTest
private class Test_AdminProvenValueController {

    static testMethod void myUnitTest() {
        
        Region__c regionGlobal = new Region__C(name='Global');
        insert regionGlobal;
        
        Region__c regionLocal = new Region__c(name='Local',Parent__c=regionGlobal.id);
        insert regionLocal;
        
        AdminProvenValueController controller = new AdminProvenValueController();        
        
        controller.newPruvenValue.Type__c = controller.getProvenValueTypes().get(0).getValue();
        controller.newPruvenValue.Unique_Value__c = 'Test'; 
        controller.regionId = controller.getRegions().get(0).getValue();
        controller.industry = controller.getIndustries().get(0).getValue();
        
        controller.InsertNew();
        
        controller.IdtoDelete = controller.newPruvenValue.id;
        controller.del();
        
    }

}