src/objects/SB_Cuenta_Pregunta__c.object
<CustomObject>
    <fields>
        <fullName>Pregunta__c</fullName>
        <label>Pregunta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Pregunta__c</fullName>
        <label>Super Ball - Pregunta</label>
        <referenceTo>Super_Ball_Pregunta__c</referenceTo>
        <relationshipLabel>SB - Cuenta - Preguntas (Super Ball - Pregunta)</relationshipLabel>
        <relationshipName>SB_Cuenta_Preguntas2</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SB - Cuenta - Pregunta</label>
    <nameField>
        <label>Nombre de SB - Cuenta - Pregunta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SB - Cuenta - Preguntas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Pregunta__c.object
<CustomObject>
    <fields>
        <fullName>Opciones_picklist__c</fullName>
        <label>Opciones picklist</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pregunta__c</fullName>
        <label>Pregunta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_pregunta__c</fullName>
        <label>Tipo de pregunta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si/no</fullName>
                </value>
                <value>
                    <fullName>Libre</fullName>
                </value>
                <value>
                    <fullName>Lista</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Super Ball - Pregunta</label>
    <nameField>
        <label>Nombre de Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Preguntas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PreguntaTipoListaController.cls
public class PreguntaTipoListaController {
	
    public Boolean initialized = false;
    public list<SelectOption> ValoresPickList {get;set;}
    public list<String> opciones {get;set;}
    public Super_Ball_Pregunta__c pregunta {get;set;}
    public SB_Cuenta_Pregunta__c preguntaCuenta {get;set;}
    
    public String idPregunta{ 
        get;
        set {
            idPregunta = value;
            if (!initialized) {
                Constructor();
                initialized = true;
            }
        }
    }
    
    public void constructor(){
        
        preguntaCuenta = [select id, Respuesta_libre__c, Super_Ball_Pregunta__c from SB_Cuenta_Pregunta__c where id =: idPregunta];
        pregunta = [select id, Pregunta__c, Tipo_de_pregunta__c, Opciones_picklist__c from Super_Ball_Pregunta__c where id =:preguntaCuenta.Super_Ball_Pregunta__c];
        
        
        opciones = new List<String>();
        ValoresPickList = new List<SelectOption>();
        
        if(pregunta.tipo_de_pregunta__c == 'Lista' && pregunta.Opciones_picklist__c != null){
            opciones = pregunta.Opciones_picklist__c.split(';');
        }
        
        ValoresPickList = obtenerValoresPickList();
    }
    
    public List<SelectOption> obtenerValoresPickList() {
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('--Ninguno--','--Ninguno--'));
        for(String valor: opciones){
            options.add(new SelectOption(valor,valor));    
        }
        
        return options; 
    }
    
    public void guardar(){
        system.debug(preguntaCuenta.Respuesta_libre__c);
        update preguntaCuenta;
    }
    
}