src/objects/SCP_Criteria_DCM__c.object
<CustomObject>
    <fields>
        <fullName>Competitors_Competitive_Standing__c</fullName>
        <label>Competitors Competitive Standing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Consideration__c</fullName>
        <label>Customer Consideration</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Our_Competitive_Standing__c</fullName>
        <label>Our Competitive Standing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SCP Criteria DCM</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de SCP Criteria DCM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SCP Criteria DCM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_DCMEvaluateCriteriaController.cls
@isTest
private class Test_DCMEvaluateCriteriaController {

    static testMethod void myUnitTest() {
        
        PageReference pageRef = Page.DCMEvaluateCriteria;
        Test.setCurrentPage(pageRef);
        
        Account acc = new Account(Name = 'Account test');
        insert acc;        
        Opportunity opp = new Opportunity(Name = 'Test Opp', accountid = acc.id, stageName = 'Open', closeDate = system.today());
        insert opp;
        
        
        ApexPages.currentPage().getParameters().put('id', opp.id);
        DCMEvaluateCriteriaController dcmController = new DCMEvaluateCriteriaController();
        
		dcmController.newCriteria = 'Test Criteria';
		
		dcmController.addNewCriteria();
		
		dcmController.getOurVK();
		dcmController.getOurVW();
		dcmController.getOurVS();
		dcmController.getOurNV();
		dcmController.getCompetitorVK();
		dcmController.getCompetitorVW();
		dcmController.getCompetitorVS();
		dcmController.getCompetitorNV();         
		dcmController.getNotEvaluatedDCM();
		dcmController.criteriaToEvaluate = 'Test Criteria';
		dcmController.popCriteriaEvaluation();
		SCP_Criteria_DCM__c myMewEval = new SCP_Criteria_DCM__c(Criteria__c = 'Test Criteria', Our_Competitive_Standing__c = 'HIGH', Customer_Consideration__c = 'HIGH', Competitors_Competitive_Standing__c = 'HIGH');                 
        dcmController.newEval = myMewEval;
        dcmController.InsertEvaluation();
        dcmController.delid = myMewEval.id;
        dcmController.saveEvaluatedDCM();
        dcmController.DeleteEvaluation();
        
    }
}