src/objects/Super_Ball_Arbol__c.object
<CustomObject>
    <fields>
        <fullName>Pais__c</fullName>
        <label>Pais</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>España</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Saudi Arabia</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Myanmar</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Financiero</fullName>
                </value>
                <value>
                    <fullName>Todos</fullName>
                </value>
                <value>
                    <fullName>Gobierno Provincial</fullName>
                </value>
                <value>
                    <fullName>Agricultura y pesca</fullName>
                </value>
                <value>
                    <fullName>Alimentación y Bebidas</fullName>
                </value>
                <value>
                    <fullName>Automoción</fullName>
                </value>
                <value>
                    <fullName>Banca</fullName>
                </value>
                <value>
                    <fullName>Construcción e inmobiliaria</fullName>
                </value>
                <value>
                    <fullName>Defensa</fullName>
                </value>
                <value>
                    <fullName>Educación</fullName>
                </value>
                <value>
                    <fullName>Farma</fullName>
                </value>
                <value>
                    <fullName>Gobierno Central</fullName>
                </value>
                <value>
                    <fullName>Gobierno Local</fullName>
                </value>
                <value>
                    <fullName>Industria</fullName>
                </value>
                <value>
                    <fullName>Justicia</fullName>
                </value>
                <value>
                    <fullName>Minería y Recursos Naturales</fullName>
                </value>
                <value>
                    <fullName>Ocio y Turismo</fullName>
                </value>
                <value>
                    <fullName>Petróleo y gas</fullName>
                </value>
                <value>
                    <fullName>Químicos</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Salud</fullName>
                </value>
                <value>
                    <fullName>Seguros</fullName>
                </value>
                <value>
                    <fullName>Servicios Profesionales</fullName>
                </value>
                <value>
                    <fullName>Tecnología y Electrónica</fullName>
                </value>
                <value>
                    <fullName>Telecom y Media</fullName>
                </value>
                <value>
                    <fullName>Transporte y Logística</fullName>
                </value>
                <value>
                    <fullName>Utilities</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Super Ball - Arbol</label>
    <nameField>
        <label>Nombre de Super Ball - Arbol</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Arboles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Super_Ball_Interlocutor__c.object
<CustomObject>
    <fields>
        <fullName>Contacto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contacto</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Super Ball - Interlocutores</relationshipLabel>
        <relationshipName>Super_Ball_Interlocutores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Interlocutores</relationshipLabel>
        <relationshipName>Super_Ball_Interlocutores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Interlocutor</label>
    <nameField>
        <label>Nombre de Super Ball - Interlocutor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Interlocutores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Nodo__c.object
<CustomObject>
    <fields>
        <fullName>Descripci_n__c</fullName>
        <label>Descripción</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Nodo_Padre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nodo Padre</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posicion__c</fullName>
        <label>Posicion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Arbol__c</fullName>
        <label>Super Ball - Arbol</label>
        <referenceTo>Super_Ball_Arbol__c</referenceTo>
        <relationshipLabel>Super Ball - Nodos</relationshipLabel>
        <relationshipName>Super_Ball_Nodos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Nodo</label>
    <nameField>
        <label>Nombre de Super Ball - Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Nodos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Pregunta__c.object
<CustomObject>
    <fields>
        <fullName>Dependencia_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependencia No</label>
        <referenceTo>Super_Ball_Pregunta__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas (Dependencia No)</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dependencia_Si__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependencia Si</label>
        <referenceTo>Super_Ball_Pregunta__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opciones_picklist__c</fullName>
        <label>Opciones picklist</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Posicion__c</fullName>
        <label>Posicion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pregunta__c</fullName>
        <label>Pregunta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Preguntas</relationshipLabel>
        <relationshipName>Super_Ball_Preguntas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tipo_de_pregunta__c</fullName>
        <label>Tipo de pregunta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Si/no</fullName>
                </value>
                <value>
                    <fullName>Libre</fullName>
                </value>
                <value>
                    <fullName>Lista</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>esHija__c</fullName>
        <defaultValue>false</defaultValue>
        <label>esHija</label>
        <type>Checkbox</type>
    </fields>
    <label>Super Ball - Pregunta</label>
    <nameField>
        <label>Nombre de Nodo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Preguntas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Recurso__c.object
<CustomObject>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Recursos</relationshipLabel>
        <relationshipName>Super_Ball_Recursos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Recurso</label>
    <nameField>
        <label>Nombre de Super Ball - Nodo Padre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Recursos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Super_Ball_Solucion__c.object
<CustomObject>
    <fields>
        <fullName>Posicion__c</fullName>
        <label>Posicion</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Super_Ball_Nodo__c</fullName>
        <label>Super Ball - Nodo</label>
        <referenceTo>Super_Ball_Nodo__c</referenceTo>
        <relationshipLabel>Super Ball - Soluciones</relationshipLabel>
        <relationshipName>Super_Ball_Soluciones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Super Ball - Solucion</label>
    <nameField>
        <label>Nombre de Super Ball - Solucion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Super Ball - Soluciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EditarArbolController.cls
public class EditarArbolController {
    
    Public String idArbol {get;set;}
    Public List<WppRamas> ramas {get;set;}
    Public Super_Ball_Nodo__c nodoCentral {get;set;}
    Public Super_Ball_Nodo__c nodoHijo {get;set;}
    Public Boolean render {get;set;}
    
    Public String idNodoPadre {get;set;}
    Public String idNodoABorrar {get;set;}
    Public String idPreguntaABorrar {get;set;}
    Public String idSolucionABorrar {get;set;}
    Public String idContactoABorrar {get;set;}
    Public String idRecursoABorrar {get;set;}
    Public String idPreguntaPadre {get;set;}
    
    Public Super_Ball_Arbol__c arbol {get;set;}
    Public Super_Ball_Pregunta__c preguntaAInsertar {get;set;}
    Public Super_Ball_Pregunta__c preguntaAInsertarSi {get;set;}
    Public Super_Ball_Pregunta__c preguntaAInsertarNo {get;set;}
    Public Super_Ball_Solucion__c solucionAInsertar {get; set;}
    Public Super_Ball_Interlocutor__c contactoAInsertar {get;set;}
    Public Super_Ball_Recurso__c recursoAInsertar {get;set;}	
    
    public EditarArbolController(){
        idArbol = ApexPages.currentPage().getParameters().get('Id');
        
        render = false;
        if(idArbol != null && idArbol != ''){
            render = true;
            arbol = [select id, name, pais__c, sector__c from Super_Ball_Arbol__c where id =: idArbol];
        }
        
        nodoCentral = new Super_Ball_Nodo__c();
        nodoHijo = new Super_Ball_Nodo__c();
        preguntaAInsertar = new Super_Ball_Pregunta__c();
        preguntaAInsertarSi = new Super_Ball_Pregunta__c();
        preguntaAInsertarNo = new Super_Ball_Pregunta__c();
        solucionAInsertar = new Super_Ball_Solucion__c();
        contactoAInsertar = new Super_Ball_Interlocutor__c();
        recursoAInsertar = new Super_Ball_Recurso__c();
        traerRamas();
    }
    
    public void traerRamas(){
        ramas = new List<WppRamas>();
        //Me traigo todos los nodos centrales.
        List<Super_Ball_Nodo__c> nodosCentrales = [select id, name, Descripci_n__c, posicion__c 
                                                   from Super_Ball_Nodo__c 
                                                   where Nodo_Padre__c = null and Super_Ball_Arbol__c =: idArbol order by createdDate asc];
        
        Set<Id> idNodosCentrales = new Set<Id>();
        for(Super_Ball_Nodo__c nodo: nodosCentrales){
            idNodosCentrales.add(nodo.id);
            ramas.add(new WppRamas(nodo));
        }
        
        if(idNodosCentrales.size()>0){
            //Me traigo los hijos y los hijos de los hijos.
            List<Super_Ball_Nodo__c> hijosDeNodos = [select id, Nodo_Padre__c, name, Descripci_n__c, posicion__c,
                                                     (select id, name, Descripci_n__c from Super_Ball_Nodos__r),
                                                     (select id, Tipo_de_pregunta__c, Opciones_picklist__c, Pregunta__c, posicion__c, Dependencia_Si__c, Dependencia_No__c,  Dependencia_Si__r.pregunta__c, Dependencia_No__r.pregunta__c 
                                                      from Super_Ball_Preguntas__r 
                                                      where esHija__c != true order by createdDate asc),
                                                     (select id, name, posicion__c from Super_Ball_Soluciones__r order by createdDate asc),
                                                     (select id, name, contacto__c from Super_Ball_Interlocutores__r order by createdDate asc),
                                                     (select id, name, link__c, posici_n__c from Super_Ball_Recursos__r order by createdDate asc)
                                                     from Super_Ball_Nodo__c 
                                                     where Nodo_Padre__c in: idNodosCentrales
                                                     order by createdDate asc];
            
            for(Super_Ball_Nodo__c nodoHijo: hijosDeNodos){
                for(WppRamas rama: ramas){
                    if(rama.nodo.id == nodoHijo.Nodo_Padre__c){
                        rama.nodosHijos.add(new WppRamas(nodoHijo, nodoHijo.Super_Ball_Nodos__r));
                    }
                }
            }
        }
    }
    
    public void InsertarNodoCentral(){
        nodoCentral.Super_Ball_Arbol__c = idArbol;
        nodoCentral.posicion__c = 0;
        nodoCentral.name=parsearString(nodoCentral.name);
        insert nodoCentral;
        nodoCentral = new Super_Ball_Nodo__c(); 
        traerRamas();
    }
    
    public String parsearString(String name){
        String parseado;
        if (name.contains('-')){
            parseado=name.replace('-', ' - ');
        } else {
            parseado=name;
        }
        if (name.contains('/')){
            parseado=name.replace('/', ' / ');
        } 
        return parseado;
    }
    
    public void InsertarNodoHijo(){
        
        if(idNodoPadre != null && idNodoPadre != ''){
            
            nodoHijo.Nodo_Padre__c = idNodoPadre;
            nodoHijo.posicion__c = 0;
            nodoHijo.Super_Ball_Arbol__c = idArbol;
            nodoHijo.name=parsearString(nodoHijo.name);
            insert nodoHijo;
            
            nodoHijo = new Super_Ball_Nodo__c();
            idNodoPadre = '';
            
            traerRamas();
        }
    }
    
    public void borrarNodo(){
        List<String> nodos = new List<String> ();
        nodos.add(idNodoABorrar);
        
        borrarHijos(nodos);
        
        delete [select id from Super_Ball_Nodo__c where id =: idNodoABorrar];
        idNodoABorrar = '';
        
        traerRamas();
    }
    
    public void borrarHijos(List<String> idNodos){
        List<Super_Ball_Nodo__c> nodos = [select id from Super_Ball_Nodo__c where Nodo_Padre__c In: idNodos];
        
        List<String> idHijosNodos = new List<String>();
        for(Super_Ball_Nodo__c nodo: nodos){
            idHijosNodos.add(nodo.id);    
        }
        
        if(nodos.size()>0){
            borrarHijos(idHijosNodos);
            delete nodos;
        }
    }
    
    public void insertarPregunta(){
        
        if(idNodoPadre != null && idNodoPadre != ''){
            
            preguntaAInsertar.Super_Ball_Nodo__c = idNodoPadre;
            preguntaAInsertar.posicion__c = 0;
            
            insert preguntaAInsertar;
            
            preguntaAInsertar = new Super_Ball_Pregunta__c();
            idNodoPadre = '';
            
            traerRamas();
        }
    }
    
    public void borrarPregunta(){
        delete [select id from Super_Ball_Pregunta__c where id =: idPreguntaABorrar];
        idPreguntaABorrar = '';
        
        traerRamas();
    }
    
    public void insertarSolucion(){
        
        if(idNodoPadre != null && idNodoPadre != ''){
            
            solucionAInsertar.Super_Ball_Nodo__c = idNodoPadre;
            solucionAInsertar.name=parsearString(solucionAInsertar.name);
            solucionAInsertar.posicion__c = 0;
            
            insert solucionAInsertar;
            
            solucionAInsertar = new Super_Ball_Solucion__c();
            idNodoPadre = '';
            
            traerRamas();
        }
    }
    
    public void borrarSolucion(){
        delete [select id from Super_Ball_Solucion__c where id =: idSolucionABorrar];
        idSolucionABorrar = '';
        
        traerRamas();
    }
    
    public void insertarContacto(){
        
        if(idNodoPadre != null && idNodoPadre != ''){
            
            contactoAInsertar.Super_Ball_Nodo__c = idNodoPadre;
            
            insert contactoAInsertar;
            
            contactoAInsertar = new Super_Ball_Interlocutor__c();
            idNodoPadre = '';
            
            traerRamas();
        }
    }
    
    public void borrarContacto(){
        delete [select id from Super_Ball_Interlocutor__c where id =: idContactoABorrar];
        idContactoABorrar = '';
        
        traerRamas();
    }
    
    public void insertarRecurso(){
        
        if(idNodoPadre != null && idNodoPadre != ''){
            
            recursoAInsertar.Super_Ball_Nodo__c = idNodoPadre;
            
            insert recursoAInsertar;
            
            recursoAInsertar = new Super_Ball_Recurso__c();
            idNodoPadre = '';
            
            traerRamas();
        }
    }
    
    public void borrarRecurso(){
        delete [select id from Super_Ball_Recurso__c where id =: idRecursoABorrar];
        idRecursoABorrar = '';
        
        traerRamas();
    }
    
    public void insertarPreguntaSi(){
        
        if(idNodoPadre != null && idNodoPadre != ''){
            
            preguntaAInsertarSi.Super_Ball_Nodo__c = idNodoPadre;
            preguntaAInsertarSi.esHija__c = true;
            insert preguntaAInsertarSi;
            
            system.debug(preguntaAInsertarSi);
            
            Super_Ball_Pregunta__c preguntaPadre = [select id, dependencia_si__c from Super_Ball_Pregunta__c where id=:idPreguntaPadre];
            preguntaPadre.dependencia_si__c = preguntaAInsertarSi.id;
            
            update preguntaPadre;
            
            preguntaAInsertarSi = new Super_Ball_Pregunta__c();
            idNodoPadre = '';
            idPreguntaPadre = '';
            
            traerRamas(); 
        }
        
        
    }
    
    public void insertarPreguntaNo(){
        
        if(idNodoPadre != null && idNodoPadre != ''){
            
            preguntaAInsertarNo.Super_Ball_Nodo__c = idNodoPadre;
            preguntaAInsertarNo.esHija__c = true;
            insert preguntaAInsertarNo;
            
            system.debug(preguntaAInsertarNo);
            
            Super_Ball_Pregunta__c preguntaPadre = [select id, dependencia_no__c from Super_Ball_Pregunta__c where id=:idPreguntaPadre];
            preguntaPadre.dependencia_no__c = preguntaAInsertarNo.id;
            
            update preguntaPadre;
            
            preguntaAInsertarNo = new Super_Ball_Pregunta__c();
            idNodoPadre = '';
            idPreguntaPadre = '';
            
            traerRamas(); 
        }
        
        
    }
    
    public PageReference irAAdminPowerBall() {    
        String url = Page.AdminSuperBall.getURL();
        return new PageReference (url);
    }
    
    public void guardar(){
        List<Super_Ball_Nodo__c> nodosAGuardar = new List<Super_Ball_Nodo__c>();
        List<Super_Ball_Nodo__c> nodosHijosAGuardar = new List<Super_Ball_Nodo__c>();
        
        for(WppRamas rama: ramas){
            nodosAGuardar.add(rama.nodo);
            if(rama.nodosHijos != null ){
                for(WppRamas ramaHija: rama.nodosHijos){
                    nodosHijosAGuardar.add(ramaHija.nodo);
                }
            }
        }
        
        List<Super_Ball_Pregunta__c> preguntasAGuardar = new List<Super_Ball_Pregunta__c>();
        for(Super_Ball_Nodo__c nodoHijo: nodosHijosAGuardar){
            preguntasAGuardar.addAll(nodoHijo.Super_Ball_Preguntas__r);
        }
        List<Super_Ball_Pregunta__c> preguntasSiAGuardar = new List<Super_Ball_Pregunta__c>();
        List<Super_Ball_Pregunta__c> preguntasNoAGuardar = new List<Super_Ball_Pregunta__c>();
        for(Super_Ball_Pregunta__c pregunta: preguntasAGuardar){
            if(pregunta.dependencia_si__c != null){
                Super_Ball_Pregunta__c nuevaPregunta = new Super_Ball_Pregunta__c();
                nuevaPregunta.id = pregunta.dependencia_si__c;
                nuevaPregunta.pregunta__c = pregunta.dependencia_si__r.pregunta__c;
                preguntasSiAGuardar.add(nuevaPregunta);
            }
            if(pregunta.dependencia_no__c != null){
                Super_Ball_Pregunta__c nuevaPregunta = new Super_Ball_Pregunta__c();
                nuevaPregunta.id = pregunta.dependencia_no__c;
                nuevaPregunta.pregunta__c = pregunta.dependencia_no__r.pregunta__c;
                preguntasNoAGuardar.add(nuevaPregunta);
            }
        }
        preguntasAGuardar.addAll(preguntasSiAGuardar);
        preguntasAGuardar.addAll(preguntasNoAGuardar);
        
        List<Super_Ball_Solucion__c> solucionAGuardar = new List<Super_Ball_Solucion__c>();
        for(Super_Ball_Nodo__c nodoHijo: nodosHijosAGuardar){
            solucionAGuardar.addAll(nodoHijo.Super_Ball_Soluciones__r);
        } 
        
        List<Super_Ball_Interlocutor__c> interlocutoresAGuardar = new List<Super_Ball_Interlocutor__c>();
        for(Super_Ball_Nodo__c nodoHijo: nodosHijosAGuardar){
            interlocutoresAGuardar.addAll(nodoHijo.Super_Ball_Interlocutores__r);
        }    
        
        List<Super_Ball_Recurso__c> recursosAGuardar = new List<Super_Ball_Recurso__c>();
        for(Super_Ball_Nodo__c nodoHijo: nodosHijosAGuardar){
            recursosAGuardar.addAll(nodoHijo.Super_Ball_Recursos__r);
        }    
        
        
        update nodosAGuardar;
        update nodosHijosAGuardar;
        update preguntasAGuardar;
        update solucionAGuardar;
        update interlocutoresAGuardar;
        update recursosAGuardar;
    }
    //===========================================================================
    Public Class WppRamas{
        
        public Super_Ball_Nodo__c nodo {get;set;}
        public List<WppRamas> nodosHijos {get;set;}
        
        public WppRamas (Super_Ball_Nodo__c padre){
            nodo = padre;
            nodosHijos = new List<WppRamas>();
        }
        
        public WppRamas (Super_Ball_Nodo__c padre, list<WppRamas> hijos){
            nodo = padre;
            nodosHijos = new List<WppRamas>();
            if(hijos != null){
                nodosHijos = hijos;
            }
        }
        
        public WppRamas (Super_Ball_Nodo__c padre, list<Super_Ball_Nodo__c> hijos){
            nodo = padre;
            nodosHijos = new List<WppRamas>();
            for(Super_Ball_Nodo__c hijo: hijos){
                nodosHijos.add(new WppRamas(hijo));
            }
        }
        
    }
    
}